### PR TITLE
Solid topography

### PR DESCRIPTION
**Pull request by ikeough**
BACKGROUND:
Topography in Elements has no thickness. For "horizontal" applications like tunnels, this results in the topography floating above the underground elements, and the topography not being able to take part fully in CSG operations.

DESCRIPTION:
This PR adds thickness to topography. By default, the thickness is set to 500m below the lowest elevation of the topography, but can be set to any number greater than 1. Giving topography thickness is achieved by creating a new property `Topography.DepthMesh` which represents the sides and bottom of the topography as a separate element, allowing the mesh to have a different texture.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

image
image

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/537)

### CODE REVIEW

**Comment by ikeough** [comment]
I'm considering removing Topography's inheritance from MeshElement, because we don't need the topography's surface mesh to serialize. The surface mesh is created during construction using a smaller amount of data in `Elevations` `CellWidth` and `CellHeight`. In this way we could have `Topography.SurfaceMesh` to visualize the surface and `Topography.DepthMesh` to visualize the thickness of the topography, and neither would serialize to JSON.

**Review by serenayl — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1, 2 of 3 files at r3, 7 of 165 files at r6, 26 of 26 files at r8.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/537)* status: 41 of 44 files reviewed, 9 unresolved discussions (waiting on @ikeough)

*[a discussion](https://reviewable.io/reviews/hypar-io/elements/537#-MUnvuKsDk01AMnD8lro:-MUnvuKsDk01AMnD8lrp:bhcpz8a) (no related file):*
I tried something silly and set the `AbsoluteMinimumElevationn` to a large value I knew would be higher than the topo, and I get funny results of course. Is this something we want to defend against?


---
___
*[Elements/src/Topography.cs, line 89 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnvHyM2F-C9P3SE_XR:-MUnvHyM2F-C9P3SE_XS:b-8f68xs) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L89)):*
> ```
> AbsoluteMinimumElevationn
> ```
Spelling: has 2 ns on end
___
*[Elements/src/Topography.cs, line 122 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnzpqL1XUEWFhYWnGV:-MUnzpqL1XUEWFhYWnGW:b-xepr93) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L122)):*
> ```
> this._mesh = new Mesh();
> ```
If `GenerateMeshAndSetInternals()` sets `this._mesh`, is this first step still necessary?
___
*[Elements/src/Topography.cs, line 130 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnuvG_0X5MS4zVvYkV:-MUnuvG_0X5MS4zVvYkW:btpjoxe) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L130)):*
> ```
> double depth
> ```
It may be helpful to rename this variable to something like `minElevation` or `bottomElevation` or something to reflect its meaning: I had assumed this was equivalent to `DepthBelowMinimumElevation`
___
*[Elements/src/Topography.cs, line 174 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnzdpVBzyuW0oOajqV:-MUnzdpVBzyuW0oOajqW:blp46hr) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L174)):*
> ```Smalltalk
>             this.CellHeight = cellHeight;
> 
>             GenerateMeshAndSetInternals();
> ```

Is there a way to consolidate the logic of this constructor and the other one? There is a lot of repeat logic between these two functions, especially the block starting with `GenerateMeshAndSetInternals` and ending with attaching the callback for `PropertyChanged`
___
*[Elements/src/Topography.cs, line 217 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUo-KWq-NHapmhrjQLY:-MUo-KWq-NHapmhrjQLZ:b-7lza78) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L217)):*
> ```
> double depth
> ```
This parameter was added but it doesn't look like it's being used in this method
___
*[Elements/src/Topography.cs, line 271 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUo08YT2G2g8jb_ppcz:-MUo08YT2G2g8jb_ppd-:bnplhv4) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L271)):*
> ```Smalltalk
>         }
> 
>         private static Mesh CreateSidesAndBottomMesh(Mesh mesh,
> ```

This method does appear to work, but in its current state I would be apprehensive about digging into it to find future bugs or something without more comments to explain the steps and what the variables do. Is it possible add a bit more explanation too?
___
*[Elements/test/TopographyTests.cs, line 188 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnu6hO7KSc-RmGtmMD:-MUnu6hO7KSc-RmGtmME:bq99umf) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/test/TopographyTests.cs#L188)):*
> ```
>  var minElevation = double.MaxValue;
> ```
What situation is this protecting against? Is it in case topography.MinElevation is higher than the maximum value available in `double`, even though it is a `double` itself?
___
*[Elements/test/TopographyTests.cs, line 255 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnxKLd0nJ1AFINFviu:-MUnxKLd0nJ1AFINFviv:b-s7yqpi) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/test/TopographyTests.cs#L255)):*
> ```
> public void Tunnel
> ```
The outcome of this test for me doesn't look the way I would expect it to?

**Review by ikeough — COMMENTED** [review]
> Reviewed 5 of 172 files at r12, 44 of 44 files at r15, 4 of 7 files at r18.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/537)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @serenayl)

*[a discussion](https://reviewable.io/reviews/hypar-io/elements/537#-MUnvuKsDk01AMnD8lro:-MW1NUdv1ZKj1q1E7P5b:b-896fix) (no related file):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

I tried something silly and set the `AbsoluteMinimumElevationn` to a large value I knew would be higher than the topo, and I get funny results of course. Is this something we want to defend against?


</blockquote></details>

Done.

---
___
*[Elements/src/Topography.cs, line 89 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnvHyM2F-C9P3SE_XR:-MWBy6DA2yhoahmAD1vc:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L89)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

> ```
> AbsoluteMinimumElevationn
> ```
Spelling: has 2 ns on end
</blockquote></details>

Done.
___
*[Elements/src/Topography.cs, line 122 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnzpqL1XUEWFhYWnGV:-MWByGAu2W60JmeiDouT:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L122)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

> ```
> this._mesh = new Mesh();
> ```
If `GenerateMeshAndSetInternals()` sets `this._mesh`, is this first step still necessary?
</blockquote></details>

Done.
___
*[Elements/src/Topography.cs, line 130 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnuvG_0X5MS4zVvYkV:-MWBzagG7VBG5nr7HWaF:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L130)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

> ```
> double depth
> ```
It may be helpful to rename this variable to something like `minElevation` or `bottomElevation` or something to reflect its meaning: I had assumed this was equivalent to `DepthBelowMinimumElevation`
</blockquote></details>

Done.
___
*[Elements/src/Topography.cs, line 174 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnzdpVBzyuW0oOajqV:-MWBybW-5GzWrr7SreeJ:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L174)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

Is there a way to consolidate the logic of this constructor and the other one? There is a lot of repeat logic between these two functions, especially the block starting with `GenerateMeshAndSetInternals` and ending with attaching the callback for `PropertyChanged`
</blockquote></details>

Done.
___
*[Elements/src/Topography.cs, line 217 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUo-KWq-NHapmhrjQLY:-MWByho2ElN6EFr-cnbJ:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/src/Topography.cs#L217)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

> ```
> double depth
> ```
This parameter was added but it doesn't look like it's being used in this method
</blockquote></details>

Done.
___
*[Elements/test/TopographyTests.cs, line 188 at r8](https://reviewable.io/reviews/hypar-io/elements/537#-MUnu6hO7KSc-RmGtmMD:-MWBz7by4elv3OhnKRJQ:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0b5c92b0d2ebb062a73a355214efc70c8d0e5afd/Elements/test/TopographyTests.cs#L188)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

> ```
>  var minElevation = double.MaxValue;
> ```
What situation is this protecting against? Is it in case topography.MinElevation is higher than the maximum value available in `double`, even though it is a `double` itself?
</blockquote></details>

Done.

**Review by serenayl — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/537#-:-MWP7KYFDBqlDzUfcCLJ:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ikeough)

**Pull request merged**
