### PR TITLE
Door-representation-improvements-ak

### PR DESCRIPTION
**Pull request by anthonie-kramer**
BACKGROUND:
- The door class needed updates to include representations. I have also done a bit of refactoring to include Door specific types within the same file. This includes changes from Serhii at AMC.

DESCRIPTION:
- Provides multiple representations for different parts of the door. Provides additional simplifications to reduce extra code.

TESTING:
- This is now used in the Doors function in this workflow in test mode:
https://hypar.io/workflows/46428205-afdf-41bd-af52-4624c8e9f88e?view=b09eebe9-9857-4fcf-92e4-e4173e928289
  
FUTURE WORK:
- Doors could probably undergo another round of refactoring to clean up and we should think about grouping other "BIM" types in Elements

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1057)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1057)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @anthonie-kramer)

___
*[`Elements/src/Door.cs` line 172 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNiSGN7ywDLjP-9wc2:-NjNiSGN7ywDLjP-9wc3:b-47r4f3) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L172)):*
> ```Smalltalk
>                 {
>                         var representationInstances = new List<RepresentationInstance>()
>             {
> ```

this formatting looks pretty weird.
___
*[`Elements/src/Door.cs` line 207 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNic7K3A5DQxD1iP4Q:-NjNic7K3A5DQxD1iP4R:b-2twd44) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L207)):*
> ```Smalltalk
>                 private RepresentationInstance CreateDoorCurveRepresentation()
>                 {
>                         var points = CollectPointsForSchematicVisualization();
> ```

in all of the methods  that make representations it seems like we're always making a new RepresentationInstance for each door, but a big reason to move to RepresentationInstances is so that we can re-use instances.  This will keep the glb model size down which makes function execution faster.
___
*[`Elements/src/Door.cs` line 380 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNixZs3Ueul4xEf446:-NjNixZs3Ueul4xEf447:bhyufs9) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L380)):*
> ```Smalltalk
>         }
> 
>         public enum DoorOpeningSide
> ```

in general we like to give classes and enums their own file.  looks like these got merged in for some reason?
___
*[`Elements/src/StandardWall.cs` line 122 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNjvNf9-Xf2sSvJgwI:-NjNjvNf9-Xf2sSvJgwJ:bmxmiy0) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/StandardWall.cs#L122)):*
> ```Smalltalk
>             // Opening transform is still off... `outOfPlane` added because transform is not working correctly
>             var outOfPlane = xAxis.Cross(Vector3.ZAxis);
>             // Opening transform is still off?
> ```

are these comments correct? does this adjustment fix the opening transform or not?
___
*[`Elements/test/DoorTest.cs` line 17 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNk6Hi9CqfHlKEBUMS:-NjNk6Hi9CqfHlKEBUMT:b-g4uffc) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/test/DoorTest.cs#L17)):*
> ```Smalltalk
>         public void Example()
>         {
>             this.Name = "Elements_Door";
> ```

use `nameof(MakeDoorElement)` and change the name of this method to `MakeDoorElement`  keeps the names in sync
___
*[`Elements/test/DoorTest.cs` line 22 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNk3M64hnVpKdIFz20:-NjNk3M64hnVpKdIFz21:b-lgdue2) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/test/DoorTest.cs#L22)):*
> ```Smalltalk
>             var wall = new StandardWall(line, 0.1, 3.0);
>             var door = new Door(wall.CenterLine, 0.5, 2.0, 2.0, Door.DOOR_THICKNESS, DoorOpeningSide.LeftHand, DoorOpeningType.SingleSwing);
>             wall.AddDoorOpening(door);
> ```

can we make an assertion about the wall having an opening here.

**Review by anthonie-kramer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1057)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Door.cs` line 172 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNiSGN7ywDLjP-9wc2:-NjNq6yy7OrZalj9IwZ6:b-2oacm4) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L172)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

this formatting looks pretty weird.
</blockquote></details>

Good catch, I'll fix
___
*[`Elements/src/Door.cs` line 207 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNic7K3A5DQxD1iP4Q:-NjNq8gH1382kr_lphew:brvo1xb) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L207)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

in all of the methods  that make representations it seems like we're always making a new RepresentationInstance for each door, but a big reason to move to RepresentationInstances is so that we can re-use instances.  This will keep the glb model size down which makes function execution faster.
</blockquote></details>

What is the expected process? Should we always create representations in the function? We could do this automatically by comparing elements when they are created and seeing if they have identical properties, and then re-using the representation. I'd like to keep this as simple as possible without requiring the user to manage representations. 
___
*[`Elements/src/Door.cs` line 380 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNixZs3Ueul4xEf446:-NjNqo4VDbmEbKMrvTT2:bwxzxzv) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L380)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

in general we like to give classes and enums their own file.  looks like these got merged in for some reason?
</blockquote></details>

I was trying to de-clutter the Elements folder... I could put this into the Utilities folder... I think this might be where we should break out the BIM stuff into their own folders. I just didn't want Enum files in the src folder
___
*[`Elements/src/StandardWall.cs` line 122 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNjvNf9-Xf2sSvJgwI:-NjNr81fBpo8_TEQ-sOa:b-5mw4c9) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/StandardWall.cs#L122)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

are these comments correct? does this adjustment fix the opening transform or not?
</blockquote></details>

Done. Removed
___
*[`Elements/test/DoorTest.cs` line 17 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNk6Hi9CqfHlKEBUMS:-NjNtDQZEGWRX4M4QtXv:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/test/DoorTest.cs#L17)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

use `nameof(MakeDoorElement)` and change the name of this method to `MakeDoorElement`  keeps the names in sync
</blockquote></details>

Done.
___
*[`Elements/test/DoorTest.cs` line 22 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNk3M64hnVpKdIFz20:-NjNtCw2BQPx4YrJ0WPl:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/test/DoorTest.cs#L22)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can we make an assertion about the wall having an opening here.
</blockquote></details>

Done.

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1057)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @anthonie-kramer)

___
*[`Elements/src/Door.cs` line 207 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNic7K3A5DQxD1iP4Q:-NjOSDcF7BLN0X5WzEyS:bkwgukq) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L207)):*
<details><summary><i>Previously, anthonie-kramer (Anthonie Kramer) wrote…</i></summary><blockquote>

What is the expected process? Should we always create representations in the function? We could do this automatically by comparing elements when they are created and seeing if they have identical properties, and then re-using the representation. I'd like to keep this as simple as possible without requiring the user to manage representations.
</blockquote></details>

great Q, I don't think we've really formalized the pattern, but here's a doc that Kate sent to me https://www.notion.so/hyparaec/Multiple-Representations-b8a5754229c940698c5fb73608e6bd8c?pvs=4  
and here's a PR where I'm starting to do this for fittings. https://github.com/hypar-io/Elements/pull/1056/files#diff-cf24189f505ad5e3c1484c59c3aa75ffb8324341ce1a61717c47af0410a4b2f5
I opted for adding a hashing method on the class that helped determine if something should be re-used.  if you like this pattern we can discuss with kate if this could be elevated to "infrastructure"
___
*[`Elements/src/Door.cs` line 380 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNixZs3Ueul4xEf446:-NjOT94H6BqJXEto49QJ:bb62yv) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L380)):*
<details><summary><i>Previously, anthonie-kramer (Anthonie Kramer) wrote…</i></summary><blockquote>

I was trying to de-clutter the Elements folder... I could put this into the Utilities folder... I think this might be where we should break out the BIM stuff into their own folders. I just didn't want Enum files in the src folder
</blockquote></details>

ah, well a folder sounds fine to me!  you could make one for 'enums' or for 'doors' or .... you could start the BIM folder?  I think having separate files makes code much easier to navigate though.

**Review by anthonie-kramer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1057)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Door.cs` line 207 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNic7K3A5DQxD1iP4Q:-NjT5Vn44PasGVYEewFg:b-nrmmhj) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L207)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

great Q, I don't think we've really formalized the pattern, but here's a doc that Kate sent to me https://www.notion.so/hyparaec/Multiple-Representations-b8a5754229c940698c5fb73608e6bd8c?pvs=4  
and here's a PR where I'm starting to do this for fittings. https://github.com/hypar-io/Elements/pull/1056/files#diff-cf24189f505ad5e3c1484c59c3aa75ffb8324341ce1a61717c47af0410a4b2f5
I opted for adding a hashing method on the class that helped determine if something should be re-used.  if you like this pattern we can discuss with kate if this could be elevated to "infrastructure"
</blockquote></details>

Added a comment to the notion doc... Let me know if you want to discuss the solution in more detail and we can start building out a standard approach.
___
*[`Elements/src/Door.cs` line 380 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNixZs3Ueul4xEf446:-NjPXi1S6K5v2YvsB9gi:b-eonacy) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L380)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

ah, well a folder sounds fine to me!  you could make one for 'enums' or for 'doors' or .... you could start the BIM folder?  I think having separate files makes code much easier to navigate though.
</blockquote></details>

Done. Also started a BIM folder and updated the Doors namespace... we should migrate other BIM things into it in a future refactor.

**Review by anthonie-kramer — COMMENTED** [review]
This should be the final version... until we find a generic solution for storage

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1057#-:-NjUUiu508lE0NVTEfUD:b1cnbeo)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Door.cs` line 207 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNic7K3A5DQxD1iP4Q:-NjUUevUEvF3HzjOWoOZ:b-3khvgs) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L207)):*
<details><summary><i>Previously, anthonie-kramer (Anthonie Kramer) wrote…</i></summary><blockquote>

Added a comment to the notion doc... Let me know if you want to discuss the solution in more detail and we can start building out a standard approach.
</blockquote></details>

Added a storage class and provided some additional updates.

**Review by wynged — CHANGES_REQUESTED** [review]
just one things needs to be renamed :)

> Reviewed 7 of 8 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1057#-:-NjhTCua-L7dfnaeJAMB:b-pv5dze)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @anthonie-kramer)

___
*[`Elements/src/BIM/Door/DoorRepresentationStorage.cs` line 9 at r4](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjhT55F7vozvLRBwHQI:-NjhT55F7vozvLRBwHQJ:b1u9lm3) ([raw file](https://github.com/hypar-io/Elements/blob/f3e9129e182b540739f885a867dab8f7235270ea/Elements/src/BIM/Door/DoorRepresentationStorage.cs#L9)):*
> ```Smalltalk
>     static class DoorRepresentationStorage
>     {
>         private static readonly Dictionary<string, List<RepresentationInstance>> _fittings = new Dictionary<string, List<RepresentationInstance>>();
> ```

rename to not be _fittings
___
*[`Elements/src/Door.cs` line 207 at r1](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjNic7K3A5DQxD1iP4Q:-NjTI2QeDiXw38_oY65x:bbqour1) ([raw file](https://github.com/hypar-io/Elements/blob/cef84bb274a126fe291d3593797c3d3edcf7dab1/Elements/src/Door.cs#L207)):*
<details><summary><i>Previously, anthonie-kramer (Anthonie Kramer) wrote…</i></summary><blockquote>

Added a storage class and provided some additional updates.
</blockquote></details>

done lgtm

**Review by anthonie-kramer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1057)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/BIM/Door/DoorRepresentationStorage.cs` line 9 at r4](https://reviewable.io/reviews/hypar-io/Elements/1057#-NjhT55F7vozvLRBwHQI:-NjhnnBDCn5TRdqC3rWM:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/f3e9129e182b540739f885a867dab8f7235270ea/Elements/src/BIM/Door/DoorRepresentationStorage.cs#L9)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

rename to not be _fittings
</blockquote></details>

Done.

**Review by wynged — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1057#-:-Nji-Ivh4lLBsF6ZoAvm:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
