### PR TITLE
Working catalog code generation and saving

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- With the ability to export catalogs from Revit comes the desire to generate useful code from those catalogs.

DESCRIPTION:
- Add a CatalogGenerator that will generate a static class with the catalog contents set as static properties.
- Add a test that will demonstrate it in action.
- Allow loading glbs into a combined model from S3 by reading URIs (even local paths) into streams.
- Add contentCatalog de/serialization logic
- Add content element tests, including catalog serialization tests.

TESTING:
- Run the tests.
- Install the CLI locally by pulling hypar branch, it uses this work.
  
FUTURE WORK:
- make a more sensible catalog de/serialization method.  We use a model because ContentElements has to inherit from GeometricElement to gain instanceing, and Elements don't serialize as individual objects in a sensible way because of the associated JSON converter and custom logic for models.

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 15 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)* status: 15 of 17 files reviewed, 4 unresolved discussions (waiting on @andrewheumann and @wynged)

___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 870 at r1](https://reviewable.io/reviews/hypar-io/elements/410#-MKBmm-XC3V1VEy4YVPg:-MKBmm-XC3V1VEy4YVPh:b-u9p8mw) ([raw file](https://github.com/hypar-io/elements/blob/bf18f7be79f9e7a04dc5d6d33f4545a3c89bf360/Elements/src/Serialization/glTF/GltfExtensions.cs#L870)):*
> ```Smalltalk
>                     Stream glbStream = GetGlbStreamFromPath(content.GltfLocation);
>                     if (glbStream != null)
>                     // if (File.Exists(content.GltfLocation))
> ```

remove comment
___
*[Elements/src/Serialization/JSON/JsonInheritanceConverter.cs, line 82 at r1](https://reviewable.io/reviews/hypar-io/elements/410#-MKBmy6M2s233jF_RQyw:-MKBmy6M2s233jF_RQyx:b-jlzg7g) ([raw file](https://github.com/hypar-io/elements/blob/bf18f7be79f9e7a04dc5d6d33f4545a3c89bf360/Elements/src/Serialization/JSON/JsonInheritanceConverter.cs#L82)):*
I know it will default to false, but it might be nice to explicitly set 
>         public static bool ElementwiseSerialization { get; set; } = false;
___
*[Elements/test/ContentTests.cs, line 86 at r1](https://reviewable.io/reviews/hypar-io/elements/410#-MKBo5g_13k_lFKcwrJS:-MKBo5g_13k_lFKcwrJT:bvvhm4i) ([raw file](https://github.com/hypar-io/elements/blob/bf18f7be79f9e7a04dc5d6d33f4545a3c89bf360/Elements/test/ContentTests.cs#L86)):*
> ```Smalltalk
>             // var threeBox = boxType2.CreateInstance(new Transform(new Vector3(15, 0, 0)), "then two");
>             // model.AddElement(threeBox);
>             var beam = new Beam(new Line(new Vector3(), new Vector3(0, 5, -0.5)), new Circle(new Vector3(), 0.3).ToPolygon());
> ```

what is the Beam doing in this test?  also probably nix the commented stuff
___
*[Elements.CodeGeneration/src/TypeGenerator.cs, line 91 at r1](https://reviewable.io/reviews/hypar-io/elements/410#-MKBopYhEMxoPWmlvRBg:-MKBopYhEMxoPWmlvRBh:bt8mvws) ([raw file](https://github.com/hypar-io/elements/blob/bf18f7be79f9e7a04dc5d6d33f4545a3c89bf360/Elements.CodeGeneration/src/TypeGenerator.cs#L91)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The directory in which to find code templates. Some execution contexts require this to be overridden as the
> ```

yesssssss love a typo fix :smile:

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)* status: 12 of 19 files reviewed, 4 unresolved discussions (waiting on @andrewheumann)

___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 870 at r1](https://reviewable.io/reviews/hypar-io/elements/410#-MKBmm-XC3V1VEy4YVPg:-MKDfX-C3iIg8SLPVMq0:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/bf18f7be79f9e7a04dc5d6d33f4545a3c89bf360/Elements/src/Serialization/glTF/GltfExtensions.cs#L870)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.
___
*[Elements/src/Serialization/JSON/JsonInheritanceConverter.cs, line 82 at r1](https://reviewable.io/reviews/hypar-io/elements/410#-MKBmy6M2s233jF_RQyw:-MKDfhHq8uClzINFsVsy:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/bf18f7be79f9e7a04dc5d6d33f4545a3c89bf360/Elements/src/Serialization/JSON/JsonInheritanceConverter.cs#L82)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I know it will default to false, but it might be nice to explicitly set 
>         public static bool ElementwiseSerialization { get; set; } = false;

</blockquote></details>

Done.
___
*[Elements/test/ContentTests.cs, line 86 at r1](https://reviewable.io/reviews/hypar-io/elements/410#-MKBo5g_13k_lFKcwrJS:-MKDfjY39EJN6J5_MDl8:bnxde2l) ([raw file](https://github.com/hypar-io/elements/blob/bf18f7be79f9e7a04dc5d6d33f4545a3c89bf360/Elements/test/ContentTests.cs#L86)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

what is the Beam doing in this test?  also probably nix the commented stuff
</blockquote></details>

ok I think.  commented stuff is back.  Beam helps provide scale
___
*[Elements.CodeGeneration/src/TypeGenerator.cs, line 91 at r1](https://reviewable.io/reviews/hypar-io/elements/410#-MKBopYhEMxoPWmlvRBg:-MKDfr5R6OH161vpvl1j:bkfh1au) ([raw file](https://github.com/hypar-io/elements/blob/bf18f7be79f9e7a04dc5d6d33f4545a3c89bf360/Elements.CodeGeneration/src/TypeGenerator.cs#L91)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

yesssssss love a typo fix :smile: 
</blockquote></details>

done.  I <3 my new spellchecker

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @andrewheumann and @wynged)

___
*[Elements/src/Geometry/BBox3.cs, line 85 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf1VdVEhjeTkXhfJVd:-MKf1VdVEhjeTkXhfJVe:b-r8yqdi) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements/src/Geometry/BBox3.cs#L85)):*
> ```Smalltalk
>         public BBox3 Transformed(Transform transform)
>         {
>             return new BBox3(transform.OfPoint(this.Min), transform.OfPoint(this.Max));
> ```

But that's not really a transform of the box — I am not convinced bboxes should be transformable (unless they can also support orientation)
___
*[Elements/src/Serialization/glTF/GltfMergingUtils.cs, line 117 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf2Gui-8_5XGib7v4u:-MKf2Gui-8_5XGib7v4v:b1e7u3q) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements/src/Serialization/glTF/GltfMergingUtils.cs#L117)):*
> ```Smalltalk
>                     else
>                     {
>                         prim.Material = 0;  // This assumes that the default material is at index 0
> ```

Did you solve the issue where the `shouldAddMaterials=false` option would fail if there were no materials at all in the scene? 
___
*[Elements.CodeGeneration/src/CatalogGenerator.cs, line 88 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf3W2o9CxyUW_xyCzb:-MKf3W2o9CxyUW_xyCzc:b-puz2id) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements.CodeGeneration/src/CatalogGenerator.cs#L88)):*
> ```Smalltalk
>                             break;
>                         case Guid guid:
>                             codeToAdd = $"new Guid(\"{guid.ToString()}\")";
> ```

I don't think ToString() is necessary inside $"" string interpolation (could be wrong)
___
*[Elements.CodeGeneration/src/TypeGenerator.cs, line 71 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf3rir9Mf-pNjt2AsK:-MKf3rir9Mf-pNjt2AsL:blqi4vr) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements.CodeGeneration/src/TypeGenerator.cs#L71)):*
> ```Smalltalk
>                 "https://dev-api.hypar.io/schemas/Vertex",
>                 "https://hypar.io/Schemas/Geometry/Color.json",
>                 "https://dev-api.hypar.io/schemas/ContentElement",
> ```

should we add the prod urls to these now so once they're on prod we won't have to change anything?

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @andrewheumann and @wynged)

___
*[Elements.CodeGeneration/src/CatalogGenerator.cs, line 142 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf46vyBbIvWocBDPzZ:-MKf46vyBbIvWocBDPz_:b-rqrag3) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements.CodeGeneration/src/CatalogGenerator.cs#L142)):*
> ```Smalltalk
>         private static string GetContentsOfUri(string uri)
>         {
>             if (uri.StartsWith("https"))
> ```

is it conceivable that if someone else was using this library they'd have non https urls? maybe just make it http unless I'm missing something?

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)* status: all files reviewed, 5 unresolved discussions (waiting on @wynged)

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)* status: all files reviewed, 5 unresolved discussions (waiting on @andrewheumann)

___
*[Elements/src/Geometry/BBox3.cs, line 85 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf1VdVEhjeTkXhfJVd:-MKf5aWx5ham_xbd0_VV:b7az9tl) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements/src/Geometry/BBox3.cs#L85)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

But that's not really a transform of the box — I am not convinced bboxes should be transformable (unless they can also support orientation)
</blockquote></details>

done.  turned into Translated
___
*[Elements/src/Serialization/glTF/GltfMergingUtils.cs, line 117 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf2Gui-8_5XGib7v4u:-MKf9ho-Cgm66AEsm1z9:b-9rmdyf) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements/src/Serialization/glTF/GltfMergingUtils.cs#L117)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Did you solve the issue where the `shouldAddMaterials=false` option would fail if there were no materials at all in the scene? 
</blockquote></details>

done.  I believe so. but can't quite remember the situation where you ran into it. I just tested by setting shouldAddMaterials=false and ran the test which now has no elements besides the imported ones.  got this in our viewer.  

___
*[Elements.CodeGeneration/src/CatalogGenerator.cs, line 88 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf3W2o9CxyUW_xyCzb:-MKf5v-00KsxacRZ1dkC:b-i6bgzx) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements.CodeGeneration/src/CatalogGenerator.cs#L88)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I don't think ToString() is necessary inside $"" string interpolation (could be wrong)
</blockquote></details>

done.  I think your right.
___
*[Elements.CodeGeneration/src/CatalogGenerator.cs, line 142 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf46vyBbIvWocBDPzZ:-MKf6Is0-2PhjYWYNd6g:b-f1brzr) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements.CodeGeneration/src/CatalogGenerator.cs#L142)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

is it conceivable that if someone else was using this library they'd have non https urls? maybe just make it http unless I'm missing something?
</blockquote></details>

ok.  I guess it is possible, and we use a more permissive check for schemas.  I've copied that one.
___
*[Elements.CodeGeneration/src/TypeGenerator.cs, line 71 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf3rir9Mf-pNjt2AsK:-MKf75Go1wSYzkwhBe0y:b-xpysu0) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements.CodeGeneration/src/TypeGenerator.cs#L71)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

should we add the prod urls to these now so once they're on prod we won't have to change anything?
</blockquote></details>

done.  sure why not.  also alphabetized within that section.

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)* status: all files reviewed, 4 unresolved discussions (waiting on @andrewheumann and @wynged)

___
*[Elements/src/Geometry/BBox3.cs, line 85 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf1VdVEhjeTkXhfJVd:-MKfBkVq7UiuAWoj7-_t:boj1jev) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements/src/Geometry/BBox3.cs#L85)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

done.  turned into Translated
</blockquote></details>

did you? maybe not pushed?

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @andrewheumann)

___
*[Elements/src/Geometry/BBox3.cs, line 85 at r2](https://reviewable.io/reviews/hypar-io/elements/410#-MKf1VdVEhjeTkXhfJVd:-MKfC4zX2G0fgiMLJ38q:b-pxtqsy) ([raw file](https://github.com/hypar-io/elements/blob/6eeda54e7d0131abcf0a845088024f9fdcb3b79f/Elements/src/Geometry/BBox3.cs#L85)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

did you? maybe not pushed?
</blockquote></details>

uhhh, yea!  :P

**Review by andrewheumann — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/410)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
