### PR TITLE
Create a Grid2d from a polygon, origin, and u and v directions

### PR DESCRIPTION
**Pull request by serenayl**
BACKGROUND:
- Custom grid functions required more fine control of Grid2d work, especially in being able to create a bounded grid from an origin and UV directions, and automatically expanding that domain to encompass the boundary.

DESCRIPTION:
- Adds additional functionality to `Line.ExtendTo(IEnumerable<Line>)` to specify whether we want to take the maximum extension or whether we want to stop at the first intersection found.
- Adds `Line.ExtendTo(Polygon)` to disambiguate in that situation.
- Adds Grid2d constructors for origin and direction, and from existing UV Grid1d that has been pre-calculated.

TESTING:
- Try creating Grid2d with origin and UV directions. It should expand to fill the boundaries given, including if the UV vectors are skewed.
  
FUTURE WORK:
- N/A

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.
- [ ] ~~The docs are up to date. To update the docs run `build_docs.sh` locally, and commit the results.~~

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Generally this looks good, although there's still a case that's not quite behaving right. Taking a child grid and "splitting at point" seems to split in the wrong location. Try this for a test:
```
var origin = new Vector3();
var uDirection = new Vector3(1, 0, 0);
var vDirection = new Vector3(-1, 1, 0); // 45 degrees up to the left

var grid = new Grid2d(rect, origin, uDirection, vDirection);

grid.SplitAtPoint(new Vector3(-3, -3));
grid.SplitAtPoint(new Vector3(4, 2));
grid[1,1].SplitAtPoint(new Vector3(0,0));
```
It looks to me like the child cell isn't getting split in the right place. 

> Reviewed 1 of 2 files at r1, 33 of 39 files at r2, 1 of 34 files at r3, 5 of 29 files at r4, 1 of 1 files at r5, 1 of 27 files at r7, 24 of 24 files at r8.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503#-:-MTk46wL8AzBYR7NwEXD:b-v2q2co)* status: 31 of 34 files reviewed, 2 unresolved discussions (waiting on @serenayl)

___
*[Elements/src/Geometry/Line.cs, line 519 at r8](https://reviewable.io/reviews/hypar-io/elements/503#-MTjtaq02VdZFG3E_8Vg:-MTjtaq02VdZFG3E_8Vh:b-e2zxij) ([raw file](https://github.com/hypar-io/elements/blob/51b8881e618675ecdb1eb8871ebdc5d3865fa683/Elements/src/Geometry/Line.cs#L519)):*
> ```Smalltalk
>             var startEndCandidates = extendToFurthest ? (startCandidates.LastOrDefault(), endCandidates.LastOrDefault() ) : ( startCandidates.FirstOrDefault(), endCandidates.FirstOrDefault() );
> 
>             if (bothSides && startEndCandidates.Item1 != null)
> ```

I find .Item1 .Item2 makes less readable code — Can we give these tuples names? I **think** it's as simple as changing the type signature of `startEndCandidates` from var to (Vector3 start, Vector3 end). That might also save you the Vector3 casts? 

I'd also use `First()` or `Last()` here instead of `FirstOrDefault()` because `default(Vector3)` is just the origin, which is not a desirable result here. (Noting fully that the previous code, which I wrote, made this same mistake)
___
*[Elements/test/Grid2dTests.cs, line 341 at r8](https://reviewable.io/reviews/hypar-io/elements/503#-MTjw4SKC-QWb-2LMRZ0:-MTjw4SLDE6f7_ZLoMI1:b7jgx5z) ([raw file](https://github.com/hypar-io/elements/blob/51b8881e618675ecdb1eb8871ebdc5d3865fa683/Elements/test/Grid2dTests.cs#L341)):*
> ```Smalltalk
>             var squareSize = 10;
>             var squareHalfSize = squareSize/2;
>             var rect = Polygon.Rectangle(new Vector3(-squareHalfSize, -squareHalfSize), new Vector3(squareHalfSize, squareHalfSize));
> ```

I think this is equivalent to `Polygon.Rectangle(squareSize, squareSize)`

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 2 of 27 files at r7.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: 33 of 34 files reviewed, 2 unresolved discussions (waiting on @serenayl)

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: all files reviewed, 2 unresolved discussions (waiting on @serenayl)

**Review by andrewheumann — COMMENTED** [review]
Did another follow up check — it appears split at point on a subcell didn't work particularly well before your changes, either. So I don't want to make approving this contingent on your fixing this. Am going to spend another 10 min investigating to see if I can fix the underlying cause.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503#-:-MTkA5t5CeJY574uS97_:b-qmk9op)* status: all files reviewed, 2 unresolved discussions (waiting on @serenayl)

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 24 files at r9.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: all files reviewed, 2 unresolved discussions (waiting on @serenayl)

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 2 of 39 files at r2, 4 of 28 files at r10, 2 of 3 files at r12, 24 of 24 files at r13.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: 34 of 35 files reviewed, 2 unresolved discussions (waiting on @andrewheumann and @serenayl)

**Review by serenayl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: 32 of 35 files reviewed, 2 unresolved discussions (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Line.cs, line 519 at r8](https://reviewable.io/reviews/hypar-io/elements/503#-MTjtaq02VdZFG3E_8Vg:-MTpk1YS4OzeFbQz8MAh:b-74309m) ([raw file](https://github.com/hypar-io/elements/blob/51b8881e618675ecdb1eb8871ebdc5d3865fa683/Elements/src/Geometry/Line.cs#L519)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I find .Item1 .Item2 makes less readable code — Can we give these tuples names? I **think** it's as simple as changing the type signature of `startEndCandidates` from var to (Vector3 start, Vector3 end). That might also save you the Vector3 casts? 

I'd also use `First()` or `Last()` here instead of `FirstOrDefault()` because `default(Vector3)` is just the origin, which is not a desirable result here. (Noting fully that the previous code, which I wrote, made this same mistake)
</blockquote></details>

COOL TIP! I was like, "well, this is a pretty annoying implicit thing in tuples" lol. Fixed. I had to do a bunch of Count checking and ternary in order to defend against `First()` or `Last()` throwing exceptions: is that expected?
___
*[Elements/test/Grid2dTests.cs, line 341 at r8](https://reviewable.io/reviews/hypar-io/elements/503#-MTjw4SKC-QWb-2LMRZ0:-MTq6Eh121huM0ghKvA6:bi71lwn) ([raw file](https://github.com/hypar-io/elements/blob/51b8881e618675ecdb1eb8871ebdc5d3865fa683/Elements/test/Grid2dTests.cs#L341)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I think this is equivalent to `Polygon.Rectangle(squareSize, squareSize)`
</blockquote></details>

Good call! I so rarely need square centered at the origin that I forgot this existed. Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 3 files at r12, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: all files reviewed, 1 unresolved discussion (waiting on @serenayl)

___
*[Elements/src/Geometry/Line.cs, line 519 at r8](https://reviewable.io/reviews/hypar-io/elements/503#-MTjtaq02VdZFG3E_8Vg:-MTqWpJY5DkuluW5N9P8:b-g4v9cq) ([raw file](https://github.com/hypar-io/elements/blob/51b8881e618675ecdb1eb8871ebdc5d3865fa683/Elements/src/Geometry/Line.cs#L519)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

COOL TIP! I was like, "well, this is a pretty annoying implicit thing in tuples" lol. Fixed. I had to do a bunch of Count checking and ternary in order to defend against `First()` or `Last()` throwing exceptions: is that expected?
</blockquote></details>

Ah, yes, this is actually much better — because now we will actually get nulls for an empty list. before this would have just thrown in the Origin and been happy, which is not the correct result.

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: all files reviewed, 1 unresolved discussion (waiting on @serenayl)

___
*[Elements/src/Geometry/Line.cs, line 519 at r8](https://reviewable.io/reviews/hypar-io/elements/503#-MTjtaq02VdZFG3E_8Vg:-MTqXAsG5v6L7DbDYB4K:b-bgevbe) ([raw file](https://github.com/hypar-io/elements/blob/51b8881e618675ecdb1eb8871ebdc5d3865fa683/Elements/src/Geometry/Line.cs#L519)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Ah, yes, this is actually much better — because now we will actually get nulls for an empty list. before this would have just thrown in the Origin and been happy, which is not the correct result. 
</blockquote></details>

ah shit, you know what, I'm wrong — 
I didn't realize that endCandidates was of type <Vector3?> rather than <Vector3>. So in fact FirstOrDefault() would have been perfectly appropriate here. My bad, sorry for sending you down the wrong path.

**Review by serenayl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Line.cs, line 519 at r8](https://reviewable.io/reviews/hypar-io/elements/503#-MTjtaq02VdZFG3E_8Vg:-MTq_RyuCOk-dI7zHF8N:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/51b8881e618675ecdb1eb8871ebdc5d3865fa683/Elements/src/Geometry/Line.cs#L519)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

ah shit, you know what, I'm wrong — 
I didn't realize that endCandidates was of type <Vector3?> rather than <Vector3>. So in fact FirstOrDefault() would have been perfectly appropriate here. My bad, sorry for sending you down the wrong path. 
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Line.cs, line 519 at r8](https://reviewable.io/reviews/hypar-io/elements/503#-MTjtaq02VdZFG3E_8Vg:-MTqY-5x2nPArVASHCYZ:blin0za) ([raw file](https://github.com/hypar-io/elements/blob/51b8881e618675ecdb1eb8871ebdc5d3865fa683/Elements/src/Geometry/Line.cs#L519)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

ah shit, you know what, I'm wrong — 
I didn't realize that endCandidates was of type <Vector3?> rather than <Vector3>. So in fact FirstOrDefault() would have been perfectly appropriate here. My bad, sorry for sending you down the wrong path. 
</blockquote></details>

that should read "rather than `<Vector3>`

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 27 files at r15.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/503)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @andrewheumann)

**Pull request merged**
