### PR TITLE
enforce warnings as errors to improve code quality.

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- Some xml comments were created that were not actually valid, and while warnings did appear, there was no enforcement.  We have many warnings from documentation missing and beta/alpha packages, which make warnings not seem important

DESCRIPTION:
- add TreatWarningsAsErrors flag.
- explicitly allow preview packages in Elements because there are no valid versions of these packages available.
- A collection of spelling fixes.

TESTING:
- Building will pass even with the new rule enforcement.
  
FUTURE WORK:
- Is there any future work needed or anticipated?  Does this PR create any obvious technical debt?

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/922)

### CODE REVIEW

**Review by ikeough — CHANGES_REQUESTED** [review]
> Reviewed 11 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/922)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 37 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEAF8iAxl5Hbam_I-U:-NIEAF8iAxl5Hbam_I-V:b-sdslzu) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L37)):*
> ```Smalltalk
>             }
> 
>             WeightModifiers = new WeightModifier[] { };
> ```

Seems like some adaptive grid code got into this PR somehow.
___
*[`Elements/test/AdaptiveGraphRoutingTests.cs` line 1008 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEAxTFCs_Z-V22yTZp:-NIEAxTFCs_Z-V22yTZq:brevem3) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements/test/AdaptiveGraphRoutingTests.cs#L1008)):*
> ```Smalltalk
>             }, AdaptiveGrid.VerticesInsertionMethod.ConnectAndCut);
> 
>             var c = RoutingConfiguration.Default();
> ```

I'm not sure why this is in this PR, but because it is, I'll say that the _default_ constructor is the corrector way to go here. 
___
*[`Elements.Serialization.SVG/src/SvgContext.cs` line 11 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIE9pXWE5WR8sf0AUAt:-NIE9pXWE5WR8sf0AUAu:b-9dtcp8) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SvgContext.cs#L11)):*
> ```Smalltalk
>     {
>         /// <summary>
>         /// Fill color.
> ```

The fill color.
___
*[`Elements.Serialization.SVG/src/SvgContext.cs` line 16 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIE9nz9AvX94KWNAvrY:-NIE9nz9AvX94KWNAvrZ:b-l18kpt) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SvgContext.cs#L16)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Stroke color.
> ```

The stroke color.
___
*[`Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs` line 9 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIE9tTmCTkSkhxoMrwx:-NIE9tTmCTkSkhxoMrwy:b-7flocu) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs#L9)):*
> ```Smalltalk
>     {
>         /// <summary>
>         /// What should the margin of the PDF be?.
> ```

The margin. (We don't typically use question syntax for properties.)
___
*[`Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs` line 14 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEA0gOEX_cHpNxylS9:-NIEA0gOEX_cHpNxylSA:bvnt2hx) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs#L14)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// What is the width of the PDF?
> ```

The page width.
___
*[`Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs` line 19 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEA1ei-MQZTnJjsFFJ:-NIEA1ei-MQZTnJjsFFK:b-ltthdi) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs#L19)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// What is the height of the PDF?
> ```

The page height.

**Review by ikeough — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/922)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Elements.csproj` line 15 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEBwTVEXxG2Xao1y1N:-NIEBwTVEXxG2Xao1y1O:bayr544) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements/src/Elements.csproj#L15)):*
> ```XML
>         <Version>$(Version)</Version>
>         <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
>         <NoWarn>NU5104</NoWarn>
> ```

I'm guessing we need this for the glTFLoader? Anything else?

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/922)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements/src/Elements.csproj` line 15 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEBwTVEXxG2Xao1y1N:-NIENGVq3k7DYbPR3sDn:bl7zjuz) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements/src/Elements.csproj#L15)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I'm guessing we need this for the glTFLoader? Anything else?
</blockquote></details>

The SixLabors packages, some of which don't even have a listed non-pre-release version.
___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 37 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEAF8iAxl5Hbam_I-U:-NIENoDB94xV2oe7sFto:b-2i5pya) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L37)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Seems like some adaptive grid code got into this PR somehow.
</blockquote></details>

these changes are to maintain functionality while removing actual internal usage of the Obsoleted properties.
___
*[`Elements/test/AdaptiveGraphRoutingTests.cs` line 1008 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEAxTFCs_Z-V22yTZp:-NIENQQS1ONyqBbmTsqO:b-tpd7ln) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements/test/AdaptiveGraphRoutingTests.cs#L1008)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I'm not sure why this is in this PR, but because it is, I'll say that the _default_ constructor is the corrector way to go here. 
</blockquote></details>

can't use the default constructor for a struct in this case because it doesn't correctly initialize.
___
*[`Elements.Serialization.SVG/src/SvgContext.cs` line 11 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIE9pXWE5WR8sf0AUAt:-NIENdBQBk3MxMmxxBDG:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SvgContext.cs#L11)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

The fill color.
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgContext.cs` line 16 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIE9nz9AvX94KWNAvrY:-NIENd-HAuBTaTw3Rf7b:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SvgContext.cs#L16)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

The stroke color.
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs` line 9 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIE9tTmCTkSkhxoMrwx:-NIEOTmL-eQ6WACxCwmI:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs#L9)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

The margin. (We don't typically use question syntax for properties.)
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs` line 14 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEA0gOEX_cHpNxylS9:-NIEOU5r0zlcywT58v6R:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs#L14)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

The page width.
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs` line 19 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEA1ei-MQZTnJjsFFJ:-NIEOUnAC9Tk10wQJAt4:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements.Serialization.SVG/src/SaveOptions/PdfSaveOptions.cs#L19)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

The page height.
</blockquote></details>

Done.

**Review by ikeough — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/922)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/test/AdaptiveGraphRoutingTests.cs` line 1008 at r3](https://reviewable.io/reviews/hypar-io/elements/922#-NIEAxTFCs_Z-V22yTZp:-NIGT7Rx31Fgi_bKKRpY:bmxor92) ([raw file](https://github.com/hypar-io/elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements/test/AdaptiveGraphRoutingTests.cs#L1008)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can't use the default constructor for a struct in this case because it doesn't correctly initialize.
</blockquote></details>

Can you use `var c = default`?

**Review by DmytroMuravskyi — COMMENTED** [review]
> Reviewed 14 of 25 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/922)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @wynged)

___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs` line 53 at r4](https://reviewable.io/reviews/hypar-io/elements/922#-NIH8o3-DPquD4p9LYub:-NIH8o3-DPquD4p9LYuc:b-yp3qpx) ([raw file](https://github.com/hypar-io/elements/blob/4226678a30b16b2b6f51d6437f851433c1a1bbdb/Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs#L53)):*
> ```Smalltalk
>         /// </summary>
>         [Obsolete("Use HasFlag(EdgeFlags.HasVerticalChange) instead")]
>         public bool HasVerticalChange { get => false; }
> ```

Setting it always  to false is worse than removing it for good. Obsolete item should still provide the same behavior as before until user it transitioned.  Let's just do HasAnyFlag(EdgeFlags.HasVerticalChange) as get.
___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 27 at r4](https://reviewable.io/reviews/hypar-io/elements/922#-NIHBcwpDMJWSQNmVKo-:-NIHBcwpDMJWSQNmVKo0:b-u1ou8a) ([raw file](https://github.com/hypar-io/elements/blob/4226678a30b16b2b6f51d6437f851433c1a1bbdb/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L27)):*
> ```Smalltalk
> #pragma warning disable 612, 618
>             // TODO - remove this warning suppression when the obsolete members are removed.
>             MainLayer = 0;
> ```

Brakes behavior.  It should be either removed or set. 
___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 37 at r4](https://reviewable.io/reviews/hypar-io/elements/922#-NIHBaDH2Zba5n9Ln_Nz:-NIHBaDH2Zba5n9Ln_O-:b-jw6geq) ([raw file](https://github.com/hypar-io/elements/blob/4226678a30b16b2b6f51d6437f851433c1a1bbdb/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L37)):*
> ```Smalltalk
>             }
> 
>             WeightModifiers = new WeightModifier[] { };
> ```

I think it should be located in routing file with warnings suppressed.  See commend below.
___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 71 at r4](https://reviewable.io/reviews/hypar-io/elements/922#-NIHA-_CD9V0WuiKR1h0:-NIHA-_CD9V0WuiKR1h1:b-9vwvso) ([raw file](https://github.com/hypar-io/elements/blob/4226678a30b16b2b6f51d6437f851433c1a1bbdb/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L71)):*
> ```Smalltalk
>         /// Weight modifiers that should be used during this routing.
>         /// </summary>
>         public WeightModifier[] WeightModifiers;
> ```

I don't think we should introduce whole new public property just to cover Obsolete items.

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/922)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi and @ikeough)

___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs` line 53 at r4](https://reviewable.io/reviews/hypar-io/Elements/922#-NIH8o3-DPquD4p9LYub:-NSR84RJBfIKXcDWS1w7:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/4226678a30b16b2b6f51d6437f851433c1a1bbdb/Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs#L53)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

Setting it always  to false is worse than removing it for good. Obsolete item should still provide the same behavior as before until user it transitioned.  Let's just do HasAnyFlag(EdgeFlags.HasVerticalChange) as get.
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 27 at r4](https://reviewable.io/reviews/hypar-io/Elements/922#-NIHBcwpDMJWSQNmVKo-:-NSR86bc8iwQ_YDoY_gX:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/4226678a30b16b2b6f51d6437f851433c1a1bbdb/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L27)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

Brakes behavior.  It should be either removed or set. 
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 37 at r4](https://reviewable.io/reviews/hypar-io/Elements/922#-NIHBaDH2Zba5n9Ln_Nz:-NSR89CB4Sb6FsHj8ST_:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/4226678a30b16b2b6f51d6437f851433c1a1bbdb/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L37)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

I think it should be located in routing file with warnings suppressed.  See commend below.
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 71 at r4](https://reviewable.io/reviews/hypar-io/Elements/922#-NIHA-_CD9V0WuiKR1h0:-NSR5grSEvpdBxryT9Me:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/4226678a30b16b2b6f51d6437f851433c1a1bbdb/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L71)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

I don't think we should introduce whole new public property just to cover Obsolete items.
</blockquote></details>

Done.

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/922)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi and @ikeough)

___
*[`Elements/test/AdaptiveGraphRoutingTests.cs` line 1008 at r3](https://reviewable.io/reviews/hypar-io/Elements/922#-NIEAxTFCs_Z-V22yTZp:-NSRC5KU7eKtYrG0C_2-:b-fv9lf8) ([raw file](https://github.com/hypar-io/Elements/blob/58f940fb2b847da207d5342ebbcdfa719b357b4c/Elements/test/AdaptiveGraphRoutingTests.cs#L1008)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Can you use `var c = default`?
</blockquote></details>

done, I've reverted the change that required this.

**Review by DmytroMuravskyi — COMMENTED** [review]
> Reviewed 5 of 11 files at r5, 6 of 7 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/922)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @wynged)

___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 4 at r7](https://reviewable.io/reviews/hypar-io/elements/922#-NSeBt6ODJB1adSlIJnP:-NSeBt6ODJB1adSlIJnQ:bjqxe2u) ([raw file](https://github.com/hypar-io/elements/blob/36ad6c0ce75625dbbcf0619e40b19987e32c8edc/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L4)):*
> ```Smalltalk
> using System.Collections.Generic;
> using System.Text;
> using Elements.Geometry;
> ```

This using is not necessary anymore

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/922)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi and @ikeough)

___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs` line 4 at r7](https://reviewable.io/reviews/hypar-io/Elements/922#-NSeBt6ODJB1adSlIJnP:-NSfeasm384MlvMtJnT0:b-ku2681) ([raw file](https://github.com/hypar-io/Elements/blob/36ad6c0ce75625dbbcf0619e40b19987e32c8edc/Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs#L4)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

This using is not necessary anymore
</blockquote></details>

Done.  good catch

**Review by ikeough — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/922)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @DmytroMuravskyi)

**Pull request merged**
