### PR TITLE
Updates to AdaptiveGrid / AdaptiveGridRouting

### PR DESCRIPTION
**Pull request by DmytroMuravskyi**
BACKGROUND:
- Adaptive grid required robust ways of creating and modifying graphs. 

DESCRIPTION:
- `Line.Intersects` for `BBox3` now has `tolerance` parameter.
- Added Obstacle object that can be created from different inputs and supports custom transformation, offset and perimeter option. SubtractBox is changed into SubtractObstacle.
- All functions that produce edges have cut parameter that allows to decide if new edges should be intersected with the rest of the graph.
- Added two convenience AddEdge functions: for a pair of Vertex objects and a pair of  Vector3.
- Added Boundaries property. When it's present obstacle perimeter edges are not created outside of boundary.
- New AddVertex uses IAddVertexStrategy - flexible way to define any custom behavior to add new vertices.
- AddVertexStrip is transformed into AddVertices that allows to use a range of methods to insert a list of vertices.

TESTING:
- `BoundingBoxOffset` test is added under BBoxTests.
- New tests are added to AdaptiveGridTests and AdaptiveGridRoutingTests.
  
FUTURE WORK:
- AdaptiveGrid and AdaptiveGridRouting are still under active development.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Several functions were modified, so consumers need to update their code. Do we need to create "Obsolete" versions of no longer available functions? This would need "AddEdge" functions to not have "cut" as default "true" anymore.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/839)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/839)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 568 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85d01x8ikbYxl6eAYB:-N85d01x8ikbYxl6eAYC:b-2f2zox) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L568)):*
> ```Smalltalk
>             //TO DO: this section can be moved into `RouteAndAddTailVertices` function 
>             var droppipePath = new List<ulong>() { trunkPathVertices.Last() };
>             ulong? tailStartDirection = null;
> ```

I don't understand this variable name.  Is it a direction?  or the first node in the trunk path?
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 286 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85eQJ16YcPJxbMUW8Q:-N85eQJ22qlZaBUq8_JX:be7vk70) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L286)):*
> ```Smalltalk
>                     }
> 
>                     Action<Vector3, Vector3> formPerimeter = (start, end) =>
> ```

does this need to be an action or could we make it a method that returns the vertices we want to add as a strip?  looks like it just takes in the start, end and then needs the intersections list?  I might be wrong.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 430 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85f3Ye4bMcbhnX2Cp7:-N85f3Ye4bMcbhnX2Cp8:by30kwq) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L430)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Execution method for AddVertices function.
> ```

phrasing   "Execution style" rather than method
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 431 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fADMASwag6Ga729N:-N85fADMASwag6Ga729O:b-72njuj) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L431)):*
> ```Smalltalk
>         /// <summary>
>         /// Execution method for AddVertices function.
>         /// Each next perform more than previous one.
> ```

phrasing "Each option performs more operations than the previous one"
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 437 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fHr7AXEPOCfUEtMY:-N85fHr7AXEPOCfUEtMZ:bq98zsg) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L437)):*
> ```Smalltalk
>             /// <summary>
>             /// Just put vertices into the grid without connecting them.
>             /// Inserted vertices returned in order.
> ```

"Inserted vertices _are_ returned in order"
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 442 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fRJw1fc3nkd8NN1S:-N85fRJw1fc3nkd8NN1T:b-w1kgss) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L442)):*
> ```Smalltalk
> 
>             /// <summary>
>             /// Insert vertices and connect them directly.
> ```

"... and connect them to each other."
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 443 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fOANEV3P_k7YHNYf:-N85fOANEV3P_k7YHNYg:b-371oje) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L443)):*
> ```Smalltalk
>             /// <summary>
>             /// Insert vertices and connect them directly.
>             /// Inserted vertices returned in order.
> ```

add "are" like above.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 448 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fbw70gw4XFTalA8l:-N85fbw70gw4XFTalA8m:bhaortu) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L448)):*
> ```Smalltalk
> 
>             /// <summary>
>             /// Insert vertices and connect them directly.
> ```

"... and connect them to each other"
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 456 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85g0ZwALrOzYR47uMl:-N85g0ZwALrOzYR47uMm:b-mhlvp4) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L456)):*
> ```Smalltalk
> 
>             /// <summary>
>             /// Insect vertices and connect them.
> ```

spelling "Insert"
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 655 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N866GYB6h2oEcm4qIJG:-N866GYB6h2oEcm4qIJH:b-a9k8d5) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L655)):*
> ```Smalltalk
>         public List<Edge> AddEdge(Vertex a, Vertex b, bool cut = true)
>         {
>             return AddEdge(a.Id, b.Id, cut);
> ```

what happens if one of the ids doesn't exist, like the vertex is from a different grid by accident? I think we should add the edge+vertex anyways if a vertex knows it's position.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 789 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N86747w5wohvaUTa-VV:-N86747w5wohvaUTa-VW:b-fkn843) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L789)):*
> ```Smalltalk
>                 if ((startId == edgeV0.Id && endId == edgeV1.Id) ||
>                     (startId == edgeV1.Id && endId == edgeV0.Id))
>                 {
> ```

I think this would look simpler if we 
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 808 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N867KvG-vE8H6ZSqveJ:-N867KvG-vE8H6ZSqveK:bpbbvq5) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L808)):*
> ```Smalltalk
>                 else if (oldEdgeLine.Direction().IsParallelTo(newEdgeLine.Direction()))
>                 {
>                     var isNewEdgeStartOnOldEdge = oldEdgeLine.PointOnLine(newEdgeLine.Start);
> ```

anyway we can wrap some of this in separate methods?  or maybe the whole if/else track?  it's a pretty big method.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 893 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N867T3J-rlkBDyOtKEt:-N867T3J-rlkBDyOtKEu:b-7o1vc8) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L893)):*
> ```Smalltalk
>                 }
>             }
>             if (intersectionPoints.Any())
> ```

this part is another good candidate for creating a separate method.  the previous results created intersection points, now we're building all the edges to be added.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 958 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N867kC5DKnkg8zG2nfD:-N867kC5DKnkg8zG2nfE:b-ihvyyk) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L958)):*
> ```Smalltalk
>                         }
>                     }
>                 }
> ```

can the steps above that create hits be factored out into a separate method?
___
*[`Elements/src/Spatial/AdaptiveGrid/IAddVertexStrategy.cs` line 22 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N868CiO2yR8cQUo6RTg:-N868CiO2yR8cQUo6RTh:bwgwxsm) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/IAddVertexStrategy.cs#L22)):*
> ```Smalltalk
>         /// <returns></returns>
>         Vertex Add(AdaptiveGrid grid, Vector3 position, bool cut);
>     }
> ```

A strategy I know I want is ConnectToClosestEdge, we don't have to implement it now, but is there any reason it would be impossible given the current interface signature?
___
*[`Elements/src/Spatial/AdaptiveGrid/Obstacle.cs` line 113 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N868bo78LTTVNr5zeg0:-N868bo78LTTVNr5zeg1:b-wbik1m) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/Obstacle.cs#L113)):*
> ```Smalltalk
>         /// </summary>
>         /// <param name="points"></param>
>         /// <param name="offset"></param>
> ```

define what these arguments are, Offset and perimeter are a little vague.  Maybe "ShouldBuildPerimeter" and "AdditionalPerimeterOffset", or atleast give descriptions.
___
*[`Elements/test/AdaptiveGridTests.cs` line 104 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N8695ZrDRoEybn8gykI:-N8695ZrDRoEybn8gykJ:bfv8p20) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/test/AdaptiveGridTests.cs#L104)):*
> ```Smalltalk
>             var edgesBefore = oldV.Edges.Count;
> 
>             var newV = adaptiveGrid.AddVertex(new Vector3(-2, -4, 2), new Connect(oldV));
> ```

This makes me realize that just calling it Connect is confusing.   Something like "ConnectVertexStrategy" I think. or Strategy_Connect
___
*[`Elements/test/AdaptiveGridTests.cs` line 221 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N869KgY88FZcK9edTDC:-N869KgY88FZcK9edTDD:b3isk75) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/test/AdaptiveGridTests.cs#L221)):*
> ```Smalltalk
>             foreach (var obstacle in obstacles)
>             {
>                 adaptiveGrid.SubtractObstacle(obstacle);
> ```

can we make a helper method `SubtractObstacles` on grid that does this iteration for the user?

**Review by DmytroMuravskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/839)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 568 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85d01x8ikbYxl6eAYB:-N8NLS29CIl2Fx7kKRDo:bl6gh2g) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L568)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I don't understand this variable name.  Is it a direction?  or the first node in the trunk path?
</blockquote></details>

This is a direction between previous tail segment  and current tail segment. Has no effect if tail consist of only 2 points.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 286 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85eQJ16YcPJxbMUW8Q:-N8NPhAh14luO8vPqHaF:bvyy54s) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L286)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

does this need to be an action or could we make it a method that returns the vertices we want to add as a strip?  looks like it just takes in the start, end and then needs the intersections list?  I might be wrong.
</blockquote></details>

We could split it. I did not like it because  perimeter is not just edges around but also cut versions of any edges that crosses obstacle. Each point has additional information about what edge it belongs to and which side of the edge should be preserved in the new edge.
Partially cutting edges and returning vertices are messy. At the end I decided to do everything in place. 
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 430 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85f3Ye4bMcbhnX2Cp7:-N8NMAZ-27Bm-ufWfJBe:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L430)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

phrasing   "Execution style" rather than method
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 431 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fADMASwag6Ga729N:-N8NMEZ_2WlGyQZwH3rz:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L431)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

phrasing "Each option performs more operations than the previous one"
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 437 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fHr7AXEPOCfUEtMY:-N8NMU7UCwJEJS0RENK7:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L437)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

"Inserted vertices _are_ returned in order"
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 442 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fRJw1fc3nkd8NN1S:-N8NMgT44Ku3lt3d5DqI:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L442)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

"... and connect them to each other."
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 443 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fOANEV3P_k7YHNYf:-N8NMh6C-DdqDdVgS8ou:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L443)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

add "are" like above.
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 448 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85fbw70gw4XFTalA8l:-N8NMi3JD3SsCuBZrtKS:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L448)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

"... and connect them to each other"
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 456 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N85g0ZwALrOzYR47uMl:-N8NMld_0nUaGoLBSrmk:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L456)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

spelling "Insert"
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 655 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N866GYB6h2oEcm4qIJG:-N8YuH5vBy-qFlnZ904P:b-j1a8h2) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L655)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

what happens if one of the ids doesn't exist, like the vertex is from a different grid by accident? I think we should add the edge+vertex anyways if a vertex knows it's position.
</blockquote></details>

I don't think we should do any position check since I don't see "other grid case" as something that can often happen, so we want to check all the time. I've added id exceptions to AddCutEdge and AddInsertEdge so at least wrong Ids or vertices with non existing Ids can't be passed.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 789 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N86747w5wohvaUTa-VV:-N8NRPEqDdDIBQL0Gcgw:b-w11qz6) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L789)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think this would look simpler if we 
</blockquote></details>

end of sentence is missing



_Code quote:_
```Smalltalk
AddEdge
```
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 808 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N867KvG-vE8H6ZSqveJ:-N8YuE69BirZquC_7LHb:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L808)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

anyway we can wrap some of this in separate methods?  or maybe the whole if/else track?  it's a pretty big method.
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 893 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N867T3J-rlkBDyOtKEt:-N8YlkDC-GDU2SgU-iGU:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L893)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

this part is another good candidate for creating a separate method.  the previous results created intersection points, now we're building all the edges to be added.
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 958 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N867kC5DKnkg8zG2nfD:-N8YlZVn33yUqqHaXxAx:bx9t2ev) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L958)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can the steps above that create hits be factored out into a separate method?
</blockquote></details>

I've separated several smaller function out of bigger ones, it made code much more simplier.



_Code quote:_
```Smalltalk
  hits = hits.OrderBy(h => h.D1).ToList();
```
___
*[`Elements/src/Spatial/AdaptiveGrid/IAddVertexStrategy.cs` line 22 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N868CiO2yR8cQUo6RTg:-N8NOmQfCyfNsOO45nly:b-tmffk3) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/IAddVertexStrategy.cs#L22)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

A strategy I know I want is ConnectToClosestEdge, we don't have to implement it now, but is there any reason it would be impossible given the current interface signature?
</blockquote></details>

No, it's possible to do. 
One note. Strategy is limited to public interface of AdaptiveGrid. I though about giving access to private members but have no way to do so. 
Static extension functions could be used instead of Strategy classes as well.
___
*[`Elements/src/Spatial/AdaptiveGrid/Obstacle.cs` line 113 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N868bo78LTTVNr5zeg0:-N8NSnI25NQJe9xDzzhB:b-p566g8) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/src/Spatial/AdaptiveGrid/Obstacle.cs#L113)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

define what these arguments are, Offset and perimeter are a little vague.  Maybe "ShouldBuildPerimeter" and "AdditionalPerimeterOffset", or atleast give descriptions.
</blockquote></details>

Whole file is missing documentation, adding it. Don't want to overcomplicate names, hope that comments will do enough.
___
*[`Elements/test/AdaptiveGridTests.cs` line 104 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N8695ZrDRoEybn8gykI:-N8O7_wrEXkD0r2lHncd:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/test/AdaptiveGridTests.cs#L104)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

This makes me realize that just calling it Connect is confusing.   Something like "ConnectVertexStrategy" I think. or Strategy_Connect
</blockquote></details>

Done.
___
*[`Elements/test/AdaptiveGridTests.cs` line 221 at r1](https://reviewable.io/reviews/hypar-io/elements/839#-N869KgY88FZcK9edTDC:-N8NSAW64uQ37uh6W2d8:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9967971c8aacda79b6b14662e173b15c8c4a7bda/Elements/test/AdaptiveGridTests.cs#L221)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can we make a helper method `SubtractObstacles` on grid that does this iteration for the user?
</blockquote></details>

Done.



_Code quote:_
```Smalltalk
SubtractObstacle
```

**Review by DmytroMuravskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/839)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 1257 at r2](https://reviewable.io/reviews/hypar-io/elements/839#-N8ZG_GvEjpL0QD91gmV:-N8ZN9Si3Kx6pB159LOx:bfgtx3x) ([raw file](https://github.com/hypar-io/elements/blob/71c50a8e24b0b75ff64776fff0413a252d8d676a/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L1257)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

oh, I see, this is for bounding box checks.  Maybe "EdgeOrientationToBox" or actually pass a BBox3 in rather than min/max points?
</blockquote></details>

Grouped the parameters and added some comments, hope it cleaner now. Can change into usage of BBox3 for points tomorrow, if you'd like



_Code quote:_
```Smalltalk
EdgeOrientation
```

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/839)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 1257 at r2](https://reviewable.io/reviews/hypar-io/elements/839#-N8ZG_GvEjpL0QD91gmV:-N8ZRBbJEtQ0JNd5cnn3:bi9hbwb) ([raw file](https://github.com/hypar-io/elements/blob/71c50a8e24b0b75ff64776fff0413a252d8d676a/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L1257)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

Grouped the parameters and added some comments, hope it cleaner now. Can change into usage of BBox3 for points tomorrow, if you'd like
</blockquote></details>

nah, I dig it.  we could always add BBox3 as a convenience method that wraps this, but let's just do that when it's helpful.

**Pull request merged**
