### PR TITLE
Add badges for the actions.

### PR DESCRIPTION
**Pull request by ikeough**
This PR adds badges for the tag and build, and build and test actions on the front page. It also removes the Travis badge.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/439)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/439)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ikeough and @wynged)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/hypar-io/elements/439#-MLIfAOt4VfeOIe-kv6R:-MLIfAOt4VfeOIe-kv6S:b-vjnzfz) ([raw file](https://github.com/hypar-io/elements/blob/3f6142556a4c2f1d59798788f92b26d149340cda/README.md#L3)):*
> ```Markdown
> # Elements
> 
> Tag and Publish Alpha
> ```

Do these svg files exist?  I don't see them being added as part of this PR

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/439)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @wynged)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/hypar-io/elements/439#-MLIfAOt4VfeOIe-kv6R:-MLJ_Cej9VYxNAaSuzLW:b-3q97vl) ([raw file](https://github.com/hypar-io/elements/blob/3f6142556a4c2f1d59798788f92b26d149340cda/README.md#L3)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

Do these svg files exist?  I don't see them being added as part of this PR
</blockquote></details>

I believe they are created by github's API because they change based on the status of the action.

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/439)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/hypar-io/elements/439#-MLIfAOt4VfeOIe-kv6R:-MLONv3e9qYWnJ-r97Lf:b-lro3yt) ([raw file](https://github.com/hypar-io/elements/blob/3f6142556a4c2f1d59798788f92b26d149340cda/README.md#L3)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I believe they are created by github's API because they change based on the status of the action.
</blockquote></details>

ok.  interesting

**Review by wynged — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/439#-:-MLTj_Jn6M5Ikwc8CIg1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
