### PR TITLE
AdaptiveGrid for routing algorithms

### PR DESCRIPTION
**Pull request by DmytroMuravskyi**
BACKGROUND:
- This is continuation of draft #618 .
The team needed lightweight version of cell complex suitable of representing a graph.

DESCRIPTION:
- This PR adds AdaptiveGrid class that allow creating Vertex / Edge structure, suitable for routing algorithms. The grid can be created from BBox3, Polygon or extrusion of polygon. Grid has it's own forked version of Vertex and Edge. Grid supports cutting portions out using BBox3.
- Added Line.Intersects what works with BBox3 to support this.
- Added Vector3.AreCoplanar that takes 4 points directly.

TESTING:
- Added new test file AdaptiveGridTests
- Added test AreCoplanar_FourPoints to VectorTests
- Added test IntersectsBox to LineTests
  
FUTURE WORK:
- AdaptiveGrid may need further polishing when requirements are settled. Some parts may need performance optimization. Some may be removed if no longer needed. New may be added as well.
- Vector and Edge classes overlap with the same classes from CellComplex as well. If direct dependency on CellComplex is removed in the future, these classes may be merged together into simple abstraction.

REQUIRED:
- [x ] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
#618 need to be closed

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/651)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/651)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 99 at r4](https://reviewable.io/reviews/hypar-io/elements/651#-Mh_VXtYBIecJ4OiI4Y3:-Mh_VXtYBIecJ4OiI4Y4:bypqj12) ([raw file](https://github.com/hypar-io/elements/blob/a841a68216b40feeab83426a7835d605d21476fe/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L99)):*
> ```Smalltalk
>         /// <param name="bBox">Box which region is populated with graph.</param>
>         /// <param name="stepSize">Step, graph is populated with.</param>
>         public void AddFromBbox(BBox3 bBox, double stepSize)
> ```

If we don't use the stepsize method, let's just get rid of it.
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 142 at r4](https://reviewable.io/reviews/hypar-io/elements/651#-Mh_WlBt2jkuL-Ti0Ras:-Mh_WlBt2jkuL-Ti0Rat:brbc6ao) ([raw file](https://github.com/hypar-io/elements/blob/a841a68216b40feeab83426a7835d605d21476fe/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L142)):*
> ```Smalltalk
>         /// <param name="height">Height of polygon extrusion</param>
>         /// <param name="stepSize">Step with which region is divided in each direction</param>
>         public void AddFromExtrude(Polygon boundingPolygon, Vector3 extrusionAxis, double height, double stepSize)
> ```

height => distance
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 185 at r4](https://reviewable.io/reviews/hypar-io/elements/651#-MhZzcdLACm4WFEUrWhx:-MhZzcdLACm4WFEUrWhy:bz17js1) ([raw file](https://github.com/hypar-io/elements/blob/a841a68216b40feeab83426a7835d605d21476fe/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L185)):*
> ```Smalltalk
>         /// <param name="height">Height of polygon extrusion</param>
>         /// <param name="keyPoints">Set of 3D points, region is split with.</param>
>         public void AddFromExtrude(Polygon boundingPolygon, Vector3 extrusionAxis, double height, List<Vector3> keyPoints)
> ```

see note in Hypar.MEP about preserving keyPoints that are added, and maybe giving keyPoints some notion of what kind of point they are.  "Leaf"
  "FinalPoint"  "TrunkPath" etc....
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 223 at r4](https://reviewable.io/reviews/hypar-io/elements/651#-Mh_-0UE1Sph7VJNwadV:-Mh_-0UE1Sph7VJNwadW:b6asmk5) ([raw file](https://github.com/hypar-io/elements/blob/a841a68216b40feeab83426a7835d605d21476fe/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L223)):*
> ```Smalltalk
>         public HashSet<Edge> AddFromPolygon(Polygon boundingPolygon, double stepSize)
>         {
>             if (stepSize < MinimumResolution)
> ```

I think if the desired stepsize is less than minResolution ,we should probably use the minResolution
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 379 at r4](https://reviewable.io/reviews/hypar-io/elements/651#-MhV9t1V1IYGlCmD-I_y:-MhV9t1V1IYGlCmD-I_z:b-sd4vyg) ([raw file](https://github.com/hypar-io/elements/blob/a841a68216b40feeab83426a7835d605d21476fe/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L379)):*
> ```Smalltalk
>         /// <param name="fuzzyFactor">Amount of tolerance in the search against each component of the coordinate.</param>
>         /// <returns></returns>
>         public bool VertexExists(Vector3 point, out ulong id, double? fuzzyFactor = null)
> ```

rename to "TryGetVertex"
also, can we rename fuzzyFactor to `tolerance` everywhere, that's what we use in other places in Elements.

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/651)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 379 at r4](https://reviewable.io/reviews/hypar-io/elements/651#-MhV9t1V1IYGlCmD-I_y:-MiM0AkF3XjCkwa268q2:bnneka6) ([raw file](https://github.com/hypar-io/elements/blob/a841a68216b40feeab83426a7835d605d21476fe/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L379)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

rename to "TryGetVertex"
also, can we rename fuzzyFactor to `tolerance` everywhere, that's what we use in other places in Elements.

</blockquote></details>

still looking for the rename to "TryGetVertexIndex"

**Review by DmytroMuravskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/651)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 185 at r4](https://reviewable.io/reviews/hypar-io/elements/651#-MhZzcdLACm4WFEUrWhx:-MiM3NIkAn2tdGH4XWS5:b-4udwqu) ([raw file](https://github.com/hypar-io/elements/blob/a841a68216b40feeab83426a7835d605d21476fe/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L185)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

see note in Hypar.MEP about preserving keyPoints that are added, and maybe giving keyPoints some notion of what kind of point they are.  "Leaf"
  "FinalPoint"  "TrunkPath" etc....
</blockquote></details>

Good point. Need to discuss this in the future.
 
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 379 at r4](https://reviewable.io/reviews/hypar-io/elements/651#-MhV9t1V1IYGlCmD-I_y:-MiM3Jc28_CdEcKBaQ6Y:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/a841a68216b40feeab83426a7835d605d21476fe/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L379)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

still looking for the rename to "TryGetVertexIndex"
</blockquote></details>

Done.

**Review by wynged — APPROVED** [review]
> Reviewed 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/651)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/651)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
