### PR TITLE
add missing xml summaries

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- Some classes have been made public without the corresponding doc xml tags being added

DESCRIPTION:
- Add all currently missing  xml summary tags.

TESTING:
- N/A
  
FUTURE WORK:
- ContentElements are being reviewed in separate PR and will also need documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/415)

### CODE REVIEW

**Review by ikeough — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/415)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @ikeough and @wynged)

___
*[Elements/src/Serialization/JSON/JsonInheritanceAttribute.cs, line 25 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKfseuFELuB3JZpnJ4O:-MKfseuFELuB3JZpnJ4P:bemsjbi) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements/src/Serialization/JSON/JsonInheritanceAttribute.cs#L25)):*
> ```Smalltalk
>         /// The key (discriminator) of the type that inherits from this class.
>         /// </summary>
>         /// <value></value>
> ```

Remove empty `<value>` tags everywhere.
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 18 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKftcN78y8OG3eV5-mk:-MKftcN78y8OG3eV5-ml:b-9cbkac) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L18)):*
> ```Smalltalk
>     /// We shouldn't actually need to implement these ourselves. See the TODO in the source code for more information.  
>     /// </summary>
>     public static class HyparFilters
> ```

Does this class and all of its methods need to be public? If we can hide it, we don't need to deal with all these comments.
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 23 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKft2wB46CMNCBHFo8l:-MKft2wB46CMNCBHFo8m:b-ku006u) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L23)):*
> ```Smalltalk
>         /// Return the string in lower camel case.
>         /// </summary>
>         /// <param name="context"></param>
> ```

Give parameter tags values everywhere.
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 26 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKfsuQi0TcDuHXnu5Jp:-MKfsuQi0TcDuHXnu5Jq:b-9bprpc) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L26)):*
> ```Smalltalk
>         /// <param name="input"></param>
>         /// <param name="firstCharacterMustBeAlpha"></param>
>         public static string Lowercamelcase(Context context, string input, bool firstCharacterMustBeAlpha = true)
> ```

`LowerCamelCase`
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 37 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKfswBZ5zYBWG47P2EI:-MKfswBZ5zYBWG47P2EJ:bkeu9jk) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L37)):*
> ```Smalltalk
>         /// <param name="input"></param>
>         /// <param name="firstCharacterMustBeAlpha"></param>
>         public static string Safeidentifierlower(Context context, string input, bool firstCharacterMustBeAlpha = true)
> ```

`SafeIdentifierLower`
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 49 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKft0Ci3N1KdOjS81Ka:-MKft0Ci3N1KdOjS81Kb:booo6rz) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L49)):*
> ```Smalltalk
>         /// <param name="firstCharacterMustBeAlpha"></param>
>         /// <returns></returns>
>         public static string Safeidentifierupper(Context context, string input, bool firstCharacterMustBeAlpha = true)
> ```

`SafeIdentifierUpper`
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 55 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKft8F647Z2e2C7sX_J:-MKft8F647Z2e2C7sX_K:bo1hi8t) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L55)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Convert the string into a tabbed and line broke text block.
> ```

"...tabbed text block with line breaks."
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 59 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKftEbE4m-_2T3caRIK:-MKftEbE4m-_2T3caRIL:bqnstxf) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L59)):*
> ```Smalltalk
>         /// <param name="input"></param>
>         /// <param name="tabCount"></param>
>         public static string Csharpdocs(string input, int tabCount)
> ```

`CSharpDocs`

**Comment by ikeough** [comment]
Does this fix https://github.com/hypar-io/Elements/issues/398?

**Review by wynged — COMMENTED** [review]
fix #398   Heck yea it does, thanks!

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/415#-:-MLDt50_1IVUdmlsYByD:bs2gagr)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @ikeough and @wynged)

___
*[Elements/src/Serialization/JSON/JsonInheritanceAttribute.cs, line 25 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKfseuFELuB3JZpnJ4O:-MLDtW_qCjrrwcpc5h6W:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements/src/Serialization/JSON/JsonInheritanceAttribute.cs#L25)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Remove empty `<value>` tags everywhere.
</blockquote></details>

Done.
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 18 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKftcN78y8OG3eV5-mk:-MLDtY3Z66Zwm3KidFOv:b-9xrses) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L18)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Does this class and all of its methods need to be public? If we can hide it, we don't need to deal with all these comments.
</blockquote></details>

I'm pretty sure it does, they are used here https://github.com/hypar-io/Hypar/blob/a213a7aca350336418240346c71da963648adcfd/Hypar.Functions/src/CodeGeneration/InputClass.cs#L22
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 23 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKft2wB46CMNCBHFo8l:-MLDv_YU1Bkg1f_woKSO:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L23)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Give parameter tags values everywhere.
</blockquote></details>

Done.
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 26 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKfsuQi0TcDuHXnu5Jp:-MLDuFE9-w6YuZFCuWDy:b-kxckga) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L26)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

`LowerCamelCase`
</blockquote></details>

I hesitate to change the names of these as they are copied from https://github.com/RicoSuter/NJsonSchema/blob/687efeabdc30ddacd235e85213f3594458ed48b4/src/NJsonSchema.CodeGeneration/DefaultTemplateFactory.cs#L183 and I'm not sure how the names are modified for use in the liquid templates.  In the templates they are completely lowercase.  Will the template still work if we change them to CamelCase?
___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 55 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKft8F647Z2e2C7sX_J:-MLDuiASBDpYrBiKjAZR:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L55)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

"...tabbed text block with line breaks."
</blockquote></details>

Done.

**Review by ikeough — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/415)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ikeough)

___
*[Elements.CodeGeneration/src/HyparFilters.cs, line 26 at r1](https://reviewable.io/reviews/hypar-io/elements/415#-MKfsuQi0TcDuHXnu5Jp:-MLE8x-Y0RFxJS9302Gq:b-dtm054) ([raw file](https://github.com/hypar-io/elements/blob/4cac0d22f0dd45f875f89b5263e9c99006c45ab5/Elements.CodeGeneration/src/HyparFilters.cs#L26)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I hesitate to change the names of these as they are copied from https://github.com/RicoSuter/NJsonSchema/blob/687efeabdc30ddacd235e85213f3594458ed48b4/src/NJsonSchema.CodeGeneration/DefaultTemplateFactory.cs#L183 and I'm not sure how the names are modified for use in the liquid templates.  In the templates they are completely lowercase.  Will the template still work if we change them to CamelCase?
</blockquote></details>

This is a good question. I didn't realize there was dotliquid magic happening here. I'm fine with it for now.

**Pull request merged**
