### PR TITLE
Add IsAffectedBy and IsNearby to RoutingHintLine public interface

### PR DESCRIPTION
**Pull request by DmytroMuravskyi**
BACKGROUND:
- There was a need in being able check if edges influenced by the hint line are part of the final tree.

DESCRIPTION:
- Moved IsAffectedBy and IsNearby from AdaptiveGraphRouting to RoutingHintLine. This was AdaptiveGraphRouting is simpler and RoutingHintLine has new public functions to use.

TESTING:
- Added RoutingHintLineTests with several tests.
  
REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/935)

### CODE REVIEW

**Review by wynged — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/935)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingHintLine.cs` line 94 at r1](https://reviewable.io/reviews/hypar-io/elements/935#-NKTkZUfDvtW50U6LvWU:-NKTkZUfDvtW50U6LvWV:b-iv2kdr) ([raw file](https://github.com/hypar-io/elements/blob/e06197fe1454ee92cccb0f9e9aacc459c120fa90/Elements/src/Spatial/AdaptiveGrid/RoutingHintLine.cs#L94)):*
> ```Smalltalk
>             Vector3 ve = Is2D ? new Vector3(end.X, end.Y) : end;
>             //Vertical edges are not affected by 2D hint lines
>             if (!Is2D || !vs.IsAlmostEqualTo(ve, tolerance) && Math.Abs(start.Z - end.Z) < tolerance)
> ```

am I correct that his method says if a hint line is 2D then it will always return false here?  where is it that 3D hint lines record that they affect an edge.  could we add paranthesis to be more clear about the order/effect of this line?
maybe make a small method that calcs "IsHorizontal"

**Review by DmytroMuravskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/935)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingHintLine.cs` line 94 at r1](https://reviewable.io/reviews/hypar-io/elements/935#-NKTkZUfDvtW50U6LvWU:-NKXM8J-5gF5rgykBdUI:b-d9ombq) ([raw file](https://github.com/hypar-io/elements/blob/e06197fe1454ee92cccb0f9e9aacc459c120fa90/Elements/src/Spatial/AdaptiveGrid/RoutingHintLine.cs#L94)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

am I correct that his method says if a hint line is 2D then it will always return false here?  where is it that 3D hint lines record that they affect an edge.  could we add paranthesis to be more clear about the order/effect of this line?
maybe make a small method that calcs "IsHorizontal"
</blockquote></details>

I restructured checks so it's easier to read.

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/935)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`Elements/src/Spatial/AdaptiveGrid/RoutingHintLine.cs` line 94 at r1](https://reviewable.io/reviews/hypar-io/elements/935#-NKTkZUfDvtW50U6LvWU:-NKY7XEF-wmBmr-5zwnG:bakkrnq) ([raw file](https://github.com/hypar-io/elements/blob/e06197fe1454ee92cccb0f9e9aacc459c120fa90/Elements/src/Spatial/AdaptiveGrid/RoutingHintLine.cs#L94)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

I restructured checks so it's easier to read.
</blockquote></details>

much better, thanks!

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/935)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
