### PR TITLE
Load content gltfs

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- We need the capability to load ContentElements that reference glb files

DESCRIPTION:
- Schematize BBox3
- Create ContentElement from schema, and add it to necessary places in code gen.
- Add `Scaled` method to transform to return a copy of the transformed method.  this is much easier to work with while creating a new transform for use in an element, can be inline.
- Made JsonInheritanceAttribute public.  It is added to classes during code gen, but wasn't always available, which resulted in invalid code in other functions.
- Add GltfBufferExtension for saving functionality that includes multiple buffers in separate bin files, or merging buffers into one for a single glb.
- GltfMergingUtils for adding a source glb to the current glb with its corresponding buffers, and meshes.
- lots of additional gltf properties managed as separate lists

TESTING:
- Tests created as part of this PR are functioning, and producing valid looking glbs.
- I've created a function that is intended to work with this update to Elements.
- 

  
FUTURE WORK:
- Retrieve glb files that are hosted at a remote URL.
- manage glbs that contain multiple meshes.
- Refactoring needs to happen.  Now that so many lists are being passed aroudn we should probably consolidate into a list based gltf object that is converted to the array version for serialization at the end.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)

### CODE REVIEW

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 8 of 15 files at r1, 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: 13 of 17 files reviewed, 8 unresolved discussions (waiting on @andrewheumann, @ikeough, and @wynged)

___
*[Elements/src/Generate/ContentElement.g.cs, line 54 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu6LvSDKCn790DwKmu:-MIu6LvSDKCn790DwKmv:b-wv9nxd) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Generate/ContentElement.g.cs#L54)):*
> ```Smalltalk
>         /// <summary>The bounding box of the content</summary>
>         [Newtonsoft.Json.JsonProperty("BBox", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
>         public BBox3 BBox { get; set; }
> ```

I think we should call the property itself BoundingBox — just a preference
___
*[Elements/src/Serialization/glTF/GltfBufferExtensions.cs, line 31 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu7TtQ5b92O3PCfiAb:-MIu7TtQ5b92O3PCfiAc:bt6p3ko) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfBufferExtensions.cs#L31)):*
> ```Smalltalk
> 
>                 var binSaveDir = Path.GetDirectoryName(gltfPath);
>                 var binSaveName = relativeUri;
> ```

is this var necessary? can we just call `relativeUri` `binSaveName`?
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 78 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu6w2e4lMmMbXS24zD:-MIu6w2e4lMmMbXS24zE:b-l6mwxj) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L78)):*
> ```Smalltalk
>         public static string ToBase64String(this Model model, bool drawEdges = false)
>         {
>             // var buffer = new List<byte>();
> ```

remove
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 858 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu7magEyaYMXlxRki5:-MIu7magEyaYMXlxRki6:b-o4biro) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L858)):*
> ```Smalltalk
>                     if (File.Exists(content.GltfLocation))
>                     {
>                         // var currentMaterials = gltf.Materials.ToList();
> ```

do we need these? 
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 861 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu7th6A5oIEPSidFrt:-MIu7th6A5oIEPSidFru:b-b2s7aq) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L861)):*
> ```Smalltalk
>                         // var currentImages = gltf.Images != null ? gltf.Images.ToList() : new List<Image>();
>                         // var currentTextures = gltf.Textures != null ? gltf.Textures.ToList() : new List<Texture>();
>                         var meshIndices = GlftMergingUtils.AddAllMeshesFromFromGlb(content.GltfLocation,
> ```

glft => gltf
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 877 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu7oCP95Y6-VP3kjzG:-MIu7oCP95Y6-VP3kjzH:b2ni25r) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L877)):*
> ```Smalltalk
>                             meshElementMap.Add(e.Id, meshIndices);
>                         }
>                         // gltf.Materials = currentMaterials.ToArray();
> ```

etc
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 879 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu8SgCEc6Zu8SdoJg7:-MIu8SgCEc6Zu8SdoJg8:bi4vs4a) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L879)):*
> ```Smalltalk
>                         // gltf.Materials = currentMaterials.ToArray();
>                     }
>                     else
> ```

is this adding the bounding box if it was unable to find the mesh? an explanatory comment would be helpful here. 
___
*[Elements/src/Serialization/glTF/GltfMergingUtils.cs, line 11 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu8cye4Kk1-eIHZykL:-MIu8cye4Kk1-eIHZykM:b-b2s7aq) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfMergingUtils.cs#L11)):*
> ```Smalltalk
> {
> 
>     internal static class GlftMergingUtils
> ```

glft => gltf

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 4 of 15 files at r1, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 8 unresolved discussions (waiting on @ikeough and @wynged)

**Review by andrewheumann — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 8 unresolved discussions (waiting on @ikeough and @wynged)

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 14 unresolved discussions (waiting on @andrewheumann and @wynged)

___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 879 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu8SgCEc6Zu8SdoJg7:-MIuj-ya6dunT9QSU8_f:b-7luhyz) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L879)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

is this adding the bounding box if it was unable to find the mesh? an explanatory comment would be helpful here. 
</blockquote></details>

I second Andrew's point, and I'll go further to argue that inside this method does not seem like the place to have code for generating geometry.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 269 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIuJFW7AXcRG4PHFIfY:-MIuJFW7AXcRG4PHFIfZ:b7a5vzw) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/src/Serialization/glTF/GltfExtensions.cs#L269)):*
> ```Smalltalk
>                 lightCount++;
>             }
>             if (lightsArr.Count > 0)
> ```

Some formatting errors here. Line space above, and indentation.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 685 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIuhUlU0t4xZ1WJCJHS:-MIuhUlU0t4xZ1WJCJHT:b-mys8w) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/src/Serialization/glTF/GltfExtensions.cs#L685)):*
> ```Smalltalk
>         {
>             var buff = new glTFLoader.Schema.Buffer();
>             var buffers = new List<glTFLoader.Schema.Buffer> { buff };
> ```

I'd recommend renaming these to `schemaBuffer` and `schemaBuffers` because they aren't actually buffers. Then you can call the below `buffer` and `buffers`. 

A buffer is commonly an array of bytes (as it is here).
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 687 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIuhJK9DCwZ4KK9RE5g:-MIuhJK9DCwZ4KK9RE5h:b-nmjyt1) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/src/Serialization/glTF/GltfExtensions.cs#L687)):*
> ```Smalltalk
>             var buffers = new List<glTFLoader.Schema.Buffer> { buff };
>             var bufferBytes = new List<byte>();
>             allBufferByteArrays = new List<byte[]> { Array.Empty<byte>() };
> ```

Do you have to allocate this? Or can you just do `new List<byte[]>()`?
___
*[Elements/test/GltfTests.cs, line 53 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIukPec6X3gZaGE6RGz:-MIukPec6X3gZaGE6RH-:bvkbmjy) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/test/GltfTests.cs#L53)):*
> ```Smalltalk
>                                       "BoxyType");
>             var boxType2 = new BoxElem("../../../models/MergeGlTF/Duck.glb",
>                                       new BBox3(new Vector3(-1, 1, 0), new Vector3(1, 1, 4)),
> ```

I don't like having a bounding box parameter for two reasons.  First, although content from some locations might be able to set this (i.e. Revit), in many other cases it will be set to some default.  I would prefer that this is a method like `BoundingBox()` which returns a bounding box from the bounding box information in the glb.  This could be pulled from a `POSITION` accessor's `MIN` and `MAX` properties. It's also unclear what this bbox represents? Is it the pre or post transformed bounds of everything in the gltf?
___
*[Elements/test/GltfTests.cs, line 75 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIun8nWDgfsRt019oqy:-MIun8nWDgfsRt019oqz:bof6cjd) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/test/GltfTests.cs#L75)):*
> ```Smalltalk
>             var testPath = "../../../models/MergeGlTF/Ours.glb";
>             var ours = Interface.LoadModel(testPath);
>             var buffers = ours.Buffers.ToList();
> ```

Every `ToList` and `ToArray` allocates memory. Is it possible to do these operations without using these extension methods? It may not be. At the very least, these should be done with counts (https://thomaslevesque.com/2014/12/07/optimize-toarray-and-tolist-by-providing-the-number-of-elements/). 
___
*[Elements/test/GltfTests.cs, line 86 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIumP8SAea-ZOmU0D5-:-MIumP8SAea-ZOmU0D50:b-s707s0) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/test/GltfTests.cs#L86)):*
> ```Smalltalk
>             var bufferByteArrays = ours.GetAllBufferByteArrays(testPath);
> 
>             GlftMergingUtils.AddAllMeshesFromFromGlb("../../../models/MergeGlTF/Avocado.glb",
> ```

Could we make this an extension method on `GlTF` like `ours.MergeModel(...)`?

**Review by wynged — COMMENTED** [review]
> Reviewed 1 of 15 files at r1, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 14 unresolved discussions (waiting on @andrewheumann and @ikeough)

___
*[Elements/src/Generate/ContentElement.g.cs, line 54 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu6LvSDKCn790DwKmu:-MIyX99HEt_IG1XjLOI3:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Generate/ContentElement.g.cs#L54)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I think we should call the property itself BoundingBox — just a preference
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfBufferExtensions.cs, line 31 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu7TtQ5b92O3PCfiAb:-MIyXLBd7R-iZPb34P4n:b3l801y) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfBufferExtensions.cs#L31)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

is this var necessary? can we just call `relativeUri` `binSaveName`?
</blockquote></details>

Done. good call.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 78 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu6w2e4lMmMbXS24zD:-MIyXSFiEkuzYthMWK3y:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L78)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 858 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu7magEyaYMXlxRki5:-MIyYoho1Mktm0zK4RQa:b-qbvls1) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L858)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

do we need these? 
</blockquote></details>

Done. nope.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 861 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu7th6A5oIEPSidFrt:-MIyYqLlCEwq5Ztce6We:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L861)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

glft => gltf
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 877 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu7oCP95Y6-VP3kjzG:-MIyYrFHEAkk-r-rkeuA:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L877)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

etc
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 879 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu8SgCEc6Zu8SdoJg7:-MIyjdwDBAzOU0r3URgY:bo7p4i6) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L879)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I second Andrew's point, and I'll go further to argue that inside this method does not seem like the place to have code for generating geometry.
</blockquote></details>

I've moved this to share the extracted method with the GeometricElement path below where it adds the representation, and I've added an UpdateRepresentations override on ContentElement that uses the Bounding Box to add a solid.  This has the added advantage that if someone wanted to they could override that again to have a more accurate glb fallback.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 269 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIuJFW7AXcRG4PHFIfY:-MIyXfP202UrymbWKMfg:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/src/Serialization/glTF/GltfExtensions.cs#L269)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Some formatting errors here. Line space above, and indentation.
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 685 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIuhUlU0t4xZ1WJCJHS:-MIyXqd_AVoUNoGi2BiJ:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/src/Serialization/glTF/GltfExtensions.cs#L685)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I'd recommend renaming these to `schemaBuffer` and `schemaBuffers` because they aren't actually buffers. Then you can call the below `buffer` and `buffers`. 

A buffer is commonly an array of bytes (as it is here).
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 687 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIuhJK9DCwZ4KK9RE5g:-MIyYNUh7qdfbZlPUQi0:b-8fx0dv) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/src/Serialization/glTF/GltfExtensions.cs#L687)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Do you have to allocate this? Or can you just do `new List<byte[]>()`?
</blockquote></details>

I think I do need to allocated this this claims the spot for the first/main/primary buffer where all geometry that is created from Representations is stored.  the first item is re-assigned later on line 825.  subsequent buffers are the imported ones.
___
*[Elements/src/Serialization/glTF/GltfMergingUtils.cs, line 11 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu8cye4Kk1-eIHZykL:-MIykJ4V-XeSo_AcGoCN:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfMergingUtils.cs#L11)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

glft => gltf
</blockquote></details>

Done.
___
*[Elements/test/GltfTests.cs, line 53 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIukPec6X3gZaGE6RGz:-MIykSexAyxgFStH51G9:b-gvjs51) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/test/GltfTests.cs#L53)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I don't like having a bounding box parameter for two reasons.  First, although content from some locations might be able to set this (i.e. Revit), in many other cases it will be set to some default.  I would prefer that this is a method like `BoundingBox()` which returns a bounding box from the bounding box information in the glb.  This could be pulled from a `POSITION` accessor's `MIN` and `MAX` properties. It's also unclear what this bbox represents? Is it the pre or post transformed bounds of everything in the gltf?
</blockquote></details>

This is the fallback case for when the  glb can't be found, so I think it has an important role.  Content is a created and curated thing, not a blind export, so there's no reason a bounding box can't be found/entered except for things that have no geometry.  

The box represents roughly the space that an object takes up in a model, and makes it easy to determine how the object relates to its insertion point.  Is the box "above" the XY plane?  is it centered on the origin?  Is the origin at a corner? (min or max is (0,0,0))?
___
*[Elements/test/GltfTests.cs, line 75 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIun8nWDgfsRt019oqy:-MIynKCW-JPuTDZfqPT5:bc8pomv) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/test/GltfTests.cs#L75)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Every `ToList` and `ToArray` allocates memory. Is it possible to do these operations without using these extension methods? It may not be. At the very least, these should be done with counts (https://thomaslevesque.com/2014/12/07/optimize-toarray-and-tolist-by-providing-the-number-of-elements/). 
</blockquote></details>

done.  definitely strikes me as premature optimization, but it's cool to know about.  I haven't done it here because these are tests, but I've done it in the production code wherever we do `ToArray()`
___
*[Elements/test/GltfTests.cs, line 86 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIumP8SAea-ZOmU0D5-:-MIynWMU8nIpaRMWaoXS:b-nten7t) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/test/GltfTests.cs#L86)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Could we make this an extension method on `GlTF` like `ours.MergeModel(...)`?
</blockquote></details>

We could, but I think that's a bit more confusing.  we don't need the GlTF, so the `this Gltf` is just kind of floating around and we actually don't *want* to operate on it, almost all of it's properties are reset at the end of the parent methods because we operate on lists while we are building our Gltf, and then convert to arrays.  I'd rather push the other direction with more static methods and a functional approach.

**Review by ikeough — CHANGES_REQUESTED** [review]
You also need to update `CHANGELIST.md` to relfect new types being added (`ContentElement` and possible others), and changes/updates to public APIs.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394#-:-MJ-4REkEwJt6tQZnm9h:b-5jgra3)* status: all files reviewed, 14 unresolved discussions (waiting on @andrewheumann, @ikeough, and @wynged)

___
*[Elements/src/ContentElement.cs, line 17 at r5](https://reviewable.io/reviews/hypar-io/elements/394#-MJ-1mef4F4xUOPG4sGo:-MJ-1mef4F4xUOPG4sGp:b-63yady) ([raw file](https://github.com/hypar-io/elements/blob/d12c547083fc86bf48206a52b044dc0e18155be6/Elements/src/ContentElement.cs#L17)):*
> ```Smalltalk
>         public override void UpdateRepresentations()
>         {
>             if (BoundingBox.Min.X == BoundingBox.Max.X
> ```

Can we move this check into the validator for BBox?
___
*[Elements/src/Geometry/Transform.cs, line 400 at r5](https://reviewable.io/reviews/hypar-io/elements/394#-MJ-2DVVCMahiyUligKz:-MJ-2DVVCMahiyUligL-:brrt1at) ([raw file](https://github.com/hypar-io/elements/blob/d12c547083fc86bf48206a52b044dc0e18155be6/Elements/src/Geometry/Transform.cs#L400)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Return copy of this transform scaled uniformly about the origin.
> ```

"Return a copy..."

I think we should remove "about the origin".
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 884 at r5](https://reviewable.io/reviews/hypar-io/elements/394#-MJ-38892dfasmtJoFBH:-MJ-38892dfasmtJoFBI:b-flhvmu) ([raw file](https://github.com/hypar-io/elements/blob/d12c547083fc86bf48206a52b044dc0e18155be6/Elements/src/Serialization/glTF/GltfExtensions.cs#L884)):*
> ```Smalltalk
>                             // apply scale transform here to bring the content glb into meters
>                             var transform = new Transform().Scaled(content.GltfScaleToMeters);
>                             transform.Concatenate(content.Transform);
> ```

Given your new APIs, can't we just do `content.Transform.Scaled(content.GltfScaleToMeters)`?
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 891 at r5](https://reviewable.io/reviews/hypar-io/elements/394#-MJ-3OoL7jwgQIxU09dW:-MJ-3OoL7jwgQIxU09dX:b-ds67af) ([raw file](https://github.com/hypar-io/elements/blob/d12c547083fc86bf48206a52b044dc0e18155be6/Elements/src/Serialization/glTF/GltfExtensions.cs#L891)):*
> ```Smalltalk
>                             // This element will be used for instancing.  Save the trasnform of the
>                             // content element base that will be needed when instances are placed.
>                             // The scaled transform is only necessary becuase we are using the glb.
> ```

"because"
___
*[Elements/test/GltfTests.cs, line 75 at r4](https://reviewable.io/reviews/hypar-io/elements/394#-MIun8nWDgfsRt019oqy:-MJ-46dKBw_5VTlOptI5:b-6kdyia) ([raw file](https://github.com/hypar-io/elements/blob/9ba0548b9294158d9039c4a3d8314d826b1b52bf/Elements/test/GltfTests.cs#L75)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

done.  definitely strikes me as premature optimization, but it's cool to know about.  I haven't done it here because these are tests, but I've done it in the production code wherever we do `ToArray()`
</blockquote></details>

Optimally we'd get rid of them altogether.

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 14 unresolved discussions (waiting on @andrewheumann and @ikeough)

___
*[Elements/src/ContentElement.cs, line 17 at r5](https://reviewable.io/reviews/hypar-io/elements/394#-MJ-1mef4F4xUOPG4sGo:-MJ2CQol7hY4XqddyASn:bb7f2mf) ([raw file](https://github.com/hypar-io/elements/blob/d12c547083fc86bf48206a52b044dc0e18155be6/Elements/src/ContentElement.cs#L17)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Can we move this check into the validator for BBox?
</blockquote></details>

done
___
*[Elements/src/Geometry/Transform.cs, line 400 at r5](https://reviewable.io/reviews/hypar-io/elements/394#-MJ-2DVVCMahiyUligKz:-MJ2Dyqi7EQWFHTQ4KB1:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/d12c547083fc86bf48206a52b044dc0e18155be6/Elements/src/Geometry/Transform.cs#L400)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

"Return a copy..."

I think we should remove "about the origin".
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 879 at r3](https://reviewable.io/reviews/hypar-io/elements/394#-MIu8SgCEc6Zu8SdoJg7:-MJ29gl-2_4b6BYKthBw:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/1d3f0b27456093c6d8a8b4940dd048207465391b/Elements/src/Serialization/glTF/GltfExtensions.cs#L879)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I've moved this to share the extracted method with the GeometricElement path below where it adds the representation, and I've added an UpdateRepresentations override on ContentElement that uses the Bounding Box to add a solid.  This has the added advantage that if someone wanted to they could override that again to have a more accurate glb fallback.
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 884 at r5](https://reviewable.io/reviews/hypar-io/elements/394#-MJ-38892dfasmtJoFBH:-MJ2FFTO1XDj0Pofxn9k:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/d12c547083fc86bf48206a52b044dc0e18155be6/Elements/src/Serialization/glTF/GltfExtensions.cs#L884)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Given your new APIs, can't we just do `content.Transform.Scaled(content.GltfScaleToMeters)`?
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 891 at r5](https://reviewable.io/reviews/hypar-io/elements/394#-MJ-3OoL7jwgQIxU09dW:-MJ2A3adD7WgFfVsD3cG:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/d12c547083fc86bf48206a52b044dc0e18155be6/Elements/src/Serialization/glTF/GltfExtensions.cs#L891)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

"because"
</blockquote></details>

Done.

**Review by ikeough — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: 16 of 21 files reviewed, 8 unresolved discussions (waiting on @andrewheumann, @ikeough, and @wynged)

**Review by wynged — COMMENTED** [review]
> Reviewed 1 of 15 files at r1, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 8 unresolved discussions (waiting on @andrewheumann)

**Review by wynged — COMMENTED** [review]
> Reviewed 5 of 15 files at r1, 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: 20 of 21 files reviewed, 8 unresolved discussions (waiting on @andrewheumann and @wynged)

**Review by wynged — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 8 unresolved discussions (waiting on @andrewheumann)

**Review by ikeough — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 8 unresolved discussions (waiting on @andrewheumann)

**Review by ikeough — APPROVED** [review]
> Reviewed 6 of 15 files at r1, 5 of 6 files at r3, 5 of 7 files at r5, 4 of 5 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 8 unresolved discussions (waiting on @andrewheumann)

**Review by ikeough — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: all files reviewed, 8 unresolved discussions (waiting on @andrewheumann)

**Review by wynged — COMMENTED** [review]
> Dismissed @andrewheumann from 8 discussions.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by wynged — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/394)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
