### PR TITLE
Adaptive grid examples

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- Didn't quite have the AdaptiveGrid documentation example code and glb wired up correctly

DESCRIPTION:
- change glb name and add `example` tags inside test code.
- update readme with some instructions.

TESTING:
- run `build_docs.sh` to see the glb now loading correctly.
  
FUTURE WORK:
- Is there any future work needed or anticipated?  Does this PR create any obvious technical debt?

REQUIRED:
~- [ ] All changes are up to date in `CHANGELOG.md`.~

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/789)

### CODE REVIEW

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/789)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[README.md, line 88 at r1](https://reviewable.io/reviews/hypar-io/elements/789#-MyxAji605Z8W70v6M_T:-Mz1UcUR-FFtENLF5KrK:bkqls6k) ([raw file](https://github.com/hypar-io/elements/blob/a17c0352ce1ace8db819b1c0e521fa2c4de3d02a/README.md#L88)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Looks like a double space here "...the code to appear.  The value..." Change to a single space.
Capitalize  "See" in "see Joist.cs".  
</blockquote></details>

Done. good eyes

**Review by ikeough — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/789)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @wynged)

___
*[Elements/test/AdaptiveGridTests.cs, line 40 at r2](https://reviewable.io/reviews/hypar-io/elements/789#-MzB1_Y05UwXcyafRGZn:-MzB1FHZBIKy4DJUE_DO:bgnvt1i) ([raw file](https://github.com/hypar-io/elements/blob/43fc4ef3d9b131f75887680af8b2046a621e5c7c/Elements/test/AdaptiveGridTests.cs#L40)):*
> ```Smalltalk
>         }
> 
>         [Fact, Trait("Category", "Examples")]
> ```

Why are we adding example tags, but removing this attribution? If you want `example2` to be available, we need to run this test when we build the docs.

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/789)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/test/AdaptiveGridTests.cs, line 40 at r2](https://reviewable.io/reviews/hypar-io/elements/789#-MzB1_Y05UwXcyafRGZn:-MzFlpmX9jeog8r5h5mC:bggvqqp) ([raw file](https://github.com/hypar-io/elements/blob/43fc4ef3d9b131f75887680af8b2046a621e5c7c/Elements/test/AdaptiveGridTests.cs#L40)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Why are we adding example tags, but removing this attribution? If you want `example2` to be available, we need to run this test when we build the docs.
</blockquote></details>

Running the tests seems to be required for generating a model, but I don't think it's part of inserting sample code into the documentation.  We have kept our one allowed sample model in the first sample.

When I run the docs locally I do see this sample code in the api docs.

**Review by ikeough — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/789)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ikeough)

**Pull request merged**
