### PR TITLE
Warning cleanup

### PR DESCRIPTION
**Pull request by andrewheumann**
BACKGROUND:
- Over time, and especially with the recent addition of Elements.Components, we had accumulated a lot of build warnings in Elements 

DESCRIPTION:
- Adds minimal XML comments to Elements.Components
- Fixes other errors/warnings that were being thrown

TESTING:
- tests passing, no more build warnings
  
FUTURE WORK:
- Not all the Elements.Components comments are very descriptive, and could use some work

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/559)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, 25 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/559)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements.Components/src/Rules/ArrayPlacementRule.cs, line 20 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MW_zyQI95MIEbR5KYVQ:-MW_zyQI95MIEbR5KYVR:b3q0xel) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/ArrayPlacementRule.cs#L20)):*
> ```Smalltalk
>         /// <param name="arrayPath">The path along which to array</param>
>         /// <param name="spacingRule">The configuration for the spacing</param>
>         /// <param name="anchorIndices"></param>
> ```

missing a few descriptions
___
*[Elements.Components/src/Rules/ArrayPlacementRule.cs, line 39 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-1AQ33FMsPTvxpW-:-MWa-1AQ33FMsPTvxpW0:b-tcejeh) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/ArrayPlacementRule.cs#L39)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The indices of the source anchors corresponding to each displacement
> ```

ian likes periods at the end of sentences.
___
*[Elements.Components/src/Rules/ArrayPlacementRule.cs, line 96 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-5hM4rhwdAQUBG4_:-MWa-5hM4rhwdAQUBG4a:b-2w5hah) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/ArrayPlacementRule.cs#L96)):*
> ```Smalltalk
>         /// Construct a set of elements from this rule for a given definition.
>         /// </summary>
>         /// <param name="definition"></param>
> ```

description.
___
*[Elements.Components/src/Rules/ComponentPlacementRule.cs, line 34 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-9D1DYNnnwjz4lYq:-MWa-9D1DYNnnwjz4lYr:b-b8wlj4) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/ComponentPlacementRule.cs#L34)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// 
> ```

empty summary.
___
*[Elements.Components/src/Rules/IComponentPlacementRule.cs, line 17 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-IEG-Qbv4WPFvDuU:-MWa-IEH2QT0IG3Ax941:b2nful3) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/IComponentPlacementRule.cs#L17)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Create elements from this rule based on a 
> ```

based on a... the suspense is killing me.
___
*[Elements.Components/src/Rules/IComponentPlacementRule.cs, line 40 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-Lv08LbVRk6iaesp:-MWa-Lv08LbVRk6iaesq:b-rntcnz) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/IComponentPlacementRule.cs#L40)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The displacement vectors for each curve vertex from its anchor
> ```

periods.
___
*[Elements.Components/src/Rules/PolylinePlacementRule.cs, line 16 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-PKa3y9vvqjmEvh7:-MWa-PKa3y9vvqjmEvh8:bfygtea) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/PolylinePlacementRule.cs#L16)):*
> ```Smalltalk
>         /// Construct a new Polyline Placement rule
>         /// </summary>
>         /// <param name="p"></param>
> ```

should probably call this argument  `polyline`
___
*[Elements.Components/src/Rules/PolylinePlacementRule.cs, line 34 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-Tt88sbXQ6YfXgpG:-MWa-Tt88sbXQ6YfXgpH:b-rntcnz) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/PolylinePlacementRule.cs#L34)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The displacement from each anchor
> ```

periods.
___
*[Elements.Components/src/Rules/PositionPlacementRule.cs, line 33 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-bSGD6ipS5PRzrOe:-MWa-bSGD6ipS5PRzrOf:b-kw3u9k) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/PositionPlacementRule.cs#L33)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The index of the anchor this element transforms with
> ```

transforms with => follows ?
___
*[Elements.Components/src/Rules/SizeBasedPlacementRule.cs, line 37 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-ha1AB7fhfWDvYli:-MWa-ha1AB7fhfWDvYlj:b-rntcnz) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/SizeBasedPlacementRule.cs#L37)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The displacement from each anchor
> ```

periods.
___
*[Elements.Components/src/Rules/SizeBasedPlacementRule.cs, line 63 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-k9V1gvONBWmLz9d:-MWa-k9V1gvONBWmLz9e:bs04k4w) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/SizeBasedPlacementRule.cs#L63)):*
> ```Smalltalk
>         /// </summary>
>         /// <param name="elementsAndClearances"></param>
>         /// <param name="p"></param>
> ```

p => polygon
___
*[Elements.Components/src/Rules/SpacingConfiguration.cs, line 18 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-nUu9xrqmuICoZ6w:-MWa-nUu9xrqmuICoZ6x:b-sj8eou) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/SpacingConfiguration.cs#L18)):*
> ```Smalltalk
>         /// <summary>
>         /// Construct the array with an approximate length. Value = target length.
>         /// </summary>    
> ```

trailing spaces.

**Review by andrewheumann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/559)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements.Components/src/Rules/ArrayPlacementRule.cs, line 20 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MW_zyQI95MIEbR5KYVQ:-MWa5_nU235mH4Yz1tsl:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/ArrayPlacementRule.cs#L20)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

missing a few descriptions
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/ArrayPlacementRule.cs, line 39 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-1AQ33FMsPTvxpW-:-MWa7lcABghkxEqrph3l:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/ArrayPlacementRule.cs#L39)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

ian likes periods at the end of sentences.
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/ArrayPlacementRule.cs, line 96 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-5hM4rhwdAQUBG4_:-MWa7mfo7KmmD_IgCi2Q:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/ArrayPlacementRule.cs#L96)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

description.
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/ComponentPlacementRule.cs, line 34 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-9D1DYNnnwjz4lYq:-MWa85iOAJYIz-7Pz3c-:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/ComponentPlacementRule.cs#L34)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

empty summary.
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/IComponentPlacementRule.cs, line 17 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-IEG-Qbv4WPFvDuU:-MWa88GQAn5GW5dKpCpY:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/IComponentPlacementRule.cs#L17)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

based on a... the suspense is killing me.
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/IComponentPlacementRule.cs, line 40 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-Lv08LbVRk6iaesp:-MWa88q98Lzour5v9zoA:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/IComponentPlacementRule.cs#L40)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

periods.
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/PolylinePlacementRule.cs, line 16 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-PKa3y9vvqjmEvh7:-MWa8XdI2GRp2KeK6Vsz:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/PolylinePlacementRule.cs#L16)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

should probably call this argument  `polyline`
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/PolylinePlacementRule.cs, line 34 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-Tt88sbXQ6YfXgpG:-MWa8Y407_aI56jNW2Wm:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/PolylinePlacementRule.cs#L34)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

periods.
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/PositionPlacementRule.cs, line 33 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-bSGD6ipS5PRzrOe:-MWa8i7O0jjbFrwTh8ou:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/PositionPlacementRule.cs#L33)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

transforms with => follows ?
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/SizeBasedPlacementRule.cs, line 37 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-ha1AB7fhfWDvYli:-MWa8iaO4TItb6hbchBV:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/SizeBasedPlacementRule.cs#L37)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

periods.
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/SizeBasedPlacementRule.cs, line 63 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-k9V1gvONBWmLz9d:-MWa8iuQ4jah4nGz35AN:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/SizeBasedPlacementRule.cs#L63)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

p => polygon
</blockquote></details>

Done.
___
*[Elements.Components/src/Rules/SpacingConfiguration.cs, line 18 at r2](https://reviewable.io/reviews/hypar-io/elements/559#-MWa-nUu9xrqmuICoZ6w:-MWa8vK1Dali_MCvDI63:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0e31df99b8401fbbdde5a9fc1f1f083ec219b37e/Elements.Components/src/Rules/SpacingConfiguration.cs#L18)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

trailing spaces.
</blockquote></details>

Done.

**Review by wynged — APPROVED** [review]
> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/559)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements.Components/src/Rules/SizeBasedPlacementRule.cs, line 47 at r3](https://reviewable.io/reviews/hypar-io/elements/559#-MWaG2BgAwGb9-dHbbWC:-MWaG2BhBXdoc9yKH8bJ:bkuvfoq) ([raw file](https://github.com/hypar-io/elements/blob/db920ace73cccd04daa535b18dd619f3bd05698b/Elements.Components/src/Rules/SizeBasedPlacementRule.cs#L47)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Is the boundary a closed shape?.
> ```

maybe punctuation overkill?

**Review by andrewheumann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/559)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @wynged)

___
*[Elements.Components/src/Rules/SizeBasedPlacementRule.cs, line 47 at r3](https://reviewable.io/reviews/hypar-io/elements/559#-MWaG2BgAwGb9-dHbbWC:-MWaI40NBj11hFlqVFnK:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/db920ace73cccd04daa535b18dd619f3bd05698b/Elements.Components/src/Rules/SizeBasedPlacementRule.cs#L47)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

maybe punctuation overkill?
</blockquote></details>

Done.

**Pull request merged**
