### PR TITLE
Catalog generation tweaks

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- New catalog generation technique in Revit wants new code gen of catalogs for use in functions.

DESCRIPTION:
- Add the reference instances to the generated code.
- Add option to use the ReferenceRotation in the generated code (so that orientation upon Revit export is respected as the "correct" orientation for the content)
- Fix a test that wasn't running, and breaking (TypeGeneratorTests)
- Allow de/serialization of either a catalog directly, or the new -model.json format, which is secretly a model.

TESTING:
- How should a reviewer observe the behavior desired by this pull request?
  
FUTURE WORK:
- Remove the old catalog style serial/deserialization

REQUIRED:
- [ x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/548)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 30 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/548)* status: all files reviewed, 3 unresolved discussions (waiting on @wynged)

___
*[Elements/src/ContentCatalog.cs, line 35 at r2](https://reviewable.io/reviews/hypar-io/elements/548#-MVaipQD5n7tlM-0d4fc:-MVaipQD5n7tlM-0d4fd:b-mmx1wf) ([raw file](https://github.com/hypar-io/elements/blob/1e1e13861850e3f8374ec9f8377fcbb2ffa08f8a/Elements/src/ContentCatalog.cs#L35)):*
> ```Smalltalk
>             else if (catalogObject.ContainsKey("Elements") && catalogObject.ContainsKey("Transform")) // catalog is stored in a model
>             {
>                 var model = catalogObject.ToObject<Model>();
> ```

Correct me if I'm wrong, but I *think* it's safer to use `Model.FromJson` — I know that means we wind up deserializing twice, but I think it has some important safeguards (which may not be relevant at this moment for catalogs, but I think it's worth doing)
___
*[Elements/src/ContentCatalog.cs, line 60 at r2](https://reviewable.io/reviews/hypar-io/elements/548#-MVajGMo-T6VfchXPOCy:-MVajGMo-T6VfchXPOCz:bs0xctk) ([raw file](https://github.com/hypar-io/elements/blob/1e1e13861850e3f8374ec9f8377fcbb2ffa08f8a/Elements/src/ContentCatalog.cs#L60)):*
> ```Smalltalk
>                     continue;
>                 }
>                 var referenceOrientation = refInstance.Transform.Concatenated(new Geometry.Transform(refInstance.Transform.Origin.Negate()));
> ```

I know why this is here, but let's leave a comment for future us — we want to respect rotation but not position of the original elements.
___
*[Elements.CodeGeneration/src/CatalogGenerator.cs, line 47 at r2](https://reviewable.io/reviews/hypar-io/elements/548#-MVajPkDA6QBH1MxXrqp:-MVajPkDA6QBH1MxXrqq:bv6mzd) ([raw file](https://github.com/hypar-io/elements/blob/1e1e13861850e3f8374ec9f8377fcbb2ffa08f8a/Elements.CodeGeneration/src/CatalogGenerator.cs#L47)):*
> ```Smalltalk
>         /// <param name="uri">The location of the catalog json file.</param>
>         /// <param name="saveDirectory">The folder of where to save the resulting generated code.</param>
>         /// <param name="useReferenceOrientation">Wether to apply the orientations of Reference elements found in the catalog to orient the content.</param>
> ```

Wether => Whether

Maybe something like "Should ContentElements be reoriented to match the rotation they had when they were exported?"

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/548)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @andrewheumann)

___
*[Elements/src/ContentCatalog.cs, line 35 at r2](https://reviewable.io/reviews/hypar-io/elements/548#-MVaipQD5n7tlM-0d4fc:-MVbBhLq5ysVCVMY1mmS:b-8l9ewf) ([raw file](https://github.com/hypar-io/elements/blob/1e1e13861850e3f8374ec9f8377fcbb2ffa08f8a/Elements/src/ContentCatalog.cs#L35)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Correct me if I'm wrong, but I *think* it's safer to use `Model.FromJson` — I know that means we wind up deserializing twice, but I think it has some important safeguards (which may not be relevant at this moment for catalogs, but I think it's worth doing)
</blockquote></details>

done.  good thought.
___
*[Elements/src/ContentCatalog.cs, line 60 at r2](https://reviewable.io/reviews/hypar-io/elements/548#-MVajGMo-T6VfchXPOCy:-MVbC28BDbMRqTAc7a7j:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/1e1e13861850e3f8374ec9f8377fcbb2ffa08f8a/Elements/src/ContentCatalog.cs#L60)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I know why this is here, but let's leave a comment for future us — we want to respect rotation but not position of the original elements.
</blockquote></details>

Done.
___
*[Elements.CodeGeneration/src/CatalogGenerator.cs, line 47 at r2](https://reviewable.io/reviews/hypar-io/elements/548#-MVajPkDA6QBH1MxXrqp:-MVbCAfw707UY-5OaUGh:b-7rl0jd) ([raw file](https://github.com/hypar-io/elements/blob/1e1e13861850e3f8374ec9f8377fcbb2ffa08f8a/Elements.CodeGeneration/src/CatalogGenerator.cs#L47)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Wether => Whether

Maybe something like "Should ContentElements be reoriented to match the rotation they had when they were exported?"
</blockquote></details>

done.

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 25 of 25 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/548)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

**Review by andrewheumann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/548)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

**Pull request merged**
