### PR TITLE
Polygon trim

### PR DESCRIPTION
**Pull request by ikeough**
BACKGROUND:
- For work on allowable envelopes, we need a way to trim polygons with planes and other polygons.

DESCRIPTION:
- This PR implements 3d polygon trimming with a plane.

TESTING:
- There are several new tests in `PolygonTests` which validate that polygon trimming can return multiple polygons, correctly handle trims coincident with vertices, and handle flipped trims.
  
FUTURE WORK:
- Is there any future work needed or anticipated?  Does this PR create any obvious technical debt?

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

image

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/586)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
This is great, the code is very clear. A few very minor comments. 

> Reviewed 4 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/586#-:-MaYFGQaBD5ROkB73P-o:badwi3p)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/src/Geometry/Polygon.cs, line 260 at r2](https://reviewable.io/reviews/hypar-io/elements/586#-MaYEAXy1b7dhXyXzwhn:-MaYEAXy1b7dhXyXzwho:b-7oh6lj) ([raw file](https://github.com/hypar-io/elements/blob/b5a69a6c759d55834f202931834362226b0ed4cc/Elements/src/Geometry/Polygon.cs#L260)):*
> ```Smalltalk
>         /// <param name="results">A collection of intersection results 
>         /// sorted along the plane.</param>
>         /// <param name="distinct">Should the intersections results that
> ```

intersections results => intersection results
___
*[Elements/src/Geometry/Polygon.cs, line 315 at r2](https://reviewable.io/reviews/hypar-io/elements/586#-MaYEc2G1UR45eShNV-g:-MaYEc2G1UR45eShNV-h:b4pcve3) ([raw file](https://github.com/hypar-io/elements/blob/b5a69a6c759d55834f202931834362226b0ed4cc/Elements/src/Geometry/Polygon.cs#L315)):*
> ```Smalltalk
>                 var d2 = pt2 - pt1;
>                 var c = d1.Cross(d2);
>                 if (c.X.ApproximatelyEquals(0.0)
> ```

I think you could use `c.IsZero()` here

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/586)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/586)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Polygon.cs, line 260 at r2](https://reviewable.io/reviews/hypar-io/elements/586#-MaYEAXy1b7dhXyXzwhn:-Mafw6I74eZySfjvGZfD:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/b5a69a6c759d55834f202931834362226b0ed4cc/Elements/src/Geometry/Polygon.cs#L260)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

intersections results => intersection results
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Polygon.cs, line 315 at r2](https://reviewable.io/reviews/hypar-io/elements/586#-MaYEc2G1UR45eShNV-g:-MafwZnR9RnelKGrfJFx:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/b5a69a6c759d55834f202931834362226b0ed4cc/Elements/src/Geometry/Polygon.cs#L315)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I think you could use `c.IsZero()` here
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/586)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
