### PR TITLE
Network fixes

### PR DESCRIPTION
**Pull request by ikeough**
BACKGROUND:
While working on a project constructing a network from connected walls, I found that the static constructor provided on `Network<T>` returned a `Network<Line>` instead of a `Network<Wall>`, which made it impossible to correlate the walls and the network. This PR fixes that while also adding small fixes for other issues aligned with the same work.

DESCRIPTION:
- Fixes an error with backwards traversal.
- Updates the constructor that creates a `Network<T>` from a collection of lines to return a `Network<T>` instead of a `Network<Line>`.
- Removes swear words from the code.
- Adds the `Network<T>.ToModelCurves()` method, which draws only the edges of the network, as opposed to the `Network<T>.ToModelArrows()` method which draws arrows.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/669)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/669)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/src/Search/AdjacencyList.cs, line 54 at r2](https://reviewable.io/reviews/hypar-io/elements/669#-MkJdcBB6NbZ2j6nrbbS:-MkJdcBC5qYIRKw8XRTD:b-fkk1mn) ([raw file](https://github.com/hypar-io/elements/blob/15254d5357cdcf334e0163c62796f104bc8dd53c/Elements/src/Search/AdjacencyList.cs#L54)):*
> ```Smalltalk
>         /// <param name="data">The data associated with the edge.</param>
>         public void AddEdgeAtEnd(int start, int end, T data)
>         {
> ```

seems like we still might want to capture that error, even if we don't want to swear about it?
___
*[Elements/src/Search/Network.cs, line 126 at r2](https://reviewable.io/reviews/hypar-io/elements/669#-MkJe_t66U6aQveaATjj:-MkJe_t66U6aQveaATjk:bl6v4n2) ([raw file](https://github.com/hypar-io/elements/blob/15254d5357cdcf334e0163c62796f104bc8dd53c/Elements/src/Search/Network.cs#L126)):*
> ```Smalltalk
>             var events = items.SelectMany((item, i) =>
>             {
>                 var segment = getSegment(item);
> ```

feel free to say this is out of scope, but could we make a class here or, or use named tuples?  all these "items" that live at "Item4" look confusing as heck.

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/669)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/Search/AdjacencyList.cs, line 54 at r2](https://reviewable.io/reviews/hypar-io/elements/669#-MkJdcBB6NbZ2j6nrbbS:-MksZnDr8vHVy3jurihF:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/25879734fd3c7e7f24c16c407ab25a82926bd2b3/Elements/src/Search/AdjacencyList.cs#L54)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

seems like we still might want to capture that error, even if we don't want to swear about it?
</blockquote></details>

Done.
___
*[Elements/src/Search/Network.cs, line 126 at r2](https://reviewable.io/reviews/hypar-io/elements/669#-MkJe_t66U6aQveaATjj:-MksWTkOEcY-N3Mb4WZq:b-cw5jft) ([raw file](https://github.com/hypar-io/elements/blob/25879734fd3c7e7f24c16c407ab25a82926bd2b3/Elements/src/Search/Network.cs#L126)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

feel free to say this is out of scope, but could we make a class here or, or use named tuples?  all these "items" that live at "Item4" look confusing as heck.
</blockquote></details>

Done. Tuple names added.

**Review by wynged — COMMENTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/669)* status: 1 change requests, 0 of 1 approvals obtained

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/669)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
