### PR TITLE
Add todo

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- While exploring a gltf regression we attempted to use a test library but it isn't available until .NET 6.

DESCRIPTION:
- Add a note about a using gltf validation library when we migrate to .NET 6.

TESTING:
- N/A
  
FUTURE WORK:
- N/A

REQUIRED:
- ~[ ] All changes are up to date in `CHANGELOG.md`.~

COMMENTS:
- Any other notes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/883)

### CODE REVIEW

**Comment by ikeough** [comment]
@wynged What's happening with this PR?

**Comment by wynged** [comment]
Last we talked about this we were bummed we couldn't use this library and wanted to add the to-do.  I think I added you as a reviewer.

**Review by wynged — COMMENTED** [review]
would you like me to merge this or close the PR?  no reason to keep it floating around. @ikeough 

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/883#-:-NI0ZqxQ8gx8HUJ1ULVu:b-et92cn)* status: 0 of 1 approvals obtained (waiting on @ikeough)

**Review by ikeough — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/883#-:-NTPOUmK9MjAlR34A8r4:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
