### PR TITLE
Routing Fixes

### PR DESCRIPTION
**Pull request by DmytroMuravskyi**
BACKGROUND:
- After few iteration of changes in AdaptiveGrid and AdaptiveGraph routing. Regressions and inconveniences were found during testing of different workflow.

DESCRIPTION:
- Done 2 fixes in newly updated AdaptiveGrid/Obstacle.
- `AdaptiveGrid.AddVertices` with `ConnectCutAndExtend` how extends only up to `HintExtendDistance` distance.
- Add HintSnapDistance with default value of 3
- Rename AddExtendVertices into AddVerticesWithCustomExtension, add a extendDistance parameter to it and make it public
- Created EdgeInfo structure in AdaptiveGraphRouting instead of a value pair. Added `HasVerticalChange` parameter to it. Is used to do not modify turn cost if either of two edges in turn point is not horizontal.  This prevents "free to travel" loops under 2d hint lines.

TESTING:
- AdaptiveGraphRoutingTests is adjusted to use EdgeInfo .
- Added AddVerticesWithCustomExtension test.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Tolerance parameter in Line.PointOnLine is not really used anywhere in final version but I see it to be very useful in the future.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/892)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/892)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 185 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-NCzbdSr7n1sxEu8PGtj:-NCzbdSr7n1sxEu8PGtk:b-n5hm7u) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L185)):*
> ```Smalltalk
>         /// Precalculated information about the edge.
>         /// </summary>
>         public struct EdgeInfo
> ```

public or internal?  and if public, should we add the ulong id of the edge to this info?
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 896 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-44oaCNqFRBKkC6GW:-ND-44oaCNqFRBKkC6GX:be12qdx) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L896)):*
> ```Smalltalk
>                     !_configuration.SupportedAngles.Any(a => a.ApproximatelyEquals(angle, 0.01)))
>                 {
>                     weights[e.Id] = new EdgeInfo(w, double.PositiveInfinity, hasVerticalChange);
> ```

given how it's used in tests below it feels like we should have another constructor that takes in two Vertices and an optional factor (make 1 the default)  Use that constructor here and then in the tests.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 1016 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-2aEM0k1PuRu2sgWm:-ND-2aEM0k1PuRu2sgWn:bk7i30h) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L1016)):*
> ```Smalltalk
> 
>                 Vertex lastCut;
>                 if (hits[index].LineParam < -extendDistance)
> ```

Seeing this I'm realizing that LineParam is potentially a confusing name, I think of Param(eters) on a line as always being between 0 and 1 for a bounded line, but this nubmer is more like "OffsetDistanceAlongLine" or some other more concise name 
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 1053 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-39XQ0dzoMpfs6zaw:-ND-39XQ0dzoMpfs6zax:b2vmufp) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L1053)):*
> ```Smalltalk
>                 {
>                     Vertex finalCut;
>                     if (hits[index].LineParam > segmentLength + extendDistance)
> ```

for clarity can we make this a named method that returns the `finalCut`?
___
*[`Elements/src/Spatial/AdaptiveGrid/Obstacle.cs` line 57 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-3USOAb_2ESimjM5Y:-ND-3USOAb_2ESimjM5Z:b7e0qrh) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/Obstacle.cs#L57)):*
> ```Smalltalk
>             );
> 
>             return new Obstacle(polygon, wall.Height, offset, addPerimeterEdges, allowOutsideBoundary, null);
> ```

can we add/update obstacle wall tests that will confirm this is correct and doesn't regress.
___
*[`Elements/test/AdaptiveGraphRoutingTests.cs` line 140 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-4JB0D-y6Ic47vUo8:-ND-4JB0D-y6Ic47vUo9:b-ospc7r) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/test/AdaptiveGraphRoutingTests.cs#L140)):*
> ```Smalltalk
>                 var ep = grid.GetVertex(e.EndId).Point;
>                 var w = (sp - ep).Length();
>                 var hasVerticalChange = Math.Abs(sp.Z - ep.Z) > grid.Tolerance;
> ```

use new `EdgeInfo` constructor as suggested above.
___
*[`Elements/test/AdaptiveGridTests.cs` line 625 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-58LH6NSLlEdOXsdY:-ND-58LH6NSLlEdOXsdZ:b-oq43u5) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/test/AdaptiveGridTests.cs#L625)):*
> ```Smalltalk
>             Assert.Equal(new Vector3(8, 6), added[1].Point);
>             Assert.Single(added[0].Edges);
>             Assert.Single(added[1].Edges);
> ```

let's add an angled hint line here as well.  Suggest a line from (1,7) to (2,8) with an extension distance of 2.  I think this will result in a hit at (0,6) and _no_ hit at (4,10)

**Review by wynged — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/892)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi)

**Review by DmytroMuravskyi — COMMENTED** [review]
Besides requested changed next was done:
Line - BBox3 intersection: add tolerance check for better support of line touching box at a corner: intersection was sometimes not detected even if the hit is less than tolerance away.
Obstacle: make Points always return with offset for consistency. Remove Offset from AdaptiveGrid.SubtractObstacle. Previously, obstacle, created from Line would include Offset in Points, but Columns would not. I decided to make it the same

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/892#-:-NDYHOWmBjwcSdncCcWv:b-66bzen)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 185 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-NCzbdSr7n1sxEu8PGtj:-NDXuUjz36nuDHXNu1De:bu9wl4u) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L185)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

public or internal?  and if public, should we add the ulong id of the edge to this info?
</blockquote></details>

Done. Added Edge reference and utility constructor
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 896 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-44oaCNqFRBKkC6GW:-NDXuaOUAXaVFSR4BoUs:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L896)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

given how it's used in tests below it feels like we should have another constructor that takes in two Vertices and an optional factor (make 1 the default)  Use that constructor here and then in the tests.
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 1016 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-2aEM0k1PuRu2sgWm:-NDXx6jW--wXV9rWjC2M:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L1016)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

Seeing this I'm realizing that LineParam is potentially a confusing name, I think of Param(eters) on a line as always being between 0 and 1 for a bounded line, but this nubmer is more like "OffsetDistanceAlongLine" or some other more concise name 
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs` line 1053 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-39XQ0dzoMpfs6zaw:-NDYH4rC-oHDYNfRwkn8:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L1053)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

for clarity can we make this a named method that returns the `finalCut`?
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/Obstacle.cs` line 57 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-3USOAb_2ESimjM5Y:-NDXufAi7mXkHuZhfzAe:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/src/Spatial/AdaptiveGrid/Obstacle.cs#L57)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can we add/update obstacle wall tests that will confirm this is correct and doesn't regress.
</blockquote></details>

Done.
___
*[`Elements/test/AdaptiveGraphRoutingTests.cs` line 140 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-4JB0D-y6Ic47vUo8:-NDXugdj00WQ5FUwHDTa:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/test/AdaptiveGraphRoutingTests.cs#L140)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

use new `EdgeInfo` constructor as suggested above.
</blockquote></details>

Done.
___
*[`Elements/test/AdaptiveGridTests.cs` line 625 at r2](https://reviewable.io/reviews/hypar-io/elements/892#-ND-58LH6NSLlEdOXsdY:-NDXuk3M299BYyP1bpNw:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/635a7fc42c05d8ac541439347a809edc6d9babff/Elements/test/AdaptiveGridTests.cs#L625)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

let's add an angled hint line here as well.  Suggest a line from (1,7) to (2,8) with an extension distance of 2.  I think this will result in a hit at (0,6) and _no_ hit at (4,10)
</blockquote></details>

Done.

**Review by wynged — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/892)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[`Elements/test/ObstacleTests.cs` line 144 at r3](https://reviewable.io/reviews/hypar-io/elements/892#-NDiA4StA6rTDOhl1abv:-NDiA4StA6rTDOhl1abw:b-bxwgif) ([raw file](https://github.com/hypar-io/elements/blob/17b0e625f291cb1569b074c808d63de318bd59e3/Elements/test/ObstacleTests.cs#L144)):*
> ```Smalltalk
>         public void ObstacleFromWallHasCorrectOrientationInGrid()
>         {
>             var grid = new AdaptiveGrid();
> ```

Maybe I'm just not seeing it, but a method to help us visualize each of these conditions when we run the test would be great.  Not necessary to Merge, but let's make a note to ourselves to make seeing all of these tests very easy at some point.  I definitely can't create all this in my head.

**Pull request merged**
