### PR TITLE
Make vertex console writing optional

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- When using elements library and in debug mode geometry generation can be very slow because we get a load of logging about vertex management.  
image

DESCRIPTION:
- Make the logging of vertex data an explicit flag that needs to be set, intended for use while debugging.

TESTING:
- When using elements in a test for example this should change the default behavior so that it doesn't show all of these logs.
  
FUTURE WORK:
- Is there any future work needed or anticipated?  Does this PR create any obvious technical debt?

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/897)

### CODE REVIEW

**Review by andrewheumann — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/897)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Geometry/Tessellation/Tessellation.cs` line 16 at r1](https://reviewable.io/reviews/hypar-io/elements/897#-NE5lYbc3a8mWI0E3Hxo:-NE5lYbc3a8mWI0E3Hxp:b-7lue38) ([raw file](https://github.com/hypar-io/elements/blob/42108a2ba230e43831d28e980bc722ed585f99bc/Elements/src/Geometry/Tessellation/Tessellation.cs#L16)):*
> ```Smalltalk
>     internal static class Tessellation
>     {
>         private static bool LOG_TESSELATION = false;
> ```

The intention being that you'd just edit the code if you wanted to see the logging messages? We might consider an "unlisted" static boolean that's public, similar to `SkipCSGUnion`, so a power user who's not editing `Elements` but still wanted this logging could enable it. 

(IOW, public but with `   [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]` annotation)

But I'm not sure that case is particularly likely, since if you're debugging `Tesselate`, you probably need to edit Elements anyway. Your call. In any case, would be good to have a comment above describing what this is for, even if it's relatively obvious.

**Comment by ikeough** [comment]
Just comment the lines out for now. This is something that a logging framework can take care of for us, with varied levels of logging verbosity.

**Review by wynged — COMMENTED** [review]
added a TODO that we should remove this when we have a logging framework.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/897#-:-NE8Xl839K7QLUa_1e8J:b902kd4)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @andrewheumann)

___
*[`Elements/src/Geometry/Tessellation/Tessellation.cs` line 16 at r1](https://reviewable.io/reviews/hypar-io/elements/897#-NE5lYbc3a8mWI0E3Hxo:-NE8XfbM9KbwFMq4UBO1:bno7bp2) ([raw file](https://github.com/hypar-io/elements/blob/42108a2ba230e43831d28e980bc722ed585f99bc/Elements/src/Geometry/Tessellation/Tessellation.cs#L16)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

The intention being that you'd just edit the code if you wanted to see the logging messages? We might consider an "unlisted" static boolean that's public, similar to `SkipCSGUnion`, so a power user who's not editing `Elements` but still wanted this logging could enable it. 

(IOW, public but with `   [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]` annotation)

But I'm not sure that case is particularly likely, since if you're debugging `Tesselate`, you probably need to edit Elements anyway. Your call. In any case, would be good to have a comment above describing what this is for, even if it's relatively obvious.  
</blockquote></details>

added comment and TODO that we should remove this when we get a more robust logging system.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/897)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
