### PR TITLE
Polyline Intersects bug and GetSubsegment behavior change

### PR DESCRIPTION
**Pull request by mwojcik-sagiton**
BACKGROUND:
I found bug in `Polyline.Intersects(Polygon polygon, out var sharedSegments)` when there was odd number of intersections between polyline and polygon. 

I found also useful to revert output polyline direction when method input parameters are reversed.

DESCRIPTION:
In `Polyline.Intersects` method I was processing intersections in pairs, but when there was odd number of them, it led to wrong output. I fixed it by processing each intersection with following one. I also used `UniqueWithinTolerance()` extension method for  filtering vectors close to each other within tolerance.

Previously `GetSubsegment` method kept direction of `Polyline`. Now it will always traverse from start `Vector3` to end `Vector3` and will return path of that traverse.

TESTING:
Run unit tests 
  
FUTURE WORK:
- Is there any future work needed or anticipated?  Does this PR create any obvious technical debt?

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/901)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/901)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mwojcik-sagiton)

___
*[`Elements/src/Geometry/Polyline.cs` line 1164 at r1](https://reviewable.io/reviews/hypar-io/elements/901#-NE8zhKR94RE_jQiR3nF:-NE8zhKS2X9mzz8ciIFF:b7wanlb) ([raw file](https://github.com/hypar-io/elements/blob/5bf23a323ae8b462964435612ec08bdece9e68d6/Elements/src/Geometry/Polyline.cs#L1164)):*
> ```Smalltalk
>                     .ToList();
> 
>                 vertices.Insert(0, start);
> ```

The `insert(0,start)` and `Add(end)` are common between the two, and so is returning the new Polyline.  Could you set vertices equal to null/empty, then assign it in the if/else and then insert/add/return after that?
___
*[`Elements/test/PolylineTests.cs` line 541 at r1](https://reviewable.io/reviews/hypar-io/elements/901#-NE8x9MKE2nxKVIVgWKr:-NE8x9MKE2nxKVIVgWKs:bpnz249) ([raw file](https://github.com/hypar-io/elements/blob/5bf23a323ae8b462964435612ec08bdece9e68d6/Elements/test/PolylineTests.cs#L541)):*
> ```Smalltalk
>                 new Vector3(-2, 5));
> 
>             var result = polyline.Intersects(polygon, out var sharedSegments);
> ```

can we assert something about shared segments, like the count atleast?
___
*[`Elements/test/PolylineTests.cs` line 566 at r1](https://reviewable.io/reviews/hypar-io/elements/901#-NE8uskh4uhYKRb3mkEW:-NE8uskh4uhYKRb3mkEX:bke7f5q) ([raw file](https://github.com/hypar-io/elements/blob/5bf23a323ae8b462964435612ec08bdece9e68d6/Elements/test/PolylineTests.cs#L566)):*
> ```Smalltalk
> 
>             var reversedResult = polyline.GetSubsegment(new Vector3(5, 3), new Vector3(-5, -3));
>             var reversedExpectedResult = new Polyline(
> ```

let's explicitly make this a polyline created from the reverse of the previous result `Vertices`

**Review by mwojcik-sagiton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/901)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Geometry/Polyline.cs` line 1164 at r1](https://reviewable.io/reviews/hypar-io/elements/901#-NE8zhKR94RE_jQiR3nF:-NE9R-EoAzBqUYTnT7RM:boqd1f4) ([raw file](https://github.com/hypar-io/elements/blob/5bf23a323ae8b462964435612ec08bdece9e68d6/Elements/src/Geometry/Polyline.cs#L1164)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

The `insert(0,start)` and `Add(end)` are common between the two, and so is returning the new Polyline.  Could you set vertices equal to null/empty, then assign it in the if/else and then insert/add/return after that?
</blockquote></details>

you're totally right, I should do it before opening this PR 
___
*[`Elements/test/PolylineTests.cs` line 541 at r1](https://reviewable.io/reviews/hypar-io/elements/901#-NE8x9MKE2nxKVIVgWKr:-NE9TSRV2PKsM2ZwHqp4:bs7wumx) ([raw file](https://github.com/hypar-io/elements/blob/5bf23a323ae8b462964435612ec08bdece9e68d6/Elements/test/PolylineTests.cs#L541)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can we assert something about shared segments, like the count atleast?
</blockquote></details>

Done. 
___
*[`Elements/test/PolylineTests.cs` line 566 at r1](https://reviewable.io/reviews/hypar-io/elements/901#-NE8uskh4uhYKRb3mkEW:-NE9SBwjBEO6LXYnVWLO:b-s5j2g7) ([raw file](https://github.com/hypar-io/elements/blob/5bf23a323ae8b462964435612ec08bdece9e68d6/Elements/test/PolylineTests.cs#L566)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

let's explicitly make this a polyline created from the reverse of the previous result `Vertices`
</blockquote></details>

good point, I created `start` and `end` `Vector3` variables to make code more readable for other developers

**Review by wynged — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/901)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/901)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
