### PR TITLE
Adaptive Grid update

### PR DESCRIPTION
**Pull request by DmytroMuravskyi**
BACKGROUND:
- While working on new function that used AdaptiveGrid I collected all pieces of code related to AdaptiveGrid but located outside Elements. It make sense to place them directly into
- It was decided to move AdaptiveGraph routing and PriorityQueue into Elements as whey had no collections with previous repository.

DESCRIPTION:
- Remove AdaptiveGrid reference from Edge and Vertex to make it independent. Move Edge.GetVertices and Edge.GetLine to AdaptiveGrid.
- Add Vertex.GetEdge, Edge.OtherVertexId.
- Add default constructor to AdaptiveGrid to avoid manual creation of new Transform object.
- Add AdaptiveGrid.AddVertexStrip for adding connected chain of vertices.
- Add AdaptiveGrid.CutEdge for replacing an edge with two new edges that meet at given point.Point.
- Add AdaptiveGrid.ClosestVertex, AdaptiveGrid.ClosestEdge
- Add AdaptiveGrid.RemoveVertex, AdaptiveGrid.AddEdge, AdaptiveGrid.RemoveEdge
- Add PriorityQueue collection into Elements.
- Add AdaptiveGraphRouting into Elements. The only new function it has is BuildSimpleNetwork.

TESTING:
- PriorityQueueTests and AdaptiveGraphRoutingTests were moved together with corresponding files.
- Add a lot of tests to AdaptiveGridTests covering new functions.
  
FUTURE WORK:
- AdaptiveGrid and AdaptiveGraphRouting  are still quite complicated to use. Higher level code is needed to easier handing.
- There are plans to introduce new  features into AdaptiveGrid and AdaptiveGraphRouting

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/794)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
just some spelling and usability notes.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/794#-:-N-Y6cnU37ErcAPU3aIJ:b-hboy5p)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[Elements/src/PriorityQueue.cs, line 9 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Xvva4B5oEqi6UF4C0:-N-Xvva4B5oEqi6UF4C1:bwjbikt) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/PriorityQueue.cs#L9)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// PriorityQueue is a collection that allows to retrieve the item with the lowest
> ```

"allows _you_ to"
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs, line 715 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Y6LGI57YHZP64qkJa:-N-Y6LGI57YHZP64qkJb:b-ljh1o0) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L715)):*
> ```Smalltalk
>         /// <param name="leafVertices">Vertices to connect into the system with extra information attached.</param>
>         /// <param name="exits">Possible exit vertices.</param>
>         /// <param name="hintLines">Collection of lines that routes are attracted to. At least one hint line is required.</param>
> ```

what will the error be if there is no hint line?  can we throw an argument exception to be sure users knows what they did wrong?
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs, line 723 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Y65SuBLeBTpiqdo8_:-N-Y65SvDfoL8kDMeXL1:bmj228o) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L723)):*
> ```Smalltalk
>         {
>             //Excluded vertices includes inlets and vertices in certain distance around these inlets.
>             //Sometimes it's not wanted for routing to go through them.
> ```

"it is not desirable"
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs, line 749 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Y6-OZ6XayQLsN63gA:-N-Y6-OZ6XayQLsN63gB:b-1qres) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L749)):*
> ```Smalltalk
>             var hintVertices = NearbyVertices(userHints, leafVertices);
>             var offsetVertices = NearbyVertices(defaultHints, leafVertices);
>             //Hint lines can go even through excluded vertices
> ```

"can even go through"



_Code quote:_
```Smalltalk
Simple
```
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 328 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-XyPBg8C6Eew-v4tMJ:-N-XyPBg8C6Eew-v4tMK:breqjhu) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L328)):*
> ```Smalltalk
>         /// <summary>
>         /// Create connected chain of vertices. If chain intersects itself - intersection vertices are created as well.
>         /// New vertices are not connected with other vertices, except the case then one or more added vertices already exist in the grid.
> ```

"except _in the case when_ one"
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 330 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-XyZyd94h4KobGvN0u:-N-XyZyd94h4KobGvN0v:bbca4fq) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L330)):*
> ```Smalltalk
>         /// New vertices are not connected with other vertices, except the case then one or more added vertices already exist in the grid.
>         /// </summary>
>         /// <param name="points">List of point to connect by edges. Must have at least two points.</param>
> ```

point _s_
___
*[Elements/src/Spatial/AdaptiveGrid/Vertex.cs, line 31 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Y-6ne5smnMkWxbznA:-N-Y-6nf2OQMTqh0yiK3:b5rzwld) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/Vertex.cs#L31)):*
> ```Smalltalk
>         /// <returns>Edge between this and Vertex with given ID. Null if not found.</returns>
>         public Edge GetEdge(ulong otherId)
>         {
> ```

if user inputs the id of this vertex they will get an edge back, but it won't be what they are expecting.  maybe we error or return null in this case?  there's no edge between a vertex and itself, but this method will return an edge I think.

**Review by DmytroMuravskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/794)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/PriorityQueue.cs, line 9 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Xvva4B5oEqi6UF4C0:-N-YMIXU3PjJvcYe0Znh:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/PriorityQueue.cs#L9)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

"allows _you_ to"
</blockquote></details>

Done.
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs, line 715 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Y6LGI57YHZP64qkJa:-N-YOZyw72Qh-cJhtAeW:b-uz4iaa) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L715)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

what will the error be if there is no hint line?  can we throw an argument exception to be sure users knows what they did wrong?
</blockquote></details>

In this case it's actually not required, but in two other functions I've added throws. Also added Asserts to corresponding tests
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs, line 723 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Y65SuBLeBTpiqdo8_:-N-YOuwqAROcht2FnQz5:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L723)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

"it is not desirable"
</blockquote></details>

Done.
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs, line 749 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Y6-OZ6XayQLsN63gA:-N-YOvrC59FKMxlMc7bz:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L749)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

"can even go through"
</blockquote></details>

Done.
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 328 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-XyPBg8C6Eew-v4tMJ:-N-YMMd48_k5M_ZJJ8ko:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L328)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

"except _in the case when_ one"
</blockquote></details>

Done.
___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs, line 330 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-XyZyd94h4KobGvN0u:-N-YMN9L5AaG3nzaWtJV:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs#L330)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

point _s_
</blockquote></details>

Done.
___
*[Elements/src/Spatial/AdaptiveGrid/Vertex.cs, line 31 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Y-6ne5smnMkWxbznA:-N-YOxHJ40xdFLrbh7s6:boa8vtu) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/Vertex.cs#L31)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

if user inputs the id of this vertex they will get an edge back, but it won't be what they are expecting.  maybe we error or return null in this case?  there's no edge between a vertex and itself, but this method will return an edge I think.
</blockquote></details>

Returned null in this case. My policy is to throw in functions that return id, since Vertex/Edge classes have zero information about what index range of owner container is

**Review by wynged — APPROVED** [review]
one more spelling tweak, but approved!

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/794#-:-N-Z4ZyP7wddhU-93roa:b-22fyjf)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs, line 723 at r1](https://reviewable.io/reviews/hypar-io/elements/794#-N-Y65SuBLeBTpiqdo8_:-N-Z4AoA93dgpvJVNEyG:blhu1o) ([raw file](https://github.com/hypar-io/elements/blob/f4a1c414392c7b4dff766a46c072d6b220cca63e/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L723)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this and the others should be "desirable" I think.

**Review by wynged — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/794)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
