### PR TITLE
Network fixes

### PR DESCRIPTION
**Pull request by katehryhorenko**
BACKGROUND:
- Network didn't work for complex models. The tree was build incorrectly in some cases 

DESCRIPTION:
- LeftMostComparer now sorts elements from the left bottom corner to the top and to the right. Now if one of the axis is the same for too points it compares values by other axis
- Added tolerance to comparation by X axis were requered
- Because of node comparer was broken the wrong element could be removed from the tree
- Now a new node is always added to both nodes that are supposed to be connected with it. Prev. some connections could be lost. And node 4 could "know" about node 2, but node 2 "knows" nothing about node 4.Now this behavior is fixed:

image

TESTING:
- I tested it on a small a big DPR model with huge amount of cases.
  
FUTURE WORK:
- Maybe add more small tests

REQUIRED:
- [ ] All changes are up to date in `CHANGELOG.md`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/890)

### CODE REVIEW

**Review by ikeough — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/890)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/Search/Network.cs` line 182 at r2](https://reviewable.io/reviews/hypar-io/elements/890#-NCa3QFS1lC34jGGtjvw:-NCa3QFTBPE6Bm18gTBe:b-xsp1kj) ([raw file](https://github.com/hypar-io/elements/blob/36f76688df402cb96ffea7012063a730f6593217/Elements/src/Search/Network.cs#L182)):*
> ```Smalltalk
>         }
> 
>         private class XComparer : IComparer<Vector3>
> ```

Maybe we should call this `XEqualityWithFallbackToYEqualityComparer`
___
*[`Elements/src/Search/Network.cs` line 245 at r2](https://reviewable.io/reviews/hypar-io/elements/890#-NCa4Jtz9nHt8NsXkv9h:-NCa4Jtz9nHt8NsXkv9i:b-7my8yv) ([raw file](https://github.com/hypar-io/elements/blob/36f76688df402cb96ffea7012063a730f6593217/Elements/src/Search/Network.cs#L245)):*
> ```Smalltalk
>                 return new LineSweepEvent<T>(g.Key, g.Select(e => (e.index, e.isLeftMost, e.item)));
>             });
>             events = events.OrderBy(e => -e.Point.Y);
> ```

Is splitting these out into separate lines just a readability thing? Or is there something more that I'm missing?
___
*[`Elements/src/Search/Network.cs` line 283 at r2](https://reviewable.io/reviews/hypar-io/elements/890#-NCa4y7K-k1rnoyGigOn:-NCa4y7L0F_0PpZNlPSe:butkzpd) ([raw file](https://github.com/hypar-io/elements/blob/36f76688df402cb96ffea7012063a730f6593217/Elements/src/Search/Network.cs#L283)):*
> ```Smalltalk
>                                 if (s.Intersects(getSegment(pre.Data), out Vector3 result, includeEnds: true))
>                                 {
>                                     if (!segmentIntersections[data].Any(p => p.IsAlmostEqualTo(result)) && s.PointOnLine(result))
> ```

We re-use this block of code a lot here. Can we convert it to a method like `PointIsUniqueIntersectionAlongLine(...)` and use that everywhere?
___
*[`Elements/src/Search/Network.cs` line 366 at r2](https://reviewable.io/reviews/hypar-io/elements/890#-NCa5c7E-hmhiSIGStdT:-NCa5c7E-hmhiSIGStdU:bvooerm) ([raw file](https://github.com/hypar-io/elements/blob/36f76688df402cb96ffea7012063a730f6593217/Elements/src/Search/Network.cs#L366)):*
> ```Smalltalk
>                         }
> 
>                         if (tree.Find(data) != null && tree.Find(data).Data.Equals(data))
> ```

We need a note here about what is going on. 
___
*[`Elements/test/NetworkTests.cs` line 303 at r2](https://reviewable.io/reviews/hypar-io/elements/890#-NCa5m9S9kfKIB_f25TK:-NCa5m9S9kfKIB_f25TL:b-2xawbt) ([raw file](https://github.com/hypar-io/elements/blob/36f76688df402cb96ffea7012063a730f6593217/Elements/test/NetworkTests.cs#L303)):*
> ```Smalltalk
>         }
> 
>         [Fact]
> ```

We need one small test that exercises the specific fix. I get the sense that this change solves for vertical lines and for multiple intersections along a segment in the same location. Can we make tiny tests for both of those (and whatever other cases this might be fixing?

The integration test from Revit data is great, we just don't get insight into why the model it's testing is problematic.

**Comment by ikeough** [comment]
@katehryhorenko I updated this with master and made just one small change. This PR helps with some other work that I'm doing so I'd really like to get it in!

**Review by katehryhorenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/890)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements/src/Search/Network.cs` line 182 at r2](https://reviewable.io/reviews/hypar-io/elements/890#-NCa3QFS1lC34jGGtjvw:-NEaEto_3h2NhptydyGk:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/36f76688df402cb96ffea7012063a730f6593217/Elements/src/Search/Network.cs#L182)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Maybe we should call this `XEqualityWithFallbackToYEqualityComparer`
</blockquote></details>

Done.
___
*[`Elements/src/Search/Network.cs` line 283 at r2](https://reviewable.io/reviews/hypar-io/elements/890#-NCa4y7K-k1rnoyGigOn:-NEaH0Xw-2jn0mIsP0wO:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/36f76688df402cb96ffea7012063a730f6593217/Elements/src/Search/Network.cs#L283)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

We re-use this block of code a lot here. Can we convert it to a method like `PointIsUniqueIntersectionAlongLine(...)` and use that everywhere?
</blockquote></details>

Done.
___
*[`Elements/src/Search/Network.cs` line 366 at r2](https://reviewable.io/reviews/hypar-io/elements/890#-NCa5c7E-hmhiSIGStdT:-NEaIEmA-1TQ2ckg_uLX:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/36f76688df402cb96ffea7012063a730f6593217/Elements/src/Search/Network.cs#L366)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

We need a note here about what is going on. 
</blockquote></details>

Done.

**Review by ikeough — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/890)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @katehryhorenko)

**Pull request merged**
