### PR TITLE
Mitigate abnormally generated areas

### PR DESCRIPTION
**Pull request by jamesbradleym**
BACKGROUND:
- Polygon.Area() unexpectedly returned a negative area, turns out Polygon.Area() returns a signed area which some may find confusing.

DESCRIPTION:
- Adds a bool signed = false default parameter to the Area function.
- Polygon.Area() now returns a signed (signed=true) or magnitude area (signed=false)

TESTING:
- Create a Polygon and check Polygon.Area value
  
FUTURE WORK:

REQUIRED:
- [ ] All changes are up to date in `CHANGELOG.md`.

COMMENTS:

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989)

### CODE REVIEW

**Comment by andrewheumann** [comment]
Just want to make sure @ikeough doesn't have any objections to this change (and folding it as an additional breaking change into 2.0)

**Review by jamesbradleym — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[`Elements/src/Geometry/Polygon.cs` line 2169 at r1](https://reviewable.io/reviews/hypar-io/Elements/989#-NZf4PnbAdMCJL5Ygmfx:-NZfUmTM18hWLO4kmIkw:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/f77943131c1cd3ec413990d08f570d612f731229/Elements/src/Geometry/Polygon.cs#L2169)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

missing a comment for the `signed` parameter.
</blockquote></details>

Done.

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Make sure to update the "changed" section of `CHANGELOG.md` with something like "Polygon.Area() now returns an unsigned area by default, and accepts a `signed` parameter to preserve the previous behavior."

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989#-:-NZfVrTlAbJwuoVWP4BU:blc1flw)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @jamesbradleym)

___
*[`Elements/src/Geometry/Polygon.cs` line 2169 at r1](https://reviewable.io/reviews/hypar-io/Elements/989#-NZf4PnbAdMCJL5Ygmfx:-NZfVAOjE9U_mb9TMg0i:b-pvxsfe) ([raw file](https://github.com/hypar-io/Elements/blob/f77943131c1cd3ec413990d08f570d612f731229/Elements/src/Geometry/Polygon.cs#L2169)):*
gonna be fussy and propose:
> "If true, a counter-clockwise polygon will yield a positive area, while a clockwise polygon will give a negative area." or something like that. but LGTM!

**Review by andrewheumann — COMMENTED** [review]
Just a ping, I think we want to get this in for the 2.0 release

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989#-:-N_8jbM020ftmpgxnCT_:bdu416s)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @jamesbradleym)

**Review by andrewheumann — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by andrewheumann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Some tests are failing. There may have been code in the library that depended on the signed area behavior which is now breaking.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989#-:-N_A_Z_gEgiRDS3AiSqc:bclc230)* status: 1 change requests, 0 of 1 approvals obtained

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Also, there are many places in the code that call `Math.Abs({something}.Area())`. The .Abs calls are no longer needed and may be removed.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989#-:-N_AaKLL1TjyYFKcyJyB:b-5owj88)* status: 1 change requests, 0 of 1 approvals obtained

**Review by jamesbradleym — COMMENTED** [review]
Went through the tests and found that one of the Mesh Volume tests anticipated an area to be signed negative as it was a boolean mesh. The test itself is validating whether or not the Mesh.Volume() value is accurate, what are your thoughts on including another test for Polygon.Area(true) for signed areas?

Went through the code and removed Math.Abs() that wrapped Polygon.Area()

> Reviewed 2 of 2 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989#-:-N_CLWF19itXQeRrXYXG:b-rlqpg5)* status: 1 change requests, 0 of 1 approvals obtained

**Review by jamesbradleym — COMMENTED** [review]
var c = Polygon.Rectangle(3.0, 2.0);
Assert.Equal(-6.0, c.Reversed().Area(true));

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989#-:-N_CN-Fa2oQiligrXvGb:b-rinzif)* status: 1 change requests, 0 of 1 approvals obtained

**Review by andrewheumann — APPROVED** [review]
Feel free to add that test if you feel like it! but this :lgtm: 

> Reviewed 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/989#-:-N_Iwb875bkGG9UesVAX:b-9wvkoc)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
