### PR TITLE
Cell complex utility transversals

### PR DESCRIPTION
**Pull request by serenayl**
BACKGROUND:
- I needed a few transversal functions for CellComplex, and the other PR is nearing completion so this is being submitted separately

DESCRIPTION:
- Adds `TraversedNeighbors` method to Cell, Edge, and Face, where it loops through the neighbors and returns to you the final path as a list.
- Updated tests to use this function and not require their own loops.

TESTING:
- See the updated tests and try using `TraversedNeighbors`.
  
FUTURE WORK:
- It would be nice in the future to have neighbor traversal that handles multiple available paths and does things like obstruction avoidance.

REQUIRED:
- [ ] All changes are up to date in `CHANGELOG.md`. (did not add to changelog, this is a follow-on to an unmerged PR)

COMMENTS:
- Traversed Cells currently includes the original cell we call the function on. If this doesn't make sense, this can be modified.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/566)

### CODE REVIEW

**Review by ikeough — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/566)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @serenayl)

___
*[Elements/src/Spatial/CellComplex/Cell.cs, line 238 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYdCR52lJ56BYC6SIZ:-MXYdCR52lJ56BYC6SI_:b-bobbo4) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/Cell.cs#L238)):*
> ```Smalltalk
>         /// <param name="completedRadius">If provided, ends the traversal when the neighbor is within this distance to the target point.</param>
>         /// <returns></returns>
>         public List<Cell> TraversedNeighbors(Vector3 point, double completedRadius = 0)
> ```

I recommend calling this `TraverseNeighbors` and changing `point` to `target`. This will align the method name and parameters with the description. Then in the `returns` block, you can say. "A collection of traversed cells."

I'm a fan of naming a method for what it _does_ instead of what it _returns_, although I'm sure we break this rule elsewhere.
___
*[Elements/src/Spatial/CellComplex/ChildBase.cs, line 10 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYda8u5qIb9I_pKGH3:-MXYda8u5qIb9I_pKGH4:b9v8qf3) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/ChildBase.cs#L10)):*
> ```Smalltalk
>     /// <summary>
>     /// An abstract base for ChildBase that does not contain the geometry constraints.
>     /// Do not inherit from this directly, always use the geometry constraints.
> ```

Is there a way we can use the mechanisms of C# to enforce this? Perhaps `sealed`? https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/sealed

The name `ChildBase` leads me to believe that this is the base class, but the description says that it's the abstract base for `ChildBase`? After reading further I see that you have two classes called `ChildBase`, one with a generic type parameter. This is confusing because "ChildBase" is pretty generic, then you have another class called the same thing. What's the base problem that this split is trying to solve?
___
*[Elements/src/Spatial/CellComplex/Edge.cs, line 172 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYhWDk7GgG8IQwuchf:-MXYhWDk7GgG8IQwuchg:b-it8owb) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/Edge.cs#L172)):*
> ```Smalltalk
>         /// <param name="completedRadius">If provided, ends the traversal when the neighbor is within this distance to the target point.</param>
>         /// <returns></returns>
>         public List<Edge> TraversedNeighbors(Vector3 point, double completedRadius = 0)
> ```

Same as above "TraverseNeighbors"...
___
*[Elements/src/Spatial/CellComplex/Face.cs, line 264 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYhE3cCYqZv_9TZ5n7:-MXYhE3d-U7Zf_DHedU7:b-iqjgt1) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/Face.cs#L264)):*
> ```Smalltalk
>         /// <param name="completedRadius">If provided, ends the traversal when the neighbor is within this distance to the target point.</param>
>         /// <returns></returns>
>         public List<Face> TraversedNeighbors(Vector3 point, bool parallel = false, bool includeSharedVertices = false, double completedRadius = 0)
> ```

Similar to above, I'd call this `TraverseNeighbors` and edit the `returns` block to say "A collection of traversed faces."
___
*[Elements/test/CellComplexTests.cs, line 193 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYf_uZ3EN0OF-zV4J5:-MXYf_uZ3EN0OF-zV4J6:byxh3w2) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/test/CellComplexTests.cs#L193)):*
> ```Smalltalk
> 
>         [Fact]
>         public void CellComplexTraversal()
> ```

This method has a number of assertions in it. Some people are religious about having only one assertion per test method. I won't go that far, but it would be nice to have more discrete tests like "CanTraverseCells" and "CanTraverseFaces".
___
*[Elements/test/CellComplexTests.cs, line 199 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYeaJ78YOGcEZP874Q:-MXYeaJ78YOGcEZP874R:bi94xk6) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/test/CellComplexTests.cs#L199)):*
> ```Smalltalk
>             var cellComplex = MakeASimpleCellComplex(numLevels: 10, uNumCells: 5, vNumCells: 10);
> 
>             var bigNumber = 100000;
> ```

Is it possible to make this const name more meaningful? I also recommend making it `public const double BIG_NUMBER = 100000` at the top of the file.

**Review by serenayl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/566)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/src/Spatial/CellComplex/Cell.cs, line 238 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYdCR52lJ56BYC6SIZ:-MXhs66k-HZVM0u8ab7t:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/Cell.cs#L238)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I recommend calling this `TraverseNeighbors` and changing `point` to `target`. This will align the method name and parameters with the description. Then in the `returns` block, you can say. "A collection of traversed cells."

I'm a fan of naming a method for what it _does_ instead of what it _returns_, although I'm sure we break this rule elsewhere.
</blockquote></details>

Done.
___
*[Elements/src/Spatial/CellComplex/ChildBase.cs, line 10 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYda8u5qIb9I_pKGH3:-MXhs9Oo2JH2Uos-z3Ei:blwaonk) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/ChildBase.cs#L10)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Is there a way we can use the mechanisms of C# to enforce this? Perhaps `sealed`? https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/sealed

The name `ChildBase` leads me to believe that this is the base class, but the description says that it's the abstract base for `ChildBase`? After reading further I see that you have two classes called `ChildBase`, one with a generic type parameter. This is confusing because "ChildBase" is pretty generic, then you have another class called the same thing. What's the base problem that this split is trying to solve?


</blockquote></details>

As an example, I'm not sure how else to type this method, where the <GeometryType> doesn't really matter?

```
        internal static T GetClosest<T>(List<T> candidates, Vector3 point) where T : ChildBase
        {
            if (candidates.Count == 0)
            {
                return null;
            }
            return candidates.OrderBy(c => c.DistanceTo(point)).ToList()[0];
        }
```
___
*[Elements/src/Spatial/CellComplex/Edge.cs, line 172 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYhWDk7GgG8IQwuchf:-MXhqD3wAc2-neFhBzm0:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/Edge.cs#L172)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Same as above "TraverseNeighbors"...
</blockquote></details>

Done.
___
*[Elements/src/Spatial/CellComplex/Face.cs, line 264 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYhE3cCYqZv_9TZ5n7:-MXhqByV96OQY9mhkrZ4:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/Face.cs#L264)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Similar to above, I'd call this `TraverseNeighbors` and edit the `returns` block to say "A collection of traversed faces."
</blockquote></details>

Done.
___
*[Elements/test/CellComplexTests.cs, line 193 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYf_uZ3EN0OF-zV4J5:-MXhpEWF7YPxX3EHT8BU:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/test/CellComplexTests.cs#L193)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

This method has a number of assertions in it. Some people are religious about having only one assertion per test method. I won't go that far, but it would be nice to have more discrete tests like "CanTraverseCells" and "CanTraverseFaces".
</blockquote></details>

Done.
___
*[Elements/test/CellComplexTests.cs, line 199 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYeaJ78YOGcEZP874Q:-MXhpF-cBtBuhP7-nGeZ:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/test/CellComplexTests.cs#L199)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Is it possible to make this const name more meaningful? I also recommend making it `public const double BIG_NUMBER = 100000` at the top of the file. 
</blockquote></details>

Done.

**Review by ikeough — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/566)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @serenayl)

___
*[Elements/src/Spatial/CellComplex/ChildBase.cs, line 10 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYda8u5qIb9I_pKGH3:-Ma0Z-bjBhc27WoRR4nR:b-2ntiqf) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/ChildBase.cs#L10)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

As an example, I'm not sure how else to type this method, where the <GeometryType> doesn't really matter?

```
        internal static T GetClosest<T>(List<T> candidates, Vector3 point) where T : ChildBase
        {
            if (candidates.Count == 0)
            {
                return null;
            }
            return candidates.OrderBy(c => c.DistanceTo(point)).ToList()[0];
        }
```
</blockquote></details>

In this example, is `T` a `Vector3`? What else would `T` ever be? An edge or a face? If you want to constrain the method to only use types that are measurable in some way, I'd use an interface. You could call it something like `IMeasureDistanceTo` and make all of your cell complex types implement the interface. Then do `where T: IMeasureDistanceTo`.

**Review by serenayl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/566)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/src/Spatial/CellComplex/ChildBase.cs, line 10 at r1](https://reviewable.io/reviews/hypar-io/elements/566#-MXYda8u5qIb9I_pKGH3:-MadMF9z8A2J6-XfFX-5:b74nlli) ([raw file](https://github.com/hypar-io/elements/blob/3e2af2381d7d3b6c45510a1ea7727df0c7ced3ac/Elements/src/Spatial/CellComplex/ChildBase.cs#L10)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

In this example, is `T` a `Vector3`? What else would `T` ever be? An edge or a face? If you want to constrain the method to only use types that are measurable in some way, I'd use an interface. You could call it something like `IMeasureDistanceTo` and make all of your cell complex types implement the interface. Then do `where T: IMeasureDistanceTo`.
</blockquote></details>

I think I either fixed this or overcomplicated it. But there is only one `ChildBase` class now with the generic attached. It is now requiring a second generic, which is the specific inherited class itself: this is allowing me to specify when I want the return types to be the same as the class that is calling them.

**Pull request merged**
