### PR TITLE
Updated Intersection method to support multiple representations

### PR DESCRIPTION
**Pull request by katehryhorenko**
BACKGROUND:
- _bounds and _csg are used by GeometricElement.Intersection method. Both this variables are calculated from SolidOperations. So currently Intersection  method ignores RepresentationInstances

DESCRIPTION:
This PR adds:
- CalculateIntersactionPoints and ComputeBounds to the SolidRepresentation. It's a duplicated code from the GeometricElement.
- SolidRepresentations are added to the Bounds calculations and to the Intersections

TESTING:
- I tested it with SVGSection method
  
FUTURE WORK:
- Add other Representation types to the calculations

REQUIRED:
- [ ] All changes are up to date in `CHANGELOG.md`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1034)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Looks good! can we add a test or two? 

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1034#-:-NfrRtdiBgsXMvb55jkM:b56lj63)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/Representations/SolidRepresentation.cs` line 150 at r1](https://reviewable.io/reviews/hypar-io/Elements/1034#-NfrRRBW8tI0C0PuF4g4:-NfrRRBW8tI0C0PuF4g5:b-9wgmat) ([raw file](https://github.com/hypar-io/Elements/blob/ff3f03b42abc6462c685936defb8e254fd3bd53a/Elements/src/Representations/SolidRepresentation.cs#L150)):*
> ```Smalltalk
>         /// <param name="beyondPolygons">The output collection of the polygons beyond the input plane.</param>
>         /// <returns>Returns the collection of intersection points.</returns>
>         public List<Vector3> CalculateIntersactionPoints(GeometricElement element, Plane plane, out List<Polygon> beyondPolygons)
> ```

`CalculateIntersactionPoints` => `CalculateIntersectionPoints` :) 
___
*[`Elements/src/Representations/SolidRepresentation.cs` line 157 at r1](https://reviewable.io/reviews/hypar-io/Elements/1034#-NfrRaSK1GvhZIZGBPMH:-NfrRaSL9paM-P0wnEk-:b-aitoin) ([raw file](https://github.com/hypar-io/Elements/blob/ff3f03b42abc6462c685936defb8e254fd3bd53a/Elements/src/Representations/SolidRepresentation.cs#L157)):*
> ```Smalltalk
>             var csg = SolidOperationUtils.GetFinalCsgFromSolids(SolidOperations, element, true);
> 
>             var localCsg = csg.Transform(element.Transform.ToMatrix4x4()); ;
> ```

lose extra `;` here

**Review by andrewheumann — COMMENTED** [review]
And update changelog :smile: 

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1034#-:-NfrS-niBPlyhj6VBTLU:b-l1e7pz)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

**Review by katehryhorenko — COMMENTED** [review]
I added two tests :)

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1034#-:-Ng0_IdZ5lZs7BtXPQxB:b2oioqm)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[`Elements/src/Representations/SolidRepresentation.cs` line 150 at r1](https://reviewable.io/reviews/hypar-io/Elements/1034#-NfrRRBW8tI0C0PuF4g4:-Ng0_DIa9rnwwobi2OJN:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/ff3f03b42abc6462c685936defb8e254fd3bd53a/Elements/src/Representations/SolidRepresentation.cs#L150)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

`CalculateIntersactionPoints` => `CalculateIntersectionPoints` :)
</blockquote></details>

Done.
___
*[`Elements/src/Representations/SolidRepresentation.cs` line 157 at r1](https://reviewable.io/reviews/hypar-io/Elements/1034#-NfrRaSK1GvhZIZGBPMH:-Ng0_Gkg-KCwguATTZgA:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/ff3f03b42abc6462c685936defb8e254fd3bd53a/Elements/src/Representations/SolidRepresentation.cs#L157)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

lose extra `;` here
</blockquote></details>

Done.

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1034)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/GeometricElement.cs` line 263 at r2](https://reviewable.io/reviews/hypar-io/Elements/1034#-Ng3JqMMCwDBcSOKV4Bk:-Ng3JqMNA_wOl8Ijt8G_:b-y7k54a) ([raw file](https://github.com/hypar-io/Elements/blob/32891ba03c904248341bb5b4759b82d4985ae962/Elements/src/GeometricElement.cs#L263)):*
> ```Smalltalk
>                 foreach (var instance in RepresentationInstances)
>                 {
>                     if (!instance.IsDefault)
> ```

can we leave a TODO here about potentially accepting a representation type filter as input?
___
*[`Elements/test/GeometricElementTests.cs` line 89 at r2](https://reviewable.io/reviews/hypar-io/Elements/1034#-Ng3J86k9b65s8zl3HCP:-Ng3J86k9b65s8zl3HCQ:bxwouya) ([raw file](https://github.com/hypar-io/Elements/blob/32891ba03c904248341bb5b4759b82d4985ae962/Elements/test/GeometricElementTests.cs#L89)):*
> ```Smalltalk
>             var width = 10;
>             var height = 10;
>             var hhickness = 0.2;
> ```

hhickness => thickness

**Review by katehryhorenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1034)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[`Elements/src/GeometricElement.cs` line 263 at r2](https://reviewable.io/reviews/hypar-io/Elements/1034#-Ng3JqMMCwDBcSOKV4Bk:-Ng3tGDU8yI-scKVcak-:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/32891ba03c904248341bb5b4759b82d4985ae962/Elements/src/GeometricElement.cs#L263)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

can we leave a TODO here about potentially accepting a representation type filter as input?
</blockquote></details>

Done.
___
*[`Elements/test/GeometricElementTests.cs` line 89 at r2](https://reviewable.io/reviews/hypar-io/Elements/1034#-Ng3J86k9b65s8zl3HCP:-Ng3tFpH3blJUNljFN5h:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/32891ba03c904248341bb5b4759b82d4985ae962/Elements/test/GeometricElementTests.cs#L89)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

hhickness => thickness
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1034)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
