### PR TITLE
Ifc serialization improvements

### PR DESCRIPTION
**Pull request by srudenkoamc**
BACKGROUND:
- IFC serialization needs improvement.

DESCRIPTION:
- Massive refactoring of IFC serialization.
- Changes from https://github.com/hypar-io/Elements/pull/531 are included.
- Recognition of core Hypar Element types from original IFC serialization is preserved.
- Added fallback conversion to GeometricElement in case if IfcBuildingElement is not supported.

FUTURE WORK
- Representations extraction should be revised after multiple representations concept implementation.
- For the most types only extrude and mapped representations are supported. But each IFC type supports it's own list of Geometric Representations. They may get support in the future.
- Each IfcRepresentationItem has it's own maretial, but Element can have only one material. It may change after multiple representations concept is implemented.
- There are many door operation types that aren't supported now.
- IFC property sets and IFC quantity sets may be used for extraction of some properties.
- IfcBooleanClippingResultParser doesn't apply boolean clipping operation.
- German names aren't extracted properly (see 'AC20-Institute-Var-2.ifc' for example).
- IFC files for "rac_sample" and "rme_sample" tests cannot be read because of some errors during file parsing in Document class.
- The original representation of an object won't be preserved, if it is converted to one of the core types (not Geometric Element). Instead the representation from 'UpdateRepresentation()' method will be used.

TESTING:
- Existing tests are improved in order to observe the effect of changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021)

### CODE REVIEW

**Review by anthonie-kramer — COMMENTED** [review]
Everything looks good. I did some testing, and found a bug with the current version of the Hypar.IFC4 package, so I'm working on an update to downgrade it to `net6.0`, since we don't use `net7.0` anywhere else. Would like to get that working before we merge this work in.

The code is here if you want to take a look at it. Feel free to review and make any other suggestions that would be helpful for these changes before I publish a new Nuget package!

https://github.com/hypar-io/IFC-gen

> Reviewed 4 of 19 files at r2, 5 of 36 files at r5, 4 of 19 files at r6, 1 of 22 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021#-:-NhAIHOpDS9fQnqGIODA:b43mk04)* status: 0 of 1 approvals obtained

**Review by DmytroMuravskyi — COMMENTED** [review]
> Reviewed 1 of 19 files at r2, 13 of 36 files at r5, 5 of 19 files at r6, 1 of 3 files at r8, 19 of 22 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021)* status: 0 of 1 approvals obtained (waiting on @srudenkoamc)

___
*[`Elements/src/Utilities/SolidOperationUtils.cs` line 101 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBQzYj1g5duxsV3kb2:-NhBQzYj1g5duxsV3kb3:b-vb47yz) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements/src/Utilities/SolidOperationUtils.cs#L101)):*
> ```Smalltalk
>             if (voids.Count == 1 && solids.Count == 0)
>             {
>                 csg = voids.First();
> ```

Make sure that this is used for subtraction.
___
*[`Elements.Serialization.IFC/src/IFCToHypar/Converters/FromIfcDoorConverter.cs` line 66 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBIUOr5tJlKjYzX045:-NhBIUOr5tJlKjYzX046:b7ewaes) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/Converters/FromIfcDoorConverter.cs#L66)):*
> ```Smalltalk
>             var matchingWalls = allWalls.Where(w => w.Id.Equals(IfcGuid.FromIfcGUID(ifcWall.GlobalId)));
> 
>             return matchingWalls.Any() ? matchingWalls.First() : null;
> ```

FirstOrDefault()
___
*[`Elements.Serialization.IFC/src/IFCToHypar/RepresentationsExtraction/MaterialExtractor.cs` line 73 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBMPch6b8EJ80vssww:-NhBMPch6b8EJ80vsswx:b-611yun) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/RepresentationsExtraction/MaterialExtractor.cs#L73)):*
> ```Smalltalk
> 
>                                 Material material;
>                                 if (!MaterialByName.ContainsKey(name))
> ```

TryGetValue
___
*[`Elements.Serialization.IFC/src/IFCToHypar/FromIfcModelProvider.cs` line 119 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhB9a46BtjFcP-5eVbK:-NhB9a46BtjFcP-5eVbL:bsx4wr0) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/FromIfcModelProvider.cs#L119)):*
> ```Smalltalk
>                 {
>                     _constructionErrors.Add(ex.Message);
>                     continue;
> ```

Looks like this continue can be removed.
___
*[`Elements.Serialization.IFC/src/IFCToHypar/FromIfcModelProvider.cs` line 150 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBCz_L7EDjf4wFK2EC:-NhBCz_L7EDjf4wFK2ED:b-fh9c3) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/FromIfcModelProvider.cs#L150)):*
> ```Smalltalk
>                 // - Idea: Make PropertySet an Element. PropertySets can store type properties.
>                 GeometricElement definition;
>                 if (_elementDefinitions.ContainsKey(repData.MappingInfo.MappingId))
> ```

if(!TryGetValue()) is better here
___
*[`Elements.Serialization.IFC/src/IFCToHypar/FromIfcModelProvider.cs` line 197 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhB9wXV50bCUiN_llFY:-NhB9wXV50bCUiN_llFZ:bx1pg5j) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/FromIfcModelProvider.cs#L197)):*
> ```Smalltalk
>             {
>                 var ifcElement = _elementToIfcProduct[elementWithOpenings];
>                 var ifcOpeningElements = ifcOpenings.Where(v => v.RelatingBuildingElement == ifcElement)
> ```

Looks like all ToList can be removed in this function as Linq can just chain together.
___
*[`Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs` line 59 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBDrZEAHDQSUpVS7z4:-NhBDrZEAHDQSUpVS7z5:b-5ac0cx) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs#L59)):*
> ```Smalltalk
>             var extrudes = opening.RepresentationsOfType<IfcExtrudedAreaSolid>().ToList();
> 
>             if (extrudes?.Count == 0)
> ```

If extrudes is null return will not happen  and next foreach with throw. It needs either != null or remove ? to show that null is not expected here.
___
*[`Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs` line 163 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBGCAk7PtSpvH-khW6:-NhBGCAk7PtSpvH-khW7:bc067n3) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs#L163)):*
> ```Smalltalk
>             {
>                 var p = Polygon.Rectangle((IfcLengthMeasure)rect.XDim, (IfcLengthMeasure)rect.YDim);
>                 var t = new Transform(rect.Position.Location.ToVector3());
> ```

Why here transform applied but not in other places? Why IfcCircleProfileDef is created as Circle here but as Polygon above?
___
*[`Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs` line 241 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBGUOg8aLGutslQq9R:-NhBGUOg8aLGutslQq9S:b-ya81ng) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs#L241)):*
> ```Smalltalk
>             {
>                 var p = Polygon.Rectangle((IfcLengthMeasure)rect.XDim, (IfcLengthMeasure)rect.YDim);
>                 var t = new Transform(rect.Position.Location.ToVector3());
> ```

Same as above
___
*[`Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs` line 314 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBGvUeA7_EYXhn9wTj:-NhBGvUeA7_EYXhn9wTk:b-85iwog) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs#L314)):*
> ```Smalltalk
>                         foreach (IfcInteger segmentIndex in (List<IfcPositiveInteger>)ai)
>                         {
>                             segmentIndices.Add(segmentIndex - 1);
> ```

Note that we support exactly 2 indices for line and 3 for arc.
___
*[`Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs` line 378 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBIA3eBmz5K9JuhV7j:-NhBIA3fB5C_r97pgHl2:brzer49) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs#L378)):*
> ```Smalltalk
>             for (var i = 0; i < point.Coordinates.Count; i++)
>             {
>                 if (point.Coordinates[i] != other.Coordinates[i])
> ```

If coordinates are floating point - there can be risk of misinterpreting two points as different.
___
*[`Elements.Serialization.IFC/src/IFCToHypar/Converters/FromIfcSpaceConverter.cs` line 41 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBJeVUCbf_4ZpzT4J6:-NhBJeVUCbf_4ZpzT4J7:be7abgh) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/Converters/FromIfcSpaceConverter.cs#L41)):*
> ```Smalltalk
>             }
> 
>             var solid = repData.SolidOperations.First()?.Solid;
> ```

First() throws if no items, use FirstOrDefault()

**Review by DmytroMuravskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021)* status: 0 of 1 approvals obtained (waiting on @srudenkoamc)

___
*[`Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs` line 93 at r10](https://reviewable.io/reviews/hypar-io/Elements/1021#-NhBR7eyDHRoB6WmeJnF:-NhBFGaR06UvRgYnovd6:b-93tchu) ([raw file](https://github.com/hypar-io/Elements/blob/02d90392890340d72493a456a88f50c2aa336c7a/Elements.Serialization.IFC/src/IFCToHypar/IFCExtensions.cs#L93)):*
> ```Smalltalk
>         }
> 
>         // private static IfcOpeningElement ToIfcOpeningElement(this Opening opening, IfcRepresentationContext context, Document doc, IfcObjectPlacement parent)
> ```

Is whole commented function needed?

**Review by anthonie-kramer — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r10, 6 of 7 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @srudenkoamc)

___
*[`Elements/src/Door.cs` line 86 at r13](https://reviewable.io/reviews/hypar-io/Elements/1021#-NibEoqWD8kQbWz6fTzn:-NibEoqWD8kQbWz6fTzo:byjin0c) ([raw file](https://github.com/hypar-io/Elements/blob/b969133e9ef514e754dedd08c4264c94954042d5/Elements/src/Door.cs#L86)):*
> ```Smalltalk
>             Representation = representation ?? new Representation(new List<SolidOperation>() { });
>             Opening = new Opening(Polygon.Rectangle(width, height), depthFront, depthBack, GetOpeningTransform());
>             Id = id != default ? id : Guid.NewGuid();
> ```

was this due to a serialization issue? I believe we can also create an empty constructor which may also fix the serialization issues with newtonsoft

**Comment by srudenkoamc** [comment]
> > Reviewed 1 of 22 files at r10, 6 of 7 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021)_ status: 1 change requests, 0 of 1 approvals obtained (waiting on @srudenkoamc)
> 
> _[`Elements/src/Door.cs` line 86 at r13](https://reviewable.io/reviews/hypar-io/Elements/1021#-NibEoqWD8kQbWz6fTzn:-NibEoqWD8kQbWz6fTzo:byjin0c) ([raw file](https://github.com/hypar-io/Elements/blob/b969133e9ef514e754dedd08c4264c94954042d5/Elements/src/Door.cs#L86)):_
> 
> > ```smalltalk
> >             Representation = representation ?? new Representation(new List<SolidOperation>() { });
> >             Opening = new Opening(Polygon.Rectangle(width, height), depthFront, depthBack, GetOpeningTransform());
> >             Id = id != default ? id : Guid.NewGuid();
> > ```
> 
> was this due to a serialization issue? I believe we can also create an empty constructor which may also fix the serialization issues with newtonsoft

This is a fix for a situation when a door has the default Guid instead of a generated one when a Guid isn't specified in the constructor parameters. The fix for the serialization issue is in the another PR (https://github.com/hypar-io/Elements/pull/1050).

**Review by anthonie-kramer — APPROVED** [review]
@srudenkoamc I have updated the IFC Nuget package so we should be good to finish this PR... Let me know when it's ready to go!

> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021#-:-NigNVHM0tRygHs05t4c:b-n2900m)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @srudenkoamc)

**Review by anthonie-kramer — APPROVED** [review]
:LGTM: ... It looks like all the comments were addressed... If there are no more updates I will merge!

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021#-:-NigO_9P5ZfnOhPXPhkC:b-6m2bjm)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @srudenkoamc)

**Comment by srudenkoamc** [comment]
> :LGTM: ... It looks like all the comments were addressed... If there are no more updates I will merge!
> 
> > _[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021#-:-NigO_9P5ZfnOhPXPhkC:b-6m2bjm)_ status: :shipit: complete! 1 of 1 approvals obtained (waiting on @srudenkoamc)

No updates from me. The changes may be merged.

**Review by anthonie-kramer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @srudenkoamc)

**Review by anthonie-kramer — APPROVED** [review]
> Reviewed 1 of 19 files at r2, 8 of 36 files at r5, 1 of 19 files at r6, 1 of 3 files at r8, 15 of 22 files at r10.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1021)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @srudenkoamc)

**Pull request merged**
