### PR TITLE
update revit docs for new converter

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- New Revit addin is being released, and the docs should be updated to reflect it.

DESCRIPTION:
- Update readme, and reference the soon to be published videos/converter sample library

TESTING:
- view readme locally if desired.
  
FUTURE WORK:
- Continued maintenance as docs and addin improve.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/393)

### CODE REVIEW

**Review by anthonyhauck — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/393)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @anthonyhauck, @ikeough, and @wynged)

___
*[doc/Revit.md, line 34 at r1](https://reviewable.io/reviews/hypar-io/elements/393#-MItU4TrDZm974HEWonP:-MItU4TrDZm974HEWonQ:b-hqqema) ([raw file](https://github.com/hypar-io/elements/blob/22f83533afdf06360c8733e16f78ab904038190e/doc/Revit.md#L34)):*
> ```Markdown
> 
> # Converting Revit to and from Hypar
> The conversion process is designed so anyone using the Elements library can add their own custom converters that will be run by the addin.  For more information about writing Element Converters refer to the 
> ```

This text just seems to stop.

**Review by anthonyhauck — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/393)* status: all files reviewed, 1 unresolved discussion (waiting on @ikeough and @wynged)

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/393)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @anthonyhauck and @ikeough)

___
*[doc/Revit.md, line 34 at r1](https://reviewable.io/reviews/hypar-io/elements/393#-MItU4TrDZm974HEWonP:-MItiDZDB6X8t76G3RMb:b-8aj4mk) ([raw file](https://github.com/hypar-io/elements/blob/22f83533afdf06360c8733e16f78ab904038190e/doc/Revit.md#L34)):*
<details><summary><i>Previously, anthonyhauck (Anthony Hauck) wrote…</i></summary><blockquote>

This text just seems to stop.
</blockquote></details>

OK, I've finished the thought.

**Review by anthonyhauck — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ikeough)

**Pull request merged**
