### PR TITLE
Skip tessellation and merge vertices during CSG output.

### PR DESCRIPTION
**Pull request by ikeough**
BACKGROUND:
There are a number of places in our glTF export code where we unnecessarily tesselate CSG polygons. This is slow. We also don't merge vertices during export leading to a jagged appearance of most geometry.

DESCRIPTION:
This PR skips tessellating CSG polygons except when completely necessary, and uses the Octree introduced in a previous PR to enable fast merging of vertices. This results in near equivalent time CSG output and lower memory usage both during CSG writes and for the exported glTF.

For our test which generates beams with every HSS section and exports the results to glTF, the results are as follows.

|                  Method |     Mean |    Error |   StdDev |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |.   File Size|
|------------------------ |---------:|---------:|---------:|-----------:|----------:|----------:|----------:|----:|
| 'Create all HSS beams.' | 306.5 ms | 34.32 ms | 22.70 ms | 55000.0000 | 5000.0000 | 2000.0000 | 205.99 MB |993kb|
| 'Create all HSS beams.' | **383.5 ms** | 12.87 ms | 8.51 ms | 41000.0000 | 2000.0000 |     - | **140.97 MB** |**667kb**|

TESTING:
- The table above is created by `Elements.Benchmarks`.

REQUIRED:
- [ ] All changes are up to date in `CHANGELOG.md`. **n/a**

Without vertex merging enabled:
image

With vertex merging enabled:
image

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/573)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/573)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/src/Geometry/CsgExtensions.cs, line 70 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtJObE9Q-LUj179Ioe:-MZtJObE9Q-LUj179Iof:b-lh2mn6) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L70)):*
> ```Smalltalk
>             var octree = new PointOctree<(Vector3 position, Vector3 normal, ushort index)>(size, origin, SEARCH_RADIUS);
> 
>             foreach (var p in csg.Polygons)
> ```

This is the beginning of a very long method that references variables created pretty far up the stack.  Anyway we can make a class that holds some of these vars and extract a sub-method here?  
___
*[Elements/src/Geometry/CsgExtensions.cs, line 72 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtLjmu2p0WKKwmCQbx:-MZtLjmv7-VGRbpeZAtu:b99449a) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L72)):*
> ```Smalltalk
>             foreach (var p in csg.Polygons)
>             {
>                 var ii = new ushort[p.Vertices.Count];
> ```

what does `ii` store?
___
*[Elements/src/Geometry/CsgExtensions.cs, line 153 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZssHbO93ixPf0ZLptG:-MZssHbO93ixPf0ZLptH:bo9ngp6) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L153)):*
> ```Smalltalk
>                     var c = tess.Vertices[tess.Elements[2]].Position.ToVector3();
>                     var tmp = (b - a).Unitized();
>                     var n = tmp.Cross(c - a).Unitized();
> ```

can we expand the name of n?  I think it's for `normal` but not sure tbh.
___
*[Elements/src/Geometry/CsgExtensions.cs, line 235 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtFRka9tR5AexDfN69:-MZtFRka9tR5AexDfN6A:buysy4t) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L235)):*
> ```Smalltalk
>                                         List<byte> uvs,
>                                         (Vector3 U, Vector3 V) basis,
>                                         ref double[] vmax,
> ```

since you're not re-assigning the variables I don't think these should be ref arguments.  You can still change the contents of an array internal to this method.
___
*[Elements/src/Geometry/CsgExtensions.cs, line 323 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZsston-V3uRNVP-xjx:-MZsston-V3uRNVP-xjy:btroxku) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L323)):*
> ```Smalltalk
>                         Csg.Vertex cv = null;
> 
>                         // TODO: Figure out if this is required.
> ```

can you add a brief note for how someone would figure this out in the future?
___
*[Elements.Benchmarks/Program.cs, line 72 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtFAXS0XfDtGJgBLAm:-MZtFAXS0XfDtGJgBLAn:b6zucz1) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements.Benchmarks/Program.cs#L72)):*
> ```Smalltalk
>                 }
>             }
>             model.ToGlTF(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "CreateAllHSSBeamsBenchmark.glb"));
> ```

Let's have this save to a gitignored location inside the code repo rather than my Documents folder.

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/573)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/Geometry/CsgExtensions.cs, line 70 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtJObE9Q-LUj179Ioe:-MZykR9162_sSbJkEaMi:byx0bqm) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L70)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

This is the beginning of a very long method that references variables created pretty far up the stack.  Anyway we can make a class that holds some of these vars and extract a sub-method here?  
</blockquote></details>

This is a great suggestion and a change that is a long time coming. I've created a new `GraphicsBuffers` class that holds graphics data in the correct layout and I've updated all locations that previously had tons of `out` input parameters to use this new class. 
___
*[Elements/src/Geometry/CsgExtensions.cs, line 72 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtLjmu2p0WKKwmCQbx:-MZyKmtT7pC0tOu7rFxa:bj9h94t) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L72)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

what does `ii` store?
</blockquote></details>

`ii` stores vertex indices. They're ushort because that's all they have to be.
___
*[Elements/src/Geometry/CsgExtensions.cs, line 153 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZssHbO93ixPf0ZLptG:-MZyLDNI7HGAa8gw2BiO:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L153)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can we expand the name of n?  I think it's for `normal` but not sure tbh.
</blockquote></details>

Done.
___
*[Elements/src/Geometry/CsgExtensions.cs, line 235 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtFRka9tR5AexDfN69:-MZyMKmwA9NK6it-nedw:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L235)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

since you're not re-assigning the variables I don't think these should be ref arguments.  You can still change the contents of an array internal to this method.
</blockquote></details>

Done.
___
*[Elements/src/Geometry/CsgExtensions.cs, line 323 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZsston-V3uRNVP-xjx:-MZyMddG3XLTanYYcWNJ:b-z7osey) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L323)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can you add a brief note for how someone would figure this out in the future?
</blockquote></details>

I've removed the note and the associated code completely.
___
*[Elements.Benchmarks/Program.cs, line 72 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtFAXS0XfDtGJgBLAm:-MZykKQJ3iv_6LzfdtI4:ba6dz9z) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements.Benchmarks/Program.cs#L72)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

Let's have this save to a gitignored location inside the code repo rather than my Documents folder.
</blockquote></details>

I don't need to write the file. I've removed that step.

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/573)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/src/GraphicsBuffers.cs, line 5 at r2](https://reviewable.io/reviews/hypar-io/elements/573#-M_1-odT2uO05wWohUul:-M_1-odT2uO05wWohUum:b-iop9vi) ([raw file](https://github.com/hypar-io/elements/blob/53d30d2305a19dda66571569a7dae3deaa391772/Elements/src/GraphicsBuffers.cs#L5)):*
> ```Smalltalk
> using Elements.Geometry;
> 
> namespace Elements
> ```

This file is used almost exclusively in classes in the Geometry namespace, and seems like it would fit in that namespace/folder.  The other option would be Serialization.  Up to you.
___
*[Elements/src/GraphicsBuffers.cs, line 22 at r2](https://reviewable.io/reviews/hypar-io/elements/573#-M_106gL8e52804w0Ep5:-M_106gL8e52804w0Ep6:b-wyqiqp) ([raw file](https://github.com/hypar-io/elements/blob/53d30d2305a19dda66571569a7dae3deaa391772/Elements/src/GraphicsBuffers.cs#L22)):*
> ```Smalltalk
>         /// A collection of indices stored as sequential bytes.
>         /// </summary>
>         /// <value></value>
> ```

sometimes we have the value tag, sometimes we don't, I think just delete the ones that are empty.
___
*[Elements/src/GraphicsBuffers.cs, line 42 at r2](https://reviewable.io/reviews/hypar-io/elements/573#-M_10IIH964N1md3iaFn:-M_10IIH964N1md3iaFo:bfvyadx) ([raw file](https://github.com/hypar-io/elements/blob/53d30d2305a19dda66571569a7dae3deaa391772/Elements/src/GraphicsBuffers.cs#L42)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The maximum position value.
> ```

all of these maximums/minimums are arrays, can we describe why/what would be inside the array?  I'm guessing it's an array that is expected to have exactly 3 values for X,Y,Z ?
___
*[Elements/src/Geometry/CsgExtensions.cs, line 72 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtLjmu2p0WKKwmCQbx:-M_1143h1-jeExwPiNji:b-2mc678) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L72)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

`ii` stores vertex indices. They're ushort because that's all they have to be.
</blockquote></details>

could we rename this to vertextIndices, or is `ii` a vertex index convention?  down below we have `ii[i]` which is particularly confusing to me, but might be commonplace when dealing with meshes.

**Comment by ikeough** [comment]
This is a problem. The vertex merging merges the UV coordinates. UV coordinate handling was not great to begin with due to the mistaken assumption that UV coordinates were blown away during CSG operations. They are not, which means that we can apply UV coordinates to the solid vertices, avoid tessellating in the case of the swept curve (the outer cylinder) and properly apply normals and UVs as the CSG is constructed. We might not need to do mesh re-merging at all.

image

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/573)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/Geometry/CsgExtensions.cs, line 72 at r1](https://reviewable.io/reviews/hypar-io/elements/573#-MZtLjmu2p0WKKwmCQbx:-M_1a9gC9KXDUcQ6rI4j:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/580f6f1239e1f7ae2c3d6a1fcec8e47fb2578cd7/Elements/src/Geometry/CsgExtensions.cs#L72)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

could we rename this to vertextIndices, or is `ii` a vertex index convention?  down below we have `ii[i]` which is particularly confusing to me, but might be commonplace when dealing with meshes.
</blockquote></details>

Done.
___
*[Elements/src/GraphicsBuffers.cs, line 5 at r2](https://reviewable.io/reviews/hypar-io/elements/573#-M_1-odT2uO05wWohUul:-M_gVD0z0l16Jtd1ktGj:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/53d30d2305a19dda66571569a7dae3deaa391772/Elements/src/GraphicsBuffers.cs#L5)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

This file is used almost exclusively in classes in the Geometry namespace, and seems like it would fit in that namespace/folder.  The other option would be Serialization.  Up to you.
</blockquote></details>

Done.
___
*[Elements/src/GraphicsBuffers.cs, line 22 at r2](https://reviewable.io/reviews/hypar-io/elements/573#-M_106gL8e52804w0Ep5:-M_1Zts4-lP1k-k-Viff:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/53d30d2305a19dda66571569a7dae3deaa391772/Elements/src/GraphicsBuffers.cs#L22)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

sometimes we have the value tag, sometimes we don't, I think just delete the ones that are empty.
</blockquote></details>

Done.
___
*[Elements/src/GraphicsBuffers.cs, line 42 at r2](https://reviewable.io/reviews/hypar-io/elements/573#-M_10IIH964N1md3iaFn:-M_1_mco71DWy0SdtB_7:b-161a38) ([raw file](https://github.com/hypar-io/elements/blob/53d30d2305a19dda66571569a7dae3deaa391772/Elements/src/GraphicsBuffers.cs#L42)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

all of these maximums/minimums are arrays, can we describe why/what would be inside the array?  I'm guessing it's an array that is expected to have exactly 3 values for X,Y,Z ?
</blockquote></details>

Good point. It's hard to understand what these are or why they are important.  Comments updated.

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/573)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by wynged — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/573)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
