### PR TITLE
Draw

### PR DESCRIPTION
**Pull request by ikeough**
**SEE COMMENTS BELOW FOR SIGNIFICANT CHANGES TO THIS PR**

BACKGROUND:
It would be nice to be able to draw arrows and text.

DESCRIPTION:
- Add a new class `Draw` with support for 3d text.
- Add a new class `ModelArrows` that functions like our `ModelPoints` and allows for the drawing of many arrows in one draw call with variable colors.
  
FUTURE WORK:
Text drawing is currently very expensive because we build a texture for every text label and those become files on disk. These labels should be added to a texture atlas and the label UV coordinates specified correctly.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

image

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/634)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/634)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/src/Draw.cs, line 15 at r1](https://reviewable.io/reviews/hypar-io/elements/634#-Mg6pPFSCJ0cKHybZp4F:-Mg6pPFSCJ0cKHybZp4G:bmfi8p0) ([raw file](https://github.com/hypar-io/elements/blob/506a1943b10686d8fd66718da74c574bedc9cc4d/Elements/src/Draw.cs#L15)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// Utilities for drawing.
> ```

Do we want to express explicitly that this is for debugging purposes? I know you had concerns about performance — I'd hate for someone to see this and start relying on it for a production function, when we really want things like labels to be the avenue. 
___
*[Elements/src/Draw.cs, line 32 at r1](https://reviewable.io/reviews/hypar-io/elements/634#-Mg6orOC9GBa_awnmHde:-Mg6orOC9GBa_awnmHdf:bnciubn) ([raw file](https://github.com/hypar-io/elements/blob/506a1943b10686d8fd66718da74c574bedc9cc4d/Elements/src/Draw.cs#L32)):*
> ```Smalltalk
>         public static Mass Cube(Vector3 location, string label, Material material, double size = 0.4)
>         {
>             return new Mass(Geometry.Polygon.Rectangle(size, size), size, material, new Transform(location - new Vector3(0, 0, size / 2)), name: label);
> ```

Can we make this a generic GeometricElement (or a specific type) with a representation instead of a Mass? I feel like, at least in theory, a Mass is supposed to represent a building mass of some kind (even though we don't really use it that way.) I know this is just debugging, but I worry about something like "get all masses in model" and running into these little cubes.  
___
*[Elements/src/Draw.cs, line 76 at r1](https://reviewable.io/reviews/hypar-io/elements/634#-Mg6pjzpDnK2W_sE4ZJH:-Mg6pjzpDnK2W_sE4ZJI:b-3ddhi9) ([raw file](https://github.com/hypar-io/elements/blob/506a1943b10686d8fd66718da74c574bedc9cc4d/Elements/src/Draw.cs#L76)):*
> ```Smalltalk
>         /// <param name="direction">The facing direction of the text</param>
>         /// <param name="size">The side length of the square mesh that will contain the text.</param>
>         public static MeshElement Text(string text, Vector3 location, Vector3 direction, double size = 1.0)
> ```

maybe give `direction` a default of (0,0,0) or something, since we already have a way to handle that case with a sensible behavior?

**Comment by ikeough** [comment]
Updated this PR to remove the arrow function that creates geometry and replaces it with `ModelArrows` which can visualize thousands of arrows of different lengths and colors in 1 draw call.
image

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/634)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/src/ModelArrows.cs, line 45 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfmeky9KxUDXgdk8Fo:-Mgfmeky9KxUDXgdk8Fp:b135lef) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelArrows.cs#L45)):*
> ```Smalltalk
>         /// <param name="arrowAtEnd">Should an arrow head be drawn at the end?</param>
>         /// <param name="arrowAngle">The angle of the arrow head.</param>
>         /// <param name="transform">The model arrows's transform.</param>
> ```

The model arrows's transform => The model arrows' transform
___
*[Elements/src/ModelArrows.cs, line 113 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfyDUA9-s60K6BVSj7:-MgfyDUBCKi20kmts7Ki:b-xvgjlb) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelArrows.cs#L113)):*
> ```Smalltalk
>                 {
>                     var pt = pts[j];
>                     gb.AddVertex(pt, default(Vector3), default(UV), v.color.HasValue ? v.color : Colors.Red);
> ```

I think this can just be `v.color ?? Colors.Red`
___
*[Elements/src/ModelText.cs, line 78 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfulx30hgZXcJKOtWn:-Mgfulx30hgZXcJKOtWo:bwki06d) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L78)):*
> ```Smalltalk
>         public ModelText(IList<(Vector3 location, Vector3 direction, string text, Geometry.Color? color)> texts,
>                          FontSize fontSize,
>                          double scale = 1.0)
> ```

I'm worried a default scale of 1 is going to lead people to create text that's too small, and wonder where it all went. 36pts is 1/2" — which would be pretty small in the scale of a building. 
___
*[Elements/src/ModelText.cs, line 102 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfstuJ6N2qtlGkAcmS:-MgfstuJ6N2qtlGkAcmT:b-t6ws54) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L102)):*
> ```Smalltalk
>             {
>                 FontCollection collection = new FontCollection();
>                 FontFamily family = collection.Install("Fonts/Roboto-Medium.ttf");
> ```

This path fails when utilizing `hypar run` against a local build of elements (and likely other cases too) — it goes looking in the root of the project for a file that doesn't exist.
___
*[Elements/src/ModelText.cs, line 111 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfrp7m9fNzByMFEktW:-Mgfrp7m9fNzByMFEktX:b-yz1b2v) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L111)):*
> ```Smalltalk
>             {
>                 var asmDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
>                 _labelsDirectory = Path.Combine(asmDir, $"Labels");
> ```

This is not a valid path to write to on a lambda — this will fail when the function is published. We can only write to the temp directory.
___
*[Elements/src/ModelText.cs, line 122 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfrwSg6QA1jhaiNyac:-MgfrwSg6QA1jhaiNyad:b-6y2vth) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L122)):*
> ```Smalltalk
>                 TextOptions = new TextOptions()
>                 {
>                     // ApplyKerning = true,
> ```

nix any commented code
___
*[Elements/src/ModelText.cs, line 177 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfv4Qe6p9RN5KP49c1:-Mgfv4Qe6p9RN5KP49c2:b-oznkuh) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L177)):*
> ```Smalltalk
> 
>                     // x = 0.0f;
>                     // y = 0.0f;
> ```

nix commented code
___
*[Elements/src/ModelText.cs, line 226 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfvqn1-P8-Q1WiPWcF:-Mgfvqn1-P8-Q1WiPWcG:b-oznkuh) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L226)):*
> ```Smalltalk
>                 // var uv2 = new UV(0, 1);
>                 // var uv3 = new UV(1, 1);
>                 // var uv4 = new UV(1, 0);
> ```

nix commented code
___
*[Elements/src/Geometry/Vector3.cs, line 998 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfwNw52i5eH4D9SMPp:-MgfwNw52i5eH4D9SMPq:ba8atqy) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/Geometry/Vector3.cs#L998)):*
> ```Smalltalk
>         }
> 
>         internal static GraphicsBuffers ToGraphicsBuffers(this IList<Vector3> vertices, bool lineLoop)
> ```

Does the lineLoop flag ever get used anywhere by a caller? It seems like everywhere we're calling this lineLoop = false. Did you maybe mean to call this from `Curve.ToGraphicsBuffers` to eliminate duplicated code? 
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 539 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfn-Qf2AhcGVI1m3UR:-Mgfn-Qf2AhcGVI1m3US:b2ni8l4) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/Serialization/glTF/GltfExtensions.cs#L539)):*
> ```Smalltalk
>             while (buffer.Count % 4 != 0)
>             {
>                 // Console.WriteLine("Padding...");
> ```

nix
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 1069 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfxJvF0BRoaaoHbjiZ:-MgfxJvF0BRoaaoHbji_:b-2bt977) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/Serialization/glTF/GltfExtensions.cs#L1069)):*
> ```Smalltalk
>             {
>                 var mc = (ModelCurve)e;
>                 var id = $"{GetNextId()}_curve";
> ```

if we ever want ModelCurves to be selectable in the UI, they need to have some mapping back to the element's ID (e.g. `${e.Id}_curve` instead). Does it make sense to do that with this change? 
___
*[Elements/test/ModelArrowsTests.cs, line 22 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfj74Z783h8m_a4m8c:-Mgfj74Z783h8m_a4m8d:b-tgzqxp) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/test/ModelArrowsTests.cs#L22)):*
> ```Smalltalk
>             // <example>
>             // Create some arrow locations.
>             var vectors = new List<(Vector3, Vector3, double, Color?)>();
> ```

Can we include the names of the tuple arguments, since this is being used as an example, just to make it clear what each piece does?
___
*[Elements/test/ModelTextTests.cs, line 26 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfizM6EqT3RteekPPn:-MgfizM7Bjc0dYAabtVv:b-tgzqxp) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/test/ModelTextTests.cs#L26)):*
> ```Smalltalk
>             var maxDistance = Math.Sqrt(Math.Pow(squareSize, 2) + Math.Pow(squareSize, 2));
> 
>             var texts = new List<(Vector3, Vector3, string, Color?)>();
> ```

Can we include the names of the tuple arguments, since this is being used as an example, just to make it clear what each piece does?
___
*[Elements/test/ModelTextTests.cs, line 38 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfidPr1IpkH2UL4ynM:-MgfidPr1IpkH2UL4ynN:bsu9d5) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/test/ModelTextTests.cs#L38)):*
> ```Smalltalk
>             }
> 
>             // Create a model arrows object.
> ```

model arrows => model text

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/634)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements/src/ModelArrows.cs, line 45 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfmeky9KxUDXgdk8Fo:-MggDmg0CvoKiDjhnMFI:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelArrows.cs#L45)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

The model arrows's transform => The model arrows' transform
</blockquote></details>

Done.
___
*[Elements/src/ModelArrows.cs, line 113 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfyDUA9-s60K6BVSj7:-MggDnlK8hTEjxtRnUu4:b-b21qqq) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelArrows.cs#L113)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I think this can just be `v.color ?? Colors.Red`
</blockquote></details>

I always forget this is available in C# now. Much nicer. Done.
___
*[Elements/src/ModelText.cs, line 78 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfulx30hgZXcJKOtWn:-MggDvHn7EGxa60gNHJs:b-fu7tw9) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L78)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I'm worried a default scale of 1 is going to lead people to create text that's too small, and wonder where it all went. 36pts is 1/2" — which would be pretty small in the scale of a building. 
</blockquote></details>

Agreed. Upped the default scale to 10.0.
___
*[Elements/src/ModelText.cs, line 102 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfstuJ6N2qtlGkAcmS:-MggL-DT00UNprB92piA:b6sjgg8) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L102)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

This path fails when utilizing `hypar run` against a local build of elements (and likely other cases too) — it goes looking in the root of the project for a file that doesn't exist.
</blockquote></details>

Fixed to be relative to the runtime location.
___
*[Elements/src/ModelText.cs, line 111 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfrp7m9fNzByMFEktW:-MggH2-s0_PeItjgjDoz:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L111)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

This is not a valid path to write to on a lambda — this will fail when the function is published. We can only write to the temp directory.
</blockquote></details>

Done.
___
*[Elements/src/ModelText.cs, line 122 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfrwSg6QA1jhaiNyac:-MggE4gt4RIMnWyvE4Yq:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L122)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

nix any commented code
</blockquote></details>

Done.
___
*[Elements/src/ModelText.cs, line 177 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfv4Qe6p9RN5KP49c1:-MggE67CERKlllTTGHk3:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L177)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

nix commented code
</blockquote></details>

Done.
___
*[Elements/src/ModelText.cs, line 226 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfvqn1-P8-Q1WiPWcF:-MggE6ad7m_s8_BW45Te:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L226)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

nix commented code
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Vector3.cs, line 998 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfwNw52i5eH4D9SMPp:-MggNYKd1ZdFIcPmvOVq:b-ydayx3) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/Geometry/Vector3.cs#L998)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Does the lineLoop flag ever get used anywhere by a caller? It seems like everywhere we're calling this lineLoop = false. Did you maybe mean to call this from `Curve.ToGraphicsBuffers` to eliminate duplicated code? 
</blockquote></details>

Yes. It gets used when processing model curves during gltf writing.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 539 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfn-Qf2AhcGVI1m3UR:-MggEDjY2PtTW7BHluGJ:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/Serialization/glTF/GltfExtensions.cs#L539)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

nix
</blockquote></details>

Done.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 1069 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfxJvF0BRoaaoHbjiZ:-MggE_6oBf70Yil8ctA7:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/Serialization/glTF/GltfExtensions.cs#L1069)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

if we ever want ModelCurves to be selectable in the UI, they need to have some mapping back to the element's ID (e.g. `${e.Id}_curve` instead). Does it make sense to do that with this change? 
</blockquote></details>

Done.
___
*[Elements/test/ModelArrowsTests.cs, line 22 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-Mgfj74Z783h8m_a4m8c:-MggF1aOBh66X4S0ZtUK:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/test/ModelArrowsTests.cs#L22)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Can we include the names of the tuple arguments, since this is being used as an example, just to make it clear what each piece does?
</blockquote></details>

Done.
___
*[Elements/test/ModelTextTests.cs, line 26 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfizM6EqT3RteekPPn:-MggFTKKEgTmJL487b4j:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/test/ModelTextTests.cs#L26)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Can we include the names of the tuple arguments, since this is being used as an example, just to make it clear what each piece does?
</blockquote></details>

Done.
___
*[Elements/test/ModelTextTests.cs, line 38 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfidPr1IpkH2UL4ynM:-MggFZ1h8x8WWLZrEYgr:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/test/ModelTextTests.cs#L38)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

model arrows => model text
</blockquote></details>

Done.
___
*[Elements/src/Draw.cs, line 15 at r1](https://reviewable.io/reviews/hypar-io/elements/634#-Mg6pPFSCJ0cKHybZp4F:-MggFc6W4tIUWuftF6uN:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/506a1943b10686d8fd66718da74c574bedc9cc4d/Elements/src/Draw.cs#L15)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Do we want to express explicitly that this is for debugging purposes? I know you had concerns about performance — I'd hate for someone to see this and start relying on it for a production function, when we really want things like labels to be the avenue. 
</blockquote></details>

Done.
___
*[Elements/src/Draw.cs, line 32 at r1](https://reviewable.io/reviews/hypar-io/elements/634#-Mg6orOC9GBa_awnmHde:-MggFboS2wuhQlqOmMdy:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/506a1943b10686d8fd66718da74c574bedc9cc4d/Elements/src/Draw.cs#L32)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Can we make this a generic GeometricElement (or a specific type) with a representation instead of a Mass? I feel like, at least in theory, a Mass is supposed to represent a building mass of some kind (even though we don't really use it that way.) I know this is just debugging, but I worry about something like "get all masses in model" and running into these little cubes.  
</blockquote></details>

Done.
___
*[Elements/src/Draw.cs, line 76 at r1](https://reviewable.io/reviews/hypar-io/elements/634#-Mg6pjzpDnK2W_sE4ZJH:-MggFcrg8JCjv_T3DHHg:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/506a1943b10686d8fd66718da74c574bedc9cc4d/Elements/src/Draw.cs#L76)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

maybe give `direction` a default of (0,0,0) or something, since we already have a way to handle that case with a sensible behavior?
</blockquote></details>

Done.

**Comment by ikeough** [comment]
Font path fixed to enable running in Hypar function: 
image

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/634)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[Elements/src/ModelText.cs, line 122 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfrwSg6QA1jhaiNyac:-MggPXq-Evwbh6qbSTD4:b5ilxji) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L122)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it though? :stuck_out_tongue_closed_eyes: 
___
*[Elements/src/Geometry/Vector3.cs, line 998 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfwNw52i5eH4D9SMPp:-MggPn9DArwsFj9D-cWU:byaamcj) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/Geometry/Vector3.cs#L998)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Yes. It gets used when processing model curves during gltf writing.
</blockquote></details>

ModelCurves utilizes `ModelCurve.ToGraphicsBuffers`, not this method. All calls in this codebase to `Vector3.ToGraphicsBuffers` have this argument false — am I missing something? 
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 1067 at r4](https://reviewable.io/reviews/hypar-io/elements/634#-MggQRsy4VuNVp1s3Wjb:-MggQRsy4VuNVp1s3Wjc:b-nspuq7) ([raw file](https://github.com/hypar-io/elements/blob/73f1add5c7b6ccf3e6309b1ee5978b6fa25d030d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1067)):*
> ```Smalltalk
>             {
>                 var mc = (ModelCurve)e;
>                 var id = $"{e.Id.ToString()}_curve";
> ```

You can omit `ToString()` in an interpolated string — this can just be `$"{e.Id}_curve"`

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/634)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements/src/ModelText.cs, line 122 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfrwSg6QA1jhaiNyac:-MggkMcp0dG34mSD3zJs:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/ModelText.cs#L122)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Is it though? :stuck_out_tongue_closed_eyes: 
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Vector3.cs, line 998 at r3](https://reviewable.io/reviews/hypar-io/elements/634#-MgfwNw52i5eH4D9SMPp:-MggkD5169W7P9o8WGaO:b-o5ef4c) ([raw file](https://github.com/hypar-io/elements/blob/fdc5b5cdd3b0c8348d3eeb8075233b1f5efa5a77/Elements/src/Geometry/Vector3.cs#L998)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

ModelCurves utilizes `ModelCurve.ToGraphicsBuffers`, not this method. All calls in this codebase to `Vector3.ToGraphicsBuffers` have this argument false — am I missing something? 
</blockquote></details>

Fixed after discussion to have implementation as a Vector extension with the line loop argument, called from ModelCurve.
___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 1067 at r4](https://reviewable.io/reviews/hypar-io/elements/634#-MggQRsy4VuNVp1s3Wjb:-MggkKiL8DKWEVHeVqrv:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/73f1add5c7b6ccf3e6309b1ee5978b6fa25d030d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1067)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

You can omit `ToString()` in an interpolated string — this can just be `$"{e.Id}_curve"`
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/634)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by andrewheumann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/634)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
