### PR TITLE
support referenced content extension

### PR DESCRIPTION
**Pull request by andrewheumann**
BACKGROUND:
- In order to support faster function execution, we want to explore skipping GLB merge, and passing GLB urls directly to a client. To do this, we want to support an experimental custom GLTF extension which lets you mark an object as containing content from a referenced URL.

DESCRIPTION:
- Adds support for the experimental referenced content extension. It will not be used unless `Elements.Serialization.glTF.GltfExtensions.UseReferencedContentExtension = true;` is on.

TESTING:
- I created several functions using this extension and tried them with a custom branch of the hypar front-end that knew how to read the extension.
  

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/913)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
mostly looks pretty good, I want to talk about how this could make an easy hop to supporting a glbRepresentation type, see if that desirable, and maybe change some language to support that.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/913#-:-NLd2Jb_5hDt6C9BtrRA:bhos0xn)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[`Elements/src/Serialization/glTF/GltfExtensions.cs` line 1223 at r1](https://reviewable.io/reviews/hypar-io/Elements/913#-NLd1aTuAveSsRZVxFdt:-NLd1aTuAveSsRZVxFdu:b-6xhej4) ([raw file](https://github.com/hypar-io/Elements/blob/33e00129e1c190b18d33368cec0531b6ee0a7f5d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1223)):*
> ```Smalltalk
>                             var nodeId = NodeUtilities.CreateNodeForMesh(meshId, nodes, content.Id, transform);
> 
>                             if (contentElement != null && UseReferencedContentExtension)
> ```

contentElement != null should already be true at this point.
___
*[`Elements/src/Serialization/glTF/GltfExtensions.cs` line 1283 at r1](https://reviewable.io/reviews/hypar-io/Elements/913#-NLd1wbv0fkiXAdyndN9:-NLd1wbv0fkiXAdyndNA:bhp1o9g) ([raw file](https://github.com/hypar-io/Elements/blob/33e00129e1c190b18d33368cec0531b6ee0a7f5d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1283)):*
> ```Smalltalk
>                     {
>                         AddExtension(gltf, nodes[nodeId], "HYPAR_referenced_content", new Dictionary<string, object> {
>                             {"contentUrl", contentElement.GltfLocation}
> ```

I think we should change the language here away from contentURL towards glbURL.

**Review by andrewheumann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/913)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Serialization/glTF/GltfExtensions.cs` line 1223 at r1](https://reviewable.io/reviews/hypar-io/Elements/913#-NLd1aTuAveSsRZVxFdt:-NLf-K_x6CRfIbxuk-0U:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/33e00129e1c190b18d33368cec0531b6ee0a7f5d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1223)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

contentElement != null should already be true at this point.
</blockquote></details>

Done.
___
*[`Elements/src/Serialization/glTF/GltfExtensions.cs` line 1283 at r1](https://reviewable.io/reviews/hypar-io/Elements/913#-NLd1wbv0fkiXAdyndN9:-NLf-Myy3Chqgez5M9B3:b-cm4iss) ([raw file](https://github.com/hypar-io/Elements/blob/33e00129e1c190b18d33368cec0531b6ee0a7f5d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1283)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think we should change the language here away from contentURL towards glbURL.  
</blockquote></details>

I'm not sure I agree. One reason I don't want to do this is that the format for the referenced content may not always be a GLB. Because we're no longer doing any merging in the function, we can now easily do referenced content of any type threeJS can display: Rhino files, point clouds, objs, etc.

**Review by wynged — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/913)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[`Elements/src/Serialization/glTF/GltfExtensions.cs` line 1223 at r1](https://reviewable.io/reviews/hypar-io/Elements/913#-NLd1aTuAveSsRZVxFdt:-NLfsSYHEXPUEHuBTzjD:b-vr4p06) ([raw file](https://github.com/hypar-io/Elements/blob/33e00129e1c190b18d33368cec0531b6ee0a7f5d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1223)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it.
___
*[`Elements/src/Serialization/glTF/GltfExtensions.cs` line 1283 at r1](https://reviewable.io/reviews/hypar-io/Elements/913#-NLd1wbv0fkiXAdyndN9:-NLfsLS750cRLgChXKoT:b-r1hu1n) ([raw file](https://github.com/hypar-io/Elements/blob/33e00129e1c190b18d33368cec0531b6ee0a7f5d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1283)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I'm not sure I agree. One reason I don't want to do this is that the format for the referenced content may not always be a GLB. Because we're no longer doing any merging in the function, we can now easily do referenced content of any type threeJS can display: Rhino files, point clouds, objs, etc. 
</blockquote></details>

yup, I buy that.  ContentElements are dead long live Content!

**Review by andrewheumann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/913)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Serialization/glTF/GltfExtensions.cs` line 1223 at r1](https://reviewable.io/reviews/hypar-io/Elements/913#-NLd1aTuAveSsRZVxFdt:-NLg-UUU9knsq_6deqb0:b47ndwl) ([raw file](https://github.com/hypar-io/Elements/blob/33e00129e1c190b18d33368cec0531b6ee0a7f5d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1223)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I don't see it.
</blockquote></details>

forgot to push oops!



_Code quote:_
```Smalltalk
 if (contentElement != null && UseReferencedContentExtension)
```

**Review by wynged — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/913)* status: 1 change requests, 0 of 1 approvals obtained

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/913)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
