### PR TITLE
Wall from profile

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- We want to change walls to support a variety of diverse wall types and to improve the openings API.

DESCRIPTION:
- update floor tests to confirm opening behavior is unchanged.
- deprecate wall Height and Profile of Wall.
- add Perimeter to WallByProfile and update constructors.
- add a direction to opening to support openings that are vertical
- add a test for `NormalFromPlanarWoundPoints` wich wasn't the problem (opening normals was) but I figure doesn't hurt.

TESTING:
- WallByProfileFromProfile test produces a wall with an opening.
  
FUTURE WORK:
- More WallByProfile changes and opening tweaks are likely as I work with exporting from Revit.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/673)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/673)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/Opening.cs, line 46 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-Mkm_FDm1YEgllDdlCx8:-Mkm_FDn5p_myxOXktmD:buy1avg) ([raw file](https://github.com/hypar-io/elements/blob/04107b0ed201db7573b24b95e71d59cb9517622f/Elements/src/Opening.cs#L46)):*
> ```Smalltalk
>         /// </summary>
>         [JsonConstructor]
>         public Opening(Polygon perimeter,
> ```

Can we make an overloaded constructor that doesn't have the normal parameter, so as not to break old code that constructs an Opening without one? this would have worked before, and will now fail to compile:
```
new Opening(rect, 2.5, 4, new Transform());
```
___
*[Elements/src/StandardWall.cs, line 83 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-Mkm_qZf6-xLiOa_bEVd:-Mkm_qZf6-xLiOa_bEVe:b-7hojae) ([raw file](https://github.com/hypar-io/elements/blob/04107b0ed201db7573b24b95e71d59cb9517622f/Elements/src/StandardWall.cs#L83)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Add an opening in the wall.
> ```

It's easy to miss param comments in intellisense. Can we provide an indication (here and wherever else relevant) that the arguments to this method assume that you're working in the wall's coordinate system? i.e how is this different from `wall.Openings.Add()`?
___
*[Elements/src/WallByProfile.cs, line 36 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmaA0bDOEFoKOA6aCq:-MkmaA0bDOEFoKOA6aCr:bgy64je) ([raw file](https://github.com/hypar-io/elements/blob/04107b0ed201db7573b24b95e71d59cb9517622f/Elements/src/WallByProfile.cs#L36)):*
> ```Smalltalk
>         /// </summary>
>         /// <param name="perimeter">The perimeter of the wall elevation.</param>
>         /// <param name="profile">This value should be left null.</param>
> ```

if there are deprecated arguments here, can we deprecate this constructor, or otherwise hide it from intellisense? 
___
*[Elements/src/WallByProfile.cs, line 67 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmaFL24gy5TpqdOmdi:-MkmaFL24gy5TpqdOmdj:b-gcx9eb) ([raw file](https://github.com/hypar-io/elements/blob/04107b0ed201db7573b24b95e71d59cb9517622f/Elements/src/WallByProfile.cs#L67)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The profile of the wall computed from it's Perimeter and the openings.
> ```

it's => its
___
*[Elements/src/WallByProfile.cs, line 86 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmaGy9EIbJ8FS0na8-:-MkmaGy9EIbJ8FS0na80:b-xex9vm) ([raw file](https://github.com/hypar-io/elements/blob/04107b0ed201db7573b24b95e71d59cb9517622f/Elements/src/WallByProfile.cs#L86)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Create a wall from a profile and thickness.  If a centerline is not include it will be
> ```

include => included
___
*[Elements/src/WallByProfile.cs, line 88 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmaKKi3SCzb6500TdA:-MkmaKKj0CdUcmv1n4M2:b4q8v95) ([raw file](https://github.com/hypar-io/elements/blob/04107b0ed201db7573b24b95e71d59cb9517622f/Elements/src/WallByProfile.cs#L88)):*
> ```Smalltalk
>         /// Create a wall from a profile and thickness.  If a centerline is not include it will be
>         /// computed from the profile.  The profile will be projected to the
>         /// centerline plane, and used to find openings of the Wall.
> ```

for all comments — let's be consistent about capitalization — either types (`Wall` / `wall`, 'Perimeter' / 'perimeter', etc) are capitalized or not
___
*[Elements/src/WallByProfile.cs, line 127 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-Mkmab354ir5zHTvMwKS:-Mkmab354ir5zHTvMwKT:b-qamk39) ([raw file](https://github.com/hypar-io/elements/blob/04107b0ed201db7573b24b95e71d59cb9517622f/Elements/src/WallByProfile.cs#L127)):*
> ```Smalltalk
>             {
>                 //TODO remove this geometry path once we completely delete the obsolete Profile property.
>                 // to ensure the correct direction, we find the direction form a point on the polygon to the vertical plane of the centerline
> ```

capitalize To, form => from

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/673)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/test/VectorTests.cs, line 218 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmbUlG0S9F5UVCspjr:-MkmbUlG0S9F5UVCspjs:b-l0ihjk) ([raw file](https://github.com/hypar-io/elements/blob/04107b0ed201db7573b24b95e71d59cb9517622f/Elements/test/VectorTests.cs#L218)):*
> ```Smalltalk
>             };
>             points.Reverse();
>             var normal = points.NormalFromPlanarWoundPoints();
> ```

I know this test is not the point, but can we at least validate the value of the normal?

**Review by andrewheumann — CHANGES_REQUESTED** [review]
I realize this was hashed out a bit in the design doc, and it's fine if we just want to stay the course with this approach, but I feel like the best solution here might have been the one not selected: unifying behind the `Wall` class with convenience constructors/Static methods and computed properties. something like `Wall.ByPlanProfile` `Wall.ByElevationProfile` `Wall.ByCenterline`, which each produce `Wall` elements and have `PlanProfile` `ElevationProfile` `Centerline` getters that can fill in the gaps of missing information, based on what's available? 

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/673#-:-MkmbbnnBZ74CqfPQtad:bvh70ce)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/WallByProfile.cs, line 24 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmcA-_2J562O8PF_NX:-MkmcA-_2J562O8PF_NY:b8qxjts) ([raw file](https://github.com/hypar-io/elements/blob/04107b0ed201db7573b24b95e71d59cb9517622f/Elements/src/WallByProfile.cs#L24)):*
> ```Smalltalk
>         public double Thickness { get; set; }
> 
>         /// <summary>The perimeter of the wall's profile.  It is assumed to be in the same plane as the centerline, and will often be projected to that plane during internal operations.</summary>
> ```

let's indicate that this is an elevational rather than plan shape

**Review by wynged — COMMENTED** [review]
Totally, would be great to move that direction, deferred for now.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/673#-:-MkmhtF85pHa-Hh062rA:b-3scuu1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements/src/Opening.cs, line 46 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-Mkm_FDm1YEgllDdlCx8:-Mkmz_GLCpD8YGUZ45rp:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0059c1e511b97b17251ccfec3eedc92adbfb16d9/Elements/src/Opening.cs#L46)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Can we make an overloaded constructor that doesn't have the normal parameter, so as not to break old code that constructs an Opening without one? this would have worked before, and will now fail to compile:
```
new Opening(rect, 2.5, 4, new Transform());
```
</blockquote></details>

Done.
___
*[Elements/src/StandardWall.cs, line 83 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-Mkm_qZf6-xLiOa_bEVd:-MkmzON59OIEpYe1ROTc:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0059c1e511b97b17251ccfec3eedc92adbfb16d9/Elements/src/StandardWall.cs#L83)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

It's easy to miss param comments in intellisense. Can we provide an indication (here and wherever else relevant) that the arguments to this method assume that you're working in the wall's coordinate system? i.e how is this different from `wall.Openings.Add()`?
</blockquote></details>

Done.
___
*[Elements/src/WallByProfile.cs, line 24 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmcA-_2J562O8PF_NX:-MkmzPd12UflOTQrILHi:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0059c1e511b97b17251ccfec3eedc92adbfb16d9/Elements/src/WallByProfile.cs#L24)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

let's indicate that this is an elevational rather than plan shape 
</blockquote></details>

Done.
___
*[Elements/src/WallByProfile.cs, line 36 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmaA0bDOEFoKOA6aCq:-MkmzSD64RLhNVrpf2G6:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0059c1e511b97b17251ccfec3eedc92adbfb16d9/Elements/src/WallByProfile.cs#L36)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

if there are deprecated arguments here, can we deprecate this constructor, or otherwise hide it from intellisense? 
</blockquote></details>

Done.
___
*[Elements/src/WallByProfile.cs, line 67 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmaFL24gy5TpqdOmdi:-MkmzTMEBcdf4wxZY54C:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0059c1e511b97b17251ccfec3eedc92adbfb16d9/Elements/src/WallByProfile.cs#L67)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

it's => its
</blockquote></details>

Done.
___
*[Elements/src/WallByProfile.cs, line 86 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmaGy9EIbJ8FS0na8-:-MkmzURP2hPpUS30eo2-:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0059c1e511b97b17251ccfec3eedc92adbfb16d9/Elements/src/WallByProfile.cs#L86)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

include => included
</blockquote></details>

Done.
___
*[Elements/src/WallByProfile.cs, line 88 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmaKKi3SCzb6500TdA:-MkmzYkZ4WNfyWwH4LEz:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0059c1e511b97b17251ccfec3eedc92adbfb16d9/Elements/src/WallByProfile.cs#L88)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

for all comments — let's be consistent about capitalization — either types (`Wall` / `wall`, 'Perimeter' / 'perimeter', etc) are capitalized or not
</blockquote></details>

Done.
___
*[Elements/src/WallByProfile.cs, line 127 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-Mkmab354ir5zHTvMwKS:-MkmzZbo1n2klmEPU4_9:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0059c1e511b97b17251ccfec3eedc92adbfb16d9/Elements/src/WallByProfile.cs#L127)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

capitalize To, form => from
</blockquote></details>

Done.
___
*[Elements/test/VectorTests.cs, line 218 at r3](https://reviewable.io/reviews/hypar-io/elements/673#-MkmbUlG0S9F5UVCspjr:-MkmotEv58VKt6lCIubA:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0059c1e511b97b17251ccfec3eedc92adbfb16d9/Elements/test/VectorTests.cs#L218)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I know this test is not the point, but can we at least validate the value of the normal?
</blockquote></details>

Done.

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/673)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/StandardWall.cs, line 84 at r4](https://reviewable.io/reviews/hypar-io/elements/673#-MknBZC3DJ7m6O1AUdqV:-MknBZC43kGrtB1Z0eHE:bkx7eno) ([raw file](https://github.com/hypar-io/elements/blob/064bf256036b75f39b16fe1996734d7069ed61b7/Elements/src/StandardWall.cs#L84)):*
> ```Smalltalk
>         /// <summary>
>         /// Add an Opening in the Wall. The Opening x and y sets the position relative to the Wall's Centerline.Start point
>         /// in the well elevation coordinate system.  The x and y will position the bottom left corner of the rectangular opening.
> ```

well => wall. And isn't this description wrong — doesn't it define the center, not the lower corner of the opening?
___
*[Elements/src/StandardWall.cs, line 102 at r4](https://reviewable.io/reviews/hypar-io/elements/673#-MknBgyjAW7x8MylhUmZ:-MknBgyjAW7x8MylhUm_:b-z9kgpg) ([raw file](https://github.com/hypar-io/elements/blob/064bf256036b75f39b16fe1996734d7069ed61b7/Elements/src/StandardWall.cs#L102)):*
> ```Smalltalk
>         /// <summary>
>         /// Add an Opening in the Wall. The Opening x and y sets the position relative to the Wall's Centerline.Start point
>         /// in the well elevation coordinate system.  The x and y will position the first point of the polygon opening.
> ```

well => wall. Also, I think this description is not correct either — the x and y specify the origin of the polygon (if it was drawn centered on the origin, it will be centered on the new xy, etc)

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/673)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/673)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements/src/StandardWall.cs, line 84 at r4](https://reviewable.io/reviews/hypar-io/elements/673#-MknBZC3DJ7m6O1AUdqV:-MknFRXBDOY08OA8vg0c:b7n1xo6) ([raw file](https://github.com/hypar-io/elements/blob/064bf256036b75f39b16fe1996734d7069ed61b7/Elements/src/StandardWall.cs#L84)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

well => wall. And isn't this description wrong — doesn't it define the center, not the lower corner of the opening?
</blockquote></details>

Done. ugh, yes
___
*[Elements/src/StandardWall.cs, line 102 at r4](https://reviewable.io/reviews/hypar-io/elements/673#-MknBgyjAW7x8MylhUmZ:-MknFSexB7v9BYV4srmi:b-es0q6b) ([raw file](https://github.com/hypar-io/elements/blob/064bf256036b75f39b16fe1996734d7069ed61b7/Elements/src/StandardWall.cs#L102)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

well => wall. Also, I think this description is not correct either — the x and y specify the origin of the polygon (if it was drawn centered on the origin, it will be centered on the new xy, etc)
</blockquote></details>

Done. ugh, yes yes

**Review by andrewheumann — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/673)* status: 1 change requests, 0 of 1 approvals obtained

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/673)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
