### PR TITLE
Polyline intersects Polygon bug

### PR DESCRIPTION
**Pull request by mwojcik-sagiton**
BACKGROUND:
I found that `Polyline.Intersects(Polygon polygon, out List<Polyline> sharedSegments)` returns wrong results when polyline start or end is on polygon perimeter.

DESCRIPTION:
I set `includeEnds` flag to true, when methods collects intersections between polygon segments and polyline. I had to add filtering of the same vectors for case polyline intersects with polygon vertex. 

TESTING:
Run unit test 
  
FUTURE WORK:
None

REQUIRED:
- [X] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
None

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/868)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/868)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mwojcik-sagiton)

___
*[`Elements/test/PolylineTests.cs` line 329 at r1](https://reviewable.io/reviews/hypar-io/elements/868#-NA5cAQp5_0ruVbcYCl6:-NA5cAQp5_0ruVbcYCl7:bc3wbp9) ([raw file](https://github.com/hypar-io/elements/blob/5df5b32aa0ff0e41e72b0fdc187683686d62ac14/Elements/test/PolylineTests.cs#L329)):*
> ```Smalltalk
> 
>         [Fact]
>         public void Test()
> ```

we shouldn't call this just `test`
___
*[`Elements/test/PolylineTests.cs` line 355 at r1](https://reviewable.io/reviews/hypar-io/elements/868#-NA5cKubDzbQkgxOzQp2:-NA5cKubDzbQkgxOzQp3:b-s4hv6b) ([raw file](https://github.com/hypar-io/elements/blob/5df5b32aa0ff0e41e72b0fdc187683686d62ac14/Elements/test/PolylineTests.cs#L355)):*
> ```Smalltalk
>             //Polyline is inside boundary
>             yield return new object[] { new Polyline(new Vector3(2, 0), new Vector3(-2, 0), new Vector3(-2, 1)),
>                 new Polyline(new Vector3(2, 0), new Vector3(-2, 0), new Vector3(-2, 1)) };
> ```

can you align these `new` statements?
___
*[`Elements/test/PolylineTests.cs` line 375 at r1](https://reviewable.io/reviews/hypar-io/elements/868#-NA5df9bEZX3Se2sTcTM:-NA5df9bEZX3Se2sTcTN:buls51z) ([raw file](https://github.com/hypar-io/elements/blob/5df5b32aa0ff0e41e72b0fdc187683686d62ac14/Elements/test/PolylineTests.cs#L375)):*
> ```Smalltalk
>             //Polyline start is inside boundary
>             yield return new object[] { new Polyline(new Vector3(-1, -5), new Vector3(-1, 0), Vector3.Origin),
>                 new Polyline(new Vector3(-1, -2), new Vector3(-1, 0), Vector3.Origin) };
> ```

I think we are now missing the case where the polyline is fully inside the polygon, start and end both inside the  boundary like the original test.

**Review by mwojcik-sagiton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/868)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/test/PolylineTests.cs` line 329 at r1](https://reviewable.io/reviews/hypar-io/elements/868#-NA5cAQp5_0ruVbcYCl6:-NA5gCZj0Qn9vNrxsYS6:b-ey21z4) ([raw file](https://github.com/hypar-io/elements/blob/5df5b32aa0ff0e41e72b0fdc187683686d62ac14/Elements/test/PolylineTests.cs#L329)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

we shouldn't call this just `test`
</blockquote></details>

Sorry I forgot to remove it 
___
*[`Elements/test/PolylineTests.cs` line 355 at r1](https://reviewable.io/reviews/hypar-io/elements/868#-NA5cKubDzbQkgxOzQp2:-NA5gFfh-cwDSv1JWzP2:bjiykng) ([raw file](https://github.com/hypar-io/elements/blob/5df5b32aa0ff0e41e72b0fdc187683686d62ac14/Elements/test/PolylineTests.cs#L355)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can you align these `new` statements?
</blockquote></details>

do you like new alignment? 
___
*[`Elements/test/PolylineTests.cs` line 375 at r1](https://reviewable.io/reviews/hypar-io/elements/868#-NA5df9bEZX3Se2sTcTM:-NA5gJY48LLveg4t3_Jm:b-4ex9ab) ([raw file](https://github.com/hypar-io/elements/blob/5df5b32aa0ff0e41e72b0fdc187683686d62ac14/Elements/test/PolylineTests.cs#L375)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think we are now missing the case where the polyline is fully inside the polygon, start and end both inside the  boundary like the original test.
</blockquote></details>

it is the first yield object line 341 to 346

**Review by wynged — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/868#-:-NA5n4CA9vUnbuySubz_:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`Elements/test/PolylineTests.cs` line 375 at r1](https://reviewable.io/reviews/hypar-io/elements/868#-NA5df9bEZX3Se2sTcTM:-NA5mvVsByrzMkcg42aR:bfk56v) ([raw file](https://github.com/hypar-io/elements/blob/5df5b32aa0ff0e41e72b0fdc187683686d62ac14/Elements/test/PolylineTests.cs#L375)):*
<details><summary><i>Previously, mwojcik-sagiton wrote…</i></summary><blockquote>

it is the first yield object line 341 to 346 
</blockquote></details>

ok, I'm just blind.

**Review by wynged — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/868)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
