### PR TITLE
Instance merged glbs

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- We want to be able to instance content elements where the glft is made up of multiple meshes and have internal gltf node structure. 

DESCRIPTION:
- fix bbox IsDegenerate method and add test.
- maintain a dictionary of nodes that corresponds to the element that was added.  when an instance is made that corresponds to that node we use the `ProtoNode` to rebuild the node hierarchy at the instance location.

TESTING:
- run the new instance content test and see that the content appears correctly.
  
FUTURE WORK:
- Something is still wrong with how content element nodes are named, this makes selecting content elements impossible.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/602)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/602)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 918 at r3](https://reviewable.io/reviews/hypar-io/elements/602#-Mbs74Eg7wHR2laKIoVq:-Mbs74Eg7wHR2laKIoVr:bpzi84j) ([raw file](https://github.com/hypar-io/elements/blob/b17372901f63b8ed40587d5ea54dfe429ece5d40/Elements/src/Serialization/glTF/GltfExtensions.cs#L918)):*
> ```Smalltalk
>                         }
>                         // TODO delete after 7/9 if not needed
>                         // if (!meshElementMap.ContainsKey(e.Id))
> ```

we can just remove this — we can always get it back from the git history if we need to bring it back.
___
*[Elements/src/Serialization/glTF/GltfMergingUtils.cs, line 139 at r3](https://reviewable.io/reviews/hypar-io/elements/602#-Mbs7MtgEIy7FSf5Pv_o:-Mbs7MtgEIy7FSf5Pv_p:b-lp43f7) ([raw file](https://github.com/hypar-io/elements/blob/b17372901f63b8ed40587d5ea54dfe429ece5d40/Elements/src/Serialization/glTF/GltfMergingUtils.cs#L139)):*
> ```Smalltalk
>         }
> 
>         private static ProtoNode RecursivelyModifyMeshIndices(glTFLoader.Schema.Node node, List<int> meshIndices, glTFLoader.Schema.Node[] loadedNodes)
> ```

Let's leave a comment above this method for future-us —
something like:
```
// We construct a new, recursively-structured 'ProtoNode' from the flat gltf node, and mutate its mesh indices to
// point to the correct mesh in the merged gltf. 
```

**Review by andrewheumann — COMMENTED** [review]
just a few little things!

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/602#-:-Mbs8lO29eW5mYlSBCpb:b-q1xjnc)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/602)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 918 at r3](https://reviewable.io/reviews/hypar-io/elements/602#-Mbs74Eg7wHR2laKIoVq:-MbwF-dM16iU1GIw15le:bb7f2mf) ([raw file](https://github.com/hypar-io/elements/blob/b17372901f63b8ed40587d5ea54dfe429ece5d40/Elements/src/Serialization/glTF/GltfExtensions.cs#L918)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

we can just remove this — we can always get it back from the git history if we need to bring it back.
</blockquote></details>

done
___
*[Elements/src/Serialization/glTF/GltfMergingUtils.cs, line 139 at r3](https://reviewable.io/reviews/hypar-io/elements/602#-Mbs7MtgEIy7FSf5Pv_o:-MbwFgAX5Wx_o6y1H9GY:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/b17372901f63b8ed40587d5ea54dfe429ece5d40/Elements/src/Serialization/glTF/GltfMergingUtils.cs#L139)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Let's leave a comment above this method for future-us —
something like:
```
// We construct a new, recursively-structured 'ProtoNode' from the flat gltf node, and mutate its mesh indices to
// point to the correct mesh in the merged gltf. 
```
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/602)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
