### PR TITLE
Fix #342.

### LINKED ISSUE #342: an angle between two identical vectors returns NaN
the angle between (0.9853, -0.1708) and (0.9853, -0.1708) returns NaN instead of 0, as expected

### PR DESCRIPTION
**Pull request by ikeough**
Fix #342.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/423)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/423)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @andrewheumann and @ikeough)

___
*[Elements/src/Geometry/Vector3.cs, line 177 at r1](https://reviewable.io/reviews/hypar-io/elements/423#-ML7vS6750ZgbLnI_T3m:-ML7vS6750ZgbLnI_T3n:b-bvxtk4) ([raw file](https://github.com/hypar-io/elements/blob/a3b3ed51a7b9cead3c268b84c733e5fc9a1127a8/Elements/src/Geometry/Vector3.cs#L177)):*
> ```Smalltalk
>             var n = Dot(v);
>             var d = Length() * v.Length();
>             var r = n / d;
> ```

should we check for d=0 to avoid a div by 0?

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/423)* status: all files reviewed, 1 unresolved discussion (waiting on @ikeough)

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/423)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Vector3.cs, line 177 at r1](https://reviewable.io/reviews/hypar-io/elements/423#-ML7vS6750ZgbLnI_T3m:-ML9446O0AJJrlRqh_tQ:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/a3b3ed51a7b9cead3c268b84c733e5fc9a1127a8/Elements/src/Geometry/Vector3.cs#L177)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

should we check for d=0 to avoid a div by 0?
</blockquote></details>

Done.

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/423)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

**Review by andrewheumann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/423)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
