### PR TITLE
Updated Beam and Column to support schema

### PR DESCRIPTION
**Pull request by katehryhorenko**
BACKGROUND:
Beam and Column do not have associated schemas

DESCRIPTION:
I added Beam and Column schema =>  updated constructors for both classes to support generated classes from this schemas.

PLEASE NOTE: DeserializationSkipsNullProperties is commented, cause now Column has empty constructor and it always will be deserialized
  
FUTURE WORK:
- Column class has location, height and curve constructor parameters. But curve will be created from location and height. As result curve parameter is not used, but we need it because generated class for Column will require it. We need some mechanism to avoid these extra parameters.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/817)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/817)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/Beam.cs` line 30 at r1](https://reviewable.io/reviews/hypar-io/elements/817#-N44qH8o0t9IPFAQdAld:-N44qH8o0t9IPFAQdAle:bs3095o) ([raw file](https://github.com/hypar-io/elements/blob/068a4512dfbb856b0c59d1ad6a8ca32df030eb21/Elements/src/Beam.cs#L30)):*
> ```Smalltalk
>                     Profile profile,
>                     Material material = null,
>                     double startSetback = 0.0,
> ```

why do we have to get rid of startSetback,endSetback and rotation parameters?  these properties seem useful.  could we keep a constructor around that has those as inputs, and then make a different constructor that has the [JsonConstructor] attribute?
___
*[`Elements/src/Column.cs` line 29 at r1](https://reviewable.io/reviews/hypar-io/elements/817#-N44o6QwEZrPQNerVBaZ:-N44o6QwEZrPQNerVBa_:bd8w071) ([raw file](https://github.com/hypar-io/elements/blob/40c3be51ef013e5ff00581fa5b7d83481296fcd2/Elements/src/Column.cs#L29)):*
> ```Smalltalk
>         /// <param name="location">The location of the base of the column.</param>
>         /// <param name="height">The column's height.</param>
>         /// <param name="curve">The center line of the column. Will be ignore, so you can use 'null'. This parameter is requered to support schema</param>
> ```

sp  "required" 
wording "ignored"
___
*[`Elements/src/Column.cs` line 39 at r1](https://reviewable.io/reviews/hypar-io/elements/817#-N44oUAl86rJWYOYbVEh:-N44oUAl86rJWYOYbVEi:b-ufrvtj) ([raw file](https://github.com/hypar-io/elements/blob/40c3be51ef013e5ff00581fa5b7d83481296fcd2/Elements/src/Column.cs#L39)):*
> ```Smalltalk
>         public Column(Vector3 location,
>               double height,
>               Curve curve,
> ```

why is the curve necessary?
___
*[`Elements/test/ModelTests.cs` line 245 at r1](https://reviewable.io/reviews/hypar-io/elements/817#-N44ory77pb4kMh-4d3L:-N44ory77pb4kMh-4d3M:bpeqnr4) ([raw file](https://github.com/hypar-io/elements/blob/40c3be51ef013e5ff00581fa5b7d83481296fcd2/Elements/test/ModelTests.cs#L245)):*
> ```Smalltalk
>                 this._output.WriteLine(e);
>             }
>             // TODO: this test cannot work, couse now Column has empty constructor
> ```

use "because"
___
*[`Elements.Serialization.IFC/src/Serialization/IFC/IFCExtensions.cs` line 40 at r1](https://reviewable.io/reviews/hypar-io/elements/817#-N44qnGv6AQEnE462tSQ:-N44qnGv6AQEnE462tSR:b99nmqh) ([raw file](https://github.com/hypar-io/elements/blob/068a4512dfbb856b0c59d1ad6a8ca32df030eb21/Elements.Serialization.IFC/src/Serialization/IFC/IFCExtensions.cs#L40)):*
> ```Smalltalk
>                                           new Profile(polygon),
>                                           BuiltInMaterials.Steel,
>                                           0.0,
> ```

might not need some of these changes if we preserve the original constructor

**Review by wynged — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/817)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/Column.cs` line 39 at r1](https://reviewable.io/reviews/hypar-io/elements/817#-N44oUAl86rJWYOYbVEh:-N44u53uEEz5o2YBGvcS:b-h2wdj) ([raw file](https://github.com/hypar-io/elements/blob/40c3be51ef013e5ff00581fa5b7d83481296fcd2/Elements/src/Column.cs#L39)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

why is the curve necessary?
</blockquote></details>

ahhh... because of structuralFraming having a curve

**Review by katehryhorenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/817)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko and @wynged)

___
*[`Elements/src/Column.cs` line 29 at r1](https://reviewable.io/reviews/hypar-io/elements/817#-N44o6QwEZrPQNerVBaZ:-N450z-r3D9IZEPhoRJh:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/40c3be51ef013e5ff00581fa5b7d83481296fcd2/Elements/src/Column.cs#L29)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

sp  "required" 
wording "ignored"
</blockquote></details>

Done.
___
*[`Elements/test/ModelTests.cs` line 245 at r1](https://reviewable.io/reviews/hypar-io/elements/817#-N44ory77pb4kMh-4d3L:-N450xwaAV9mQUnWVNg-:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/40c3be51ef013e5ff00581fa5b7d83481296fcd2/Elements/test/ModelTests.cs#L245)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

use "because"
</blockquote></details>

Done.

**Review by wynged — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/817)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
