### PR TITLE
Bug fix Polygon.Contains3D

### PR DESCRIPTION
**Pull request by pederlh**
BACKGROUND:
Fixed a bug causing issues in own code.

DESCRIPTION:
The `out Containment containment` parameter in Polygon.Contains3D isn't updated if one of the other polygon's vertices is outside this polygon.  In that case `Containment.Inside` would be passed instead of `Containment.Outside`.

TESTING:
None.
  
FUTURE WORK:
None.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/Elements/986)

### CODE REVIEW

**Review by ikeough — APPROVED** [review]
Thanks very much for the fix @pederlh.

**Comment by ikeough** [comment]
Seems like there's one failing test. Do you have any interest in attempting to fix?

**Comment by pederlh** [comment]
I’m off the grid for almost a month, so it would be great if you guys could take a look 😊 Otherwise I’ll revisit this later on

**Comment by pederlh** [comment]
The `dotnet test -c release` workflow process that was causing an error earlier passes without issue locally. Could you try to rerun the workflow @ikeough?

**Comment by andrewheumann** [comment]
Thanks for the nudge @pederlh, all tests are passing now, so I'm going to go ahead and merge. Sorry feedback on this PR took so long, and thanks for your contribution!!

**Pull request merged**
