### PR TITLE
Distance to

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- Needed distance to operations for analysing some lines.

DESCRIPTION:
- add a handful of distance to methods.
- factor out distance to methods into their own file.
- add tests for the methods

TESTING:
- pull branch run test.
  
FUTURE WORK:
- moar distance to methods.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/414)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/414)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @andrewheumann and @wynged)

___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 34 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe2_8eEuqRHhCPblK8:-MKe2_8fBnBLAU6GY2-K:ba3ed84) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L34)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Find the distance from this vector to the line, and output the location 
> ```

Let's call it a point rather than a vector, to be consistent with other docs
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 41 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe7Vg7-zsW3fZ8StNN:-MKe7Vg7-zsW3fZ8StNO:bg7fkfp) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L41)):*
> ```Smalltalk
>         public double DistanceTo(Line line, out Vector3 closestPoint)
>         {
>             var p = new Plane(this, line.Direction());
> ```

I think there's a simpler way to calculate this with one dot product. I doubt it would make a noticeable performance difference but Line.Intersects(Plane) calls Ray.Intersects(Plane), which in turn performs like 4 dot products.

```
var lineVec = line.Direction()
var startToPt = this - line.Start
var lengthAlongLine = startToPt.Dot(lineVec)
if(lengthAlongLine > line.Length()) {
    closestPoint = line.End
} else if (lengthAlongLine < 0) {
    closestPoint = line.Start
} else {
    closestPoint = line.Start + lineVec * lengthAlongLine
}
return DistanceTo(closestPoint)
```
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 46 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe2uWG-KLsa9ZJ3pYf:-MKe2uWHCj2sK72faatZ:bez2tkd) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L46)):*
> ```Smalltalk
>                 if (line.Intersects(p, out closestPoint))
>                 {
>                     // If the line intersect the plane originating at this point
> ```

intersect => intersects
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 68 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe3RRb5brwbZr4tOQ2:-MKe3RRb5brwbZr4tOQ3:b-f8dz7y) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L68)):*
> ```Smalltalk
>         public double DistanceTo(Line line)
>         {
>             return DistanceTo(line, out var ignoredPoint);
> ```

The convention is for ignored out variables to be represented with an underscore, treated as a discard:
https://csharp.today/c-7-0-discards/
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 72 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe3quz0pyQHrJr5M-6:-MKe3quz0pyQHrJr5M-7:bljr9bd) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L72)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Find the shortest distance from this vector to any point on the
> ```

vector => point
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 75 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe2oEuAIlIPQMkyo-E:-MKe2oEuAIlIPQMkyo-F:b-rktld7) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L75)):*
> ```Smalltalk
>         /// polyline, and output the location of the closest point on that polyline.
>         /// </summary>
>         /// <param name="polyline">The polyline to </param>
> ```

forgot to finish this one :) 
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 78 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe4zVO9GpT2XkrvMcQ:-MKe4zVO9GpT2XkrvMcR:buodjpk) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L78)):*
> ```Smalltalk
>         /// <param name="closestPoint">The point on the polyline that is closest to this point.</param>
>         /// <returns></returns>
>         public double DistanceTo(Polyline polyline, out Vector3 closestPoint)
> ```

Should this one get a convenience overload without the `out` as well?

**Review by andrewheumann — COMMENTED** [review]
I'm not convinced about the refactoring to Vector3.DistanceTo.cs. What problem is it solving?

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/414#-:-MKeCHeD2aeZwX5j_k5N:bcf7yue)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @andrewheumann and @wynged)

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/414)* status: all files reviewed, 7 unresolved discussions (waiting on @wynged)

**Review by wynged — COMMENTED** [review]
Vector3 file is large and DistanceTo file will be large and repetitive.  Just adding more structure.  If you don't like it I can move it back.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/414#-:-MKeJb9T614NepK86vsh:bvhuury)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 34 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe2_8eEuqRHhCPblK8:-MKeKu0J-6xpd--Q-8mY:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L34)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Let's call it a point rather than a vector, to be consistent with other docs
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 41 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe7Vg7-zsW3fZ8StNN:-MKes8rw5vrG5oEaMHlw:bt9frb6) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L41)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I think there's a simpler way to calculate this with one dot product. I doubt it would make a noticeable performance difference but Line.Intersects(Plane) calls Ray.Intersects(Plane), which in turn performs like 4 dot products.

```
var lineVec = line.Direction()
var startToPt = this - line.Start
var lengthAlongLine = startToPt.Dot(lineVec)
if(lengthAlongLine > line.Length()) {
    closestPoint = line.End
} else if (lengthAlongLine < 0) {
    closestPoint = line.Start
} else {
    closestPoint = line.Start + lineVec * lengthAlongLine
}
return DistanceTo(closestPoint)
```
</blockquote></details>

good intuition.  ran 10000 executions old vs new and got a ~1/3 speedup!
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 46 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe2uWG-KLsa9ZJ3pYf:-MKeL-c-COJs0ntZvCcz:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L46)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

intersect => intersects
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 68 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe3RRb5brwbZr4tOQ2:-MKeLdmf7BBO4uUZoASm:b-7c1oav) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L68)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

The convention is for ignored out variables to be represented with an underscore, treated as a discard:
https://csharp.today/c-7-0-discards/
</blockquote></details>

ok cool!
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 72 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe3quz0pyQHrJr5M-6:-MKeMjaw4O44DiQI1dTY:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L72)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

vector => point
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 75 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe2oEuAIlIPQMkyo-E:-MKeMkQx6YwyeijOE7lE:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L75)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

forgot to finish this one :) 
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 78 at r1](https://reviewable.io/reviews/hypar-io/elements/414#-MKe4zVO9GpT2XkrvMcQ:-MKeMlyP1nsk3EkWODB6:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0bc7b1088f06d6d8b77e1864035f8b0a79b121af/Elements/src/Geometry/Vector3.DistanceTo.cs#L78)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Should this one get a convenience overload without the `out` as well? 
</blockquote></details>

Done.

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/414)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrewheumann and @wynged)

___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 98 at r2](https://reviewable.io/reviews/hypar-io/elements/414#-MKetESGE4nTJBwbRWnh:-MKetESGE4nTJBwbRWni:biqmi6g) ([raw file](https://github.com/hypar-io/elements/blob/6d9d7fc5dd6ccb9d3bd6f18c89bbcf93f8ec7f06/Elements/src/Geometry/Vector3.DistanceTo.cs#L98)):*
> ```Smalltalk
>         /// </summary>
>         /// <param name="polyline">The polyline for computing the distance.</param>
>         public double DistanceTo(Polyline polyline)
> ```

Shouldn't this implementation just use the other method with `out _` like the other overload?

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/414)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Vector3.DistanceTo.cs, line 98 at r2](https://reviewable.io/reviews/hypar-io/elements/414#-MKetESGE4nTJBwbRWnh:-MKexmWQCb0x6p8_nGHI:b-jyjri6) ([raw file](https://github.com/hypar-io/elements/blob/6d9d7fc5dd6ccb9d3bd6f18c89bbcf93f8ec7f06/Elements/src/Geometry/Vector3.DistanceTo.cs#L98)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Shouldn't this implementation just use the other method with `out _` like the other overload?
</blockquote></details>

done, woops!

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/414)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
