### PR TITLE
Support non-xy splits

### PR DESCRIPTION
**Pull request by andrewheumann**
BACKGROUND:
- Polygon.Split would fail or give incorrect results for polygons not in the world XY plane, or not counter-clockwise wound.

DESCRIPTION:
- Transforms a polygon into its XY plane before trying to split it, and then transforms its results back.
- Adds a `ToTransform()` method to `Polygon` which produces a consistent transform with its Z axis along the polygon's normal. Using `Vertices.ToTransform()` was not yielding consistent results.

TESTING:
- Added new tests, verified old split tests still pass.

FUTURE WORK:
- We might want to enable `Profile` methods to be more tolerant of non-XY orientations as well

REQUIRED:
- [X] All changes are up to date in `CHANGELOG.md`.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/584)

### CODE REVIEW

**Review by serenayl — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/584)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 1100 at r1](https://reviewable.io/reviews/hypar-io/elements/584#-Ma-kwUJCCzEYl2e9k-Z:-Ma-kwUK2ta9K3H5cdAt:b-4lmnuy) ([raw file](https://github.com/hypar-io/elements/blob/45a1b9f9f5636d6d4aa3aea4f69b262127cfc5fc/Elements/src/Serialization/glTF/GltfExtensions.cs#L1100)):*
> ```Smalltalk
> 
>         public static Dictionary<string, MemoryStream> gltfCache = new Dictionary<string, MemoryStream>();
> ```

I'm generally unclear about the changes made to `GltfExtensions` and how they relate to the PR?

**Review by andrewheumann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/584)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @serenayl)

___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 1100 at r1](https://reviewable.io/reviews/hypar-io/elements/584#-Ma-kwUJCCzEYl2e9k-Z:-Ma02KYy4BqEcxOkv4Y_:b-e648a0) ([raw file](https://github.com/hypar-io/elements/blob/45a1b9f9f5636d6d4aa3aea4f69b262127cfc5fc/Elements/src/Serialization/glTF/GltfExtensions.cs#L1100)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

I'm generally unclear about the changes made to `GltfExtensions` and how they relate to the PR?
</blockquote></details>

mistake — reverted.

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/584)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @serenayl)

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/584)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @serenayl)

**Review by serenayl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/584)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
