### PR TITLE
Vector3.PlaneAngleTo

### PR DESCRIPTION
**Pull request by andrewheumann**
BACKGROUND:
- Elements did not have any way to calculate non-reflex angles in a given plane

DESCRIPTION:
- Adds `Vector3.PlaneAngleTo(Vector 3 v)` and a corresponding test

TESTING:
- Ran VectorTests.Vector3_PlaneAngles and ensured valid results

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/391)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/391)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewheumann and @ikeough)

___
*[Elements/src/Geometry/Vector3.cs, line 180 at r1](https://reviewable.io/reviews/hypar-io/elements/391#-MIPZScb-9IdZuSF0S65:-MIPZScb-9IdZuSF0S66:b-ec2j73) ([raw file](https://github.com/hypar-io/elements/blob/4b96f46a4186ba056856b31b1e1a129d320dbffa/Elements/src/Geometry/Vector3.cs#L180)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Calculate a plane angle between this vector and the provided vector in the XY plane.
> ```

This is a little confusing to me so I'd like to capture that it is the *horizontal* (XY) plan only, and that it is the clockwise angle.  
`Calculate the clockwise angle on the horizontal (XY) plane between this vector and the provided vector`
___
*[Elements/src/Geometry/Vector3.cs, line 204 at r1](https://reviewable.io/reviews/hypar-io/elements/391#-MIPZo3v1e5ciQ0ttn6K:-MIPZo3v1e5ciQ0ttn6L:bc9zjyg) ([raw file](https://github.com/hypar-io/elements/blob/4b96f46a4186ba056856b31b1e1a129d320dbffa/Elements/src/Geometry/Vector3.cs#L204)):*
> ```Smalltalk
>             // check if should be reflex angle
>             Vector3 aCrossB = aUnitized.Cross(bUnitized).Unitized();
>             if (Vector3.ZAxis.Dot(aCrossB) > 0.999)
> ```

is the epsilon not useful here?

**Review by andrewheumann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/391)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ikeough and @wynged)

___
*[Elements/src/Geometry/Vector3.cs, line 180 at r1](https://reviewable.io/reviews/hypar-io/elements/391#-MIPZScb-9IdZuSF0S65:-MIPlbOzEH5GtM31tqPq:beztjgv) ([raw file](https://github.com/hypar-io/elements/blob/4b96f46a4186ba056856b31b1e1a129d320dbffa/Elements/src/Geometry/Vector3.cs#L180)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

This is a little confusing to me so I'd like to capture that it is the *horizontal* (XY) plan only, and that it is the clockwise angle.  
`Calculate the clockwise angle on the horizontal (XY) plane between this vector and the provided vector`
</blockquote></details>

the method has changed a bit, but updated to include "counter-clockwise"
___
*[Elements/src/Geometry/Vector3.cs, line 204 at r1](https://reviewable.io/reviews/hypar-io/elements/391#-MIPZo3v1e5ciQ0ttn6K:-MIPhf8J3U1QzwkZzwoG:b-83r14i) ([raw file](https://github.com/hypar-io/elements/blob/4b96f46a4186ba056856b31b1e1a129d320dbffa/Elements/src/Geometry/Vector3.cs#L204)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

is the epsilon not useful here?
</blockquote></details>

This value should only ever be 1 or -1 — but all we really care about is whether it's > 0.  the .999 is misleading, changed.

**Review by wynged — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/391)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewheumann and @ikeough)

___
*[Elements/src/Geometry/Vector3.cs, line 180 at r1](https://reviewable.io/reviews/hypar-io/elements/391#-MIPZScb-9IdZuSF0S65:-MIPuTUtD3jwNz8xwJxL:bryeife) ([raw file](https://github.com/hypar-io/elements/blob/4b96f46a4186ba056856b31b1e1a129d320dbffa/Elements/src/Geometry/Vector3.cs#L180)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

the method has changed a bit, but updated to include "counter-clockwise"
</blockquote></details>

cool, this is what I thought this vector was for anyways, so I like the change.
___
*[Elements/src/Geometry/Vector3.cs, line 204 at r1](https://reviewable.io/reviews/hypar-io/elements/391#-MIPZo3v1e5ciQ0ttn6K:-MIPw4H12d6hlgvDz_Ot:b-90v2br) ([raw file](https://github.com/hypar-io/elements/blob/4b96f46a4186ba056856b31b1e1a129d320dbffa/Elements/src/Geometry/Vector3.cs#L204)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

This value should only ever be 1 or -1 — but all we really care about is whether it's > 0.  the .999 is misleading, changed.
</blockquote></details>

while getting dot products for some vectors in  a different method I didn't always get pure +-1, so think I'd include some tolerance here.  Might not happen since you're doing a cross product right above, up to you.  Here's where I had to add that tolerance check, I think it was causing a geometry validation error in that case.

  https://github.com/hypar-io/Elements/commit/a313cd3f14751cfac25ee817ff7fe0ccf5cb0f09

**Review by andrewheumann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/391)* status: all files reviewed, 2 unresolved discussions (waiting on @ikeough and @wynged)

___
*[Elements/src/Geometry/Vector3.cs, line 180 at r1](https://reviewable.io/reviews/hypar-io/elements/391#-MIPZScb-9IdZuSF0S65:-MIThsik7_9CimwsmPt0:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4b96f46a4186ba056856b31b1e1a129d320dbffa/Elements/src/Geometry/Vector3.cs#L180)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

cool, this is what I thought this vector was for anyways, so I like the change.
</blockquote></details>

Done.

**Pull request merged**
