### PR TITLE
Add Line.DistanceTo(Line)

### PR DESCRIPTION
**Pull request by DmytroMuravskyi**
BACKGROUND:
- At one moment I needed a function that calculates distance between two lines. Just taking minimum between endpoints and lines doesn't work in all cases. So, this function was created. At the end of the day was not used but I decided that it may be a good addition to the Elements.

DESCRIPTION:
- Line.DistanceTo(line) compute distance between any two lines, even those that are not on the same plane.
 
TESTING:
- Added two tests: one with simple handwritten lines, one with complex parametric numbers.
  
FUTURE WORK:
- Closest point is not returned but there is enough information to do so. There is no clear closest point for several cases of parallel or overlapping lines. I guess the close end point of other line can be returned in this case. Let me know if this is something you want.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/Elements/942)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/942)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[`Elements/src/Geometry/Line.cs` line 864 at r1](https://reviewable.io/reviews/hypar-io/Elements/942#-NOuxDl07ahUMGfLrB4M:-NOuxDl07ahUMGfLrB4N:b-upnrll) ([raw file](https://github.com/hypar-io/Elements/blob/a6664231fdde9838979df7bd18ba30f1db25176c/Elements/src/Geometry/Line.cs#L864)):*
> ```Smalltalk
>             Vector3 cross = vThis.Cross(vOther);
>             // line vectors are collinear - two segments share the same infinite line on the infinite line.
>             if (cross.IsZero())
> ```

I think we have methods for colinearity on lines, can we use that?
___
*[`Elements/test/LineTests.cs` line 954 at r1](https://reviewable.io/reviews/hypar-io/Elements/942#-NOuxg8kEvNmqckzHCCO:-NOuxg8kEvNmqckzHCCP:bugv8a1) ([raw file](https://github.com/hypar-io/Elements/blob/a6664231fdde9838979df7bd18ba30f1db25176c/Elements/test/LineTests.cs#L954)):*
> ```Smalltalk
>             Vector3 pt = new Vector3(-2.685818406894334, -2.476879934864206, -0.5565494179776103);
>             Vector3 v = new Vector3(-2.3537985903693657, 2.407193267710168, -2.771078003386066);
>             double q1 = -1.7567568535640823, q2 = -0.21721224020356145, q3 = 1.006813808941921, q4 = 2.112519713576212;
> ```

can you use a more descriptive variable name than q1,2,3 ?  



_Code quote (from Elements/src/Geometry/Line.cs):_
```Smalltalk
                // other + dStartStart and this are now in the same plane
                // check if other is fully on one side of this or vice versa,
                // in other words, if  this and `other + dStartStart` intersect on a shred plane
```
___
*[`Elements/test/LineTests.cs` line 955 at r1](https://reviewable.io/reviews/hypar-io/Elements/942#-NOuxo6rCM53aGEm4LnP:-NOuxo6rCM53aGEm4LnQ:b-qn8ow8) ([raw file](https://github.com/hypar-io/Elements/blob/a6664231fdde9838979df7bd18ba30f1db25176c/Elements/test/LineTests.cs#L955)):*
> ```Smalltalk
>             Vector3 v = new Vector3(-2.3537985903693657, 2.407193267710168, -2.771078003386066);
>             double q1 = -1.7567568535640823, q2 = -0.21721224020356145, q3 = 1.006813808941921, q4 = 2.112519713576212;
>             Vector3 pt1 = pt + q1 * v, pt2 = pt + q2 * v, pt3 = pt + q3 * v, pt4 = pt + q4 * v;
> ```

I think put these vectors on separate lines, this is pretty hard to read.
Same in the below sections.  
___
*[`Elements/test/LineTests.cs` line 986 at r1](https://reviewable.io/reviews/hypar-io/Elements/942#-NOuy6wbDG944IYpJTBb:-NOuy6wbDG944IYpJTBc:b92m5d5) ([raw file](https://github.com/hypar-io/Elements/blob/a6664231fdde9838979df7bd18ba30f1db25176c/Elements/test/LineTests.cs#L986)):*
> ```Smalltalk
> 
>             //Two groups of points on two lines.
>             pt = new Vector3(2.798721214152833, -0.3556044049478837, -2.9550511796484766);
> ```

let's make these different sections actually be different DistanceTo tests.  they can run in parallel and the method name can be the description.

**Review by DmytroMuravskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/942)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Geometry/Line.cs` line 864 at r1](https://reviewable.io/reviews/hypar-io/Elements/942#-NOuxDl07ahUMGfLrB4M:-NOxQPfD0jd3x3ESndrk:b3szy2e) ([raw file](https://github.com/hypar-io/Elements/blob/a6664231fdde9838979df7bd18ba30f1db25176c/Elements/src/Geometry/Line.cs#L864)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think we have methods for colinearity on lines, can we use that?
</blockquote></details>

We could, but cross product is answering the same question and it's used in distance finding later anyway. Following strict tolerance is not critical here, as any non-zero difference between two vectors will calculate precise distance.



_Code quote:_
```Smalltalk
cross
```
___
*[`Elements/test/LineTests.cs` line 954 at r1](https://reviewable.io/reviews/hypar-io/Elements/942#-NOuxg8kEvNmqckzHCCO:-NOxgMqg25EgZ8S1lKoV:b-u7ihmr) ([raw file](https://github.com/hypar-io/Elements/blob/a6664231fdde9838979df7bd18ba30f1db25176c/Elements/test/LineTests.cs#L954)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can you use a more descriptive variable name than q1,2,3 ?  
</blockquote></details>

I don't think renaming it to quantity1 will make more difference since it's just a parameter in line equation.
I tried to add extra clarity by comments. Those are experimental way to do tests for sure, just wanted to do something that is similar to real numbers, now just lines on X axis. Tell me if it's better to remove them for good.
___
*[`Elements/test/LineTests.cs` line 955 at r1](https://reviewable.io/reviews/hypar-io/Elements/942#-NOuxo6rCM53aGEm4LnP:-NOxgMQdBnFiBrBoTX0z:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/a6664231fdde9838979df7bd18ba30f1db25176c/Elements/test/LineTests.cs#L955)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think put these vectors on separate lines, this is pretty hard to read.
Same in the below sections.  
</blockquote></details>

Done.
___
*[`Elements/test/LineTests.cs` line 986 at r1](https://reviewable.io/reviews/hypar-io/Elements/942#-NOuy6wbDG944IYpJTBb:-NOxgLfzDeV58JMJ_6If:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/a6664231fdde9838979df7bd18ba30f1db25176c/Elements/test/LineTests.cs#L986)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

let's make these different sections actually be different DistanceTo tests.  they can run in parallel and the method name can be the description.
</blockquote></details>

Done.

**Review by wynged — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/942)* status: 1 change requests, 0 of 1 approvals obtained

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/942)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
