### PR TITLE
Returning absolute value of area

### PR DESCRIPTION
**Pull request by anthonyhauck**
It looks as if I forgot to push this. Sorry.

### CODE REVIEW

**Comment by ikeough** [comment]
Sorry I'm just looping back to this @anthonyhauck. Can you investigate why the build is failing? Then I'll merge.

**Comment by anthonyhauck** [comment]
Will do sometime today.

**Comment by anthonyhauck** [comment]
Previous Centroid method was dependent on negative Areas for correct result in Quadrant 2. Revised Centroid method to much simpler and dependable method of minimizing distances to all Polygon vertices.

**Comment by anthonyhauck** [comment]
Putting these changes into the Floor extrusion change instead.

**Comment by ikeough** [comment]
@anthonyhauck We didn't merge this because I don't think the behavior is wrong. We can fix the documentation to make it clear that the area calculation returns the "signed area" where a negative area means a CCW winding. This gives us two benefits:
- The area of a set of polygons with different windings is simply the sum of its areas.
- A developer can determine the winding of a Polygon by just getting the area, or we can provide a method like `IsClockwise` which checks the sign of the area.

**Pull request closed without merging**
