### PR TITLE
Geometry comparers

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- When working with some geometry I wanted to check if vectors, lines and triangles were contained in some hashsets quickly based on their geometric features.

DESCRIPTION:
- Add IEqualityComparer to line with corresponding tests.
- Add IEqualityComparaer to triangle with corresponding tests.
- Add line IsApproximatelyEqual and HashCode with optional tolerance.
- Add triangle IsApproximatelyEqual and HashCode with optional tolerance.
- Improve speed of Vector3 hashing, and allow specifying tolerance.
- Make Vector3Comparer public
- Add comment to split method on polyline
- Remove 0.9.3 from changelog, we're still working on 0.9.2

TESTING:
- How should a reviewer observe the behavior desired by this pull request?
  
FUTURE WORK:
- don't think so

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/637)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/637)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements/src/Geometry/Line.cs, line 163 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAdj8BE2kELGFzJ6yJ:-MgAdj8BE2kELGFzJ6yK:b-o33yrv) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Line.cs#L163)):*
> ```Smalltalk
>         {
>             var obj = this;
>             // If the direction doesn't matter, then we always sort the end points by X, then Y, then Z to have a consistent basis for forming the hash code.
> ```

This sorting won't work in some cases. Consider this test — it passes if direction-dependent,  but fails if not direction-dependent: 
```
            var line1 = new Line((0, 0), (-0.000001, 3));
            var line2 = new Line((0, 0), (0, 3));
            var hash1 = line1.GetHashCode(false, 0.0001);
            var hash2 = line2.GetHashCode(false, 0.0001);
            Assert.Equal(hash1, hash2);
```
___
*[Elements/src/Geometry/Line.cs, line 192 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgB57S39I4FNtgX9MuI:-MgB57S39I4FNtgX9MuJ:b-fl5la3) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Line.cs#L192)):*
> ```Smalltalk
>                 }
>             }
>             int hash = 17;
> ```

This and similar sections that might result in an integer overflow should be wrapped with `unchecked {}`, in case the user's compiler settings specify `Check for arithmetic overflow / underflow`
___
*[Elements/src/Geometry/Line.cs, line 839 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAqgGYCwqd2YmOdelt:-MgAqgGYCwqd2YmOdelu:bmk4hqa) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Line.cs#L839)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Construct a comparer setting wether the direction matters and optionally the tolerance.
> ```

wether => whether
___
*[Elements/src/Geometry/Polyline.cs, line 805 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAqv7B5z99TZnIAzW8:-MgAqv7C3PABAFIsB686:b5kykr9) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Polyline.cs#L805)):*
> ```Smalltalk
>         /// <param name="points">The points at which to split the polyline.</param>
>         /// <param name="closed">Should the polyline be closed</param>
>         /// <returns>The index of the new vertex.</returns>
> ```

This method returns void, so shouldn't have a <returns>
___
*[Elements/src/Geometry/Triangle.cs, line 106 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAvwwJ7kKfWybzUtBB:-MgAvwwJ7kKfWybzUtBC:bp89kyg) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Triangle.cs#L106)):*
> ```Smalltalk
>         /// Is the provided triangle approximately geometrically equal to this one?
>         /// </summary>
>         public bool IsAlmostEqualTo(Triangle other, bool rotationDependent = false, double precision = Vector3.EPSILON)
> ```

In this case I think we're talking about tolerance rather than precision, no? 
___
*[Elements/src/Geometry/Triangle.cs, line 156 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAlWjs3603FnHlCAcb:-MgAlWjs3603FnHlCAcc:b-glm9el) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Triangle.cs#L156)):*
> ```Smalltalk
>             if (_rotationDependent)
>             {
>                 vertices = triangle.Vertices.OrderBy(v => v.Position.X).ThenBy(v => v.Position.Y).ThenBy(v => v.Position.Z).ToList();
> ```

This has the same issue as `Line.GetHashCode` — ordering will be inconsistent if two edges are slightly tilted off of an axis.
___
*[Elements/src/Geometry/Triangle.cs, line 159 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgBJ1K34Oi-A_b2mBpA:-MgBJ1K4E7Hc_24o7wVA:b4eqb5d) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Triangle.cs#L159)):*
> ```Smalltalk
>             }
> 
>             var alt = 17;
> ```

`unchecked {}`
___
*[Elements/src/Geometry/Vector3.cs, line 46 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAk9B8CL-99keLDxoK:-MgAk9B91KL1AsEebJjU:bt9x253) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Vector3.cs#L46)):*
> ```Smalltalk
>             var alt = 17;
>             var rounded = Rounded(precision);
>             alt = alt * 23 + rounded.X.GetHashCode();
> ```

you could skip a multiplication by just doing `var alt = 391 + rounded.X.GetHashCode();` since you're just multiplying these two ints the same way every time (or maybe just leave it 17 or 23?). Also see the note about `unchecked`. 
___
*[Elements/src/Geometry/Vector3.cs, line 1024 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAxaSH7OKMolBNDW3a:-MgAxaSH7OKMolBNDW3b:bd7s4vy) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Vector3.cs#L1024)):*
technically, this is a violation of the `EqualityComparer` concept. Per the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1.gethashcode?redirectedfrom=MSDN&view=net-5.0#System_Collections_Generic_IEqualityComparer_1_GetHashCode__0_):

> Implementations are required to ensure that if the Equals(T, T) method returns `true` for two objects `x` and `y`, then the value returned by the `GetHashCode(T)` method for `x` must equal the value returned for `y`.

This test fails: 

```
var vector1 = new Vector3(0, 0.00004, 0);
var vector2 = new Vector3(0, 0.00005, 0);
var vector3 = new Vector3(0, 0.00006, 0);

Assert.True(eqComp.Equals(vector1, vector2));
Assert.True(eqComp.Equals(vector2, vector3));
Assert.True(eqComp.GetHashCode(vector1) == eqComp.GetHashCode(vector2));
Assert.True(eqComp.GetHashCode(vector2) == eqComp.GetHashCode(vector3));
```

Per our discussion on slack, for now let's just comment the various EqualityComparer classes and GetHashCode methods with a warning saying "These comparers are strictly speaking imperfect implementations of IEqualityComparer — and so should be used with caution in collections and Linq methods. They may occasionally indicate that two items are distinct when they are within the specified tolerance of each other."

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/637)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/637)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Line.cs, line 163 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAdj8BE2kELGFzJ6yJ:-MgBswtd6sh20aCccu0y:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Line.cs#L163)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

This sorting won't work in some cases. Consider this test — it passes if direction-dependent,  but fails if not direction-dependent: 
```
            var line1 = new Line((0, 0), (-0.000001, 3));
            var line2 = new Line((0, 0), (0, 3));
            var hash1 = line1.GetHashCode(false, 0.0001);
            var hash2 = line2.GetHashCode(false, 0.0001);
            Assert.Equal(hash1, hash2);
```
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Line.cs, line 192 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgB57S39I4FNtgX9MuI:-MgBp6p_3QD0LQwSogd1:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Line.cs#L192)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

This and similar sections that might result in an integer overflow should be wrapped with `unchecked {}`, in case the user's compiler settings specify `Check for arithmetic overflow / underflow`
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Line.cs, line 839 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAqgGYCwqd2YmOdelt:-MgBpC_-6DjkoLK7kobc:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Line.cs#L839)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

wether => whether
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Polyline.cs, line 805 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAqv7B5z99TZnIAzW8:-MgBpHem9M4TV7wB3WT2:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Polyline.cs#L805)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

This method returns void, so shouldn't have a <returns>
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Triangle.cs, line 106 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAvwwJ7kKfWybzUtBB:-MgBpOuJ1KfaXwRCeO-D:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Triangle.cs#L106)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

In this case I think we're talking about tolerance rather than precision, no? 
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Triangle.cs, line 156 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAlWjs3603FnHlCAcb:-MgC2V1I4HEruLiUQq8v:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Triangle.cs#L156)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

This has the same issue as `Line.GetHashCode` — ordering will be inconsistent if two edges are slightly tilted off of an axis.
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Triangle.cs, line 159 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgBJ1K34Oi-A_b2mBpA:-MgBp_0BClCeOQyBc9wK:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Triangle.cs#L159)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

`unchecked {}`
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Vector3.cs, line 46 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAk9B8CL-99keLDxoK:-MgBpp1BB-nN-AQkpwL4:bvhawbb) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Vector3.cs#L46)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

you could skip a multiplication by just doing `var alt = 391 + rounded.X.GetHashCode();` since you're just multiplying these two ints the same way every time (or maybe just leave it 17 or 23?). Also see the note about `unchecked`. 
</blockquote></details>

done. I can do it for the first one, but after that it's building upon the previous hash.
___
*[Elements/src/Geometry/Vector3.cs, line 1024 at r1](https://reviewable.io/reviews/hypar-io/elements/637#-MgAxaSH7OKMolBNDW3a:-MgC5n0l76L5DbRvspoG:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/5f81c0443c556f84c7fdf61313495314205a9bce/Elements/src/Geometry/Vector3.cs#L1024)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

technically, this is a violation of the `EqualityComparer` concept. Per the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1.gethashcode?redirectedfrom=MSDN&view=net-5.0#System_Collections_Generic_IEqualityComparer_1_GetHashCode__0_):

> Implementations are required to ensure that if the Equals(T, T) method returns `true` for two objects `x` and `y`, then the value returned by the `GetHashCode(T)` method for `x` must equal the value returned for `y`.

This test fails: 

```
var vector1 = new Vector3(0, 0.00004, 0);
var vector2 = new Vector3(0, 0.00005, 0);
var vector3 = new Vector3(0, 0.00006, 0);

Assert.True(eqComp.Equals(vector1, vector2));
Assert.True(eqComp.Equals(vector2, vector3));
Assert.True(eqComp.GetHashCode(vector1) == eqComp.GetHashCode(vector2));
Assert.True(eqComp.GetHashCode(vector2) == eqComp.GetHashCode(vector3));
```

Per our discussion on slack, for now let's just comment the various EqualityComparer classes and GetHashCode methods with a warning saying "These comparers are strictly speaking imperfect implementations of IEqualityComparer — and so should be used with caution in collections and Linq methods. They may occasionally indicate that two items are distinct when they are within the specified tolerance of each other."

</blockquote></details>

Done.

**Comment by wynged** [comment]
This plan is too flawed.  tolerance while creating HashCodes is problematic because there will always be rounding issues that create boundary conditions where two things thing really should be identical are not. These images highlight the problem.

In HashCodes everything is "binned" which results in strange results.  The red and blue dots are "different" but the blue and green dots are the same.
image

image

**Pull request closed without merging**
