### PR TITLE
Added method that returns cell geometry as set of profiles;

### PR DESCRIPTION
**Pull request by katehryhorenko**
BACKGROUND:
Grid2d.GetTrimmedCellGeometry returns list of polygons. It works good, but If cell has void that is completely inside the cell, the additional analyze should be done to use retrieved geometry.

DESCRIPTION:
GetTrimmedCellProfiles method returns cell geometry as set of profiles, where internal polygons are added as voids

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/693)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Let's add a unit test in `Grid2dTests` for this new method. And don't forget to update the changelog :) 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/693#-:-MnRnZroD2Pl5AG4QPny:b8vjzle)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[Elements/src/Spatial/Grid2d.cs, line 741 at r1](https://reviewable.io/reviews/hypar-io/elements/693#-MnRnH5f6GIkcIvOaXmD:-MnRnH5f6GIkcIvOaXmE:b-5dr77w) ([raw file](https://github.com/hypar-io/elements/blob/a83d0f4f6ed960bf62082bc30a0143ecd84e57a6/Elements/src/Spatial/Grid2d.cs#L741)):*
> ```Smalltalk
>             {
>                 var profiles = new List<Profile>();
>                 var outerRectangles = trimmedRect.Where(rect => !rect.IsClockWise());
> ```

Nit: Since these are not guaranteed to be rectangles after the trim operation, let's call these vars `outerCurves` and `innerCurves` or `outerLoops` and `innerLoops` or similar — and rename the inner var from `rect`.

**Review by katehryhorenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/693)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements/src/Spatial/Grid2d.cs, line 741 at r1](https://reviewable.io/reviews/hypar-io/elements/693#-MnRnH5f6GIkcIvOaXmD:-MnSPAPl1OLxrS60uRKa:b-8fx2u7) ([raw file](https://github.com/hypar-io/elements/blob/a83d0f4f6ed960bf62082bc30a0143ecd84e57a6/Elements/src/Spatial/Grid2d.cs#L741)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Nit: Since these are not guaranteed to be rectangles after the trim operation, let's call these vars `outerCurves` and `innerCurves` or `outerLoops` and `innerLoops` or similar — and rename the inner var from `rect`. 
</blockquote></details>

:+1:

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/693)* status: 1 change requests, 0 of 1 approvals obtained

**Review by katehryhorenko — COMMENTED** [review]
I added two tests and updated changelog. Please verify if I did it right :)

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/693#-:-Mo0j-8r3v7D5DOfHUCz:b-o2njrt)* status: 1 change requests, 0 of 1 approvals obtained

**Review by andrewheumann — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/693)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by andrewheumann — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/693#-:-Mo4oArP6x6r4vgMxdp5:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
