### PR TITLE
Fix GLB Vertex normals

### PR DESCRIPTION
**Pull request by andrewheumann**
BACKGROUND:
- Some shapes were showing up inexplicably dark in the viewport, despite having been consistently constructed. 
image
- This was because certain meshes had incorrect vertex normals, as verified in a GLTF debugger:
image 
- This was due to an invalid assumption in the code: that a normal calculated from the first three vertices of a polygon would necessarily be the correct normal for that face. In fact, if the polygon face was non-convex, and the first three vertices fell within a concave portion, then the "triangle" we were using to calculate the normal would be wound clockwise relative to the polygon it came from. 
image

DESCRIPTION:
- Switches to using a tessellated triangle as the basis for the normal, which is guaranteed to lie within the CSG face polygon and be correctly wound.

TESTING:
- I verified that a glb generated after this fix has its normals correctly oriented, and all volumes are shaded consistently. 
image
 
REQUIRED:
- [X] All changes are up to date in `CHANGELOG.md`.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/652)

### CODE REVIEW

**Review by wynged — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/652)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by wynged — CHANGES_REQUESTED** [review]
add a test?

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/652#-:-MhTrFgZAsxxVcjX6oUo:b-hukd2u)* status: 1 change requests, 0 of 1 approvals obtained

**Review by wynged — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/652)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/652)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by andrewheumann — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/652)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
