### PR TITLE
Add Polygon.SharedSegments()

### PR DESCRIPTION
**Pull request by cdriesler**
BACKGROUND:
- I need the ability to find shared segments between polygons for another function. I thought it would be useful to include in elements.

DESCRIPTION:
- Adds a static `Polygon.SharedSegments()` method.
- Given two polygons, it returns a set of tuples for any shared segments
  - A 'shared segment' means the start and end points are the same (although possibly reversed)
- The tuple is of the segment indices for their respective polygons. They can be different, hence tuple instead of just `int`.

TESTING:
Tests in code are:

- Concentric polygon circles return no results
- Intersecting polygon circles return no results
- Identical polygon circles return ten accurate results
- Identical polygon circles (one reversed) return ten accurate results
- A pair of squares with one shared edge return one result
- A pair of squares with touching (but not identical) edges returns no results

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/488)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Suggestion: 
This code applies nearly perfectly for Polylines too, from which Polygon inherits; is it possible to move it into Polyline?  There might need to be a few subtle conditional checks (whether to loop past the last vertex, etc) but it seems like most of it would hold. Happy to approve without this change, but seems like it would be useful!

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/488#-:-MReBC1e0KhyVrcCzZfY:b-g2b26j)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cdriesler)

___
*[Elements/src/Geometry/Polygon.cs, line 1013 at r1](https://reviewable.io/reviews/hypar-io/elements/488#-MRe9nXG410VuJcBaX2K:-MRe9nXG410VuJcBaX2L:b-9xwymf) ([raw file](https://github.com/hypar-io/elements/blob/ef2879af65029cf0fd20fbc96124c5844909950b/Elements/src/Geometry/Polygon.cs#L1013)):*
> ```Smalltalk
>         /// <param name="b">The second polygon to compare.</param>
>         /// <returns>Returns a list of tuples of indices for the segments that match in each polygon.</returns>
>         public static List<(int, int)> SharedSegments(Polygon a, Polygon b)
> ```

I like to use named tuples in a case like this — List<(int indexOnA, int indexOnB)> — then whoever receives the result can get result.indexOnA instead of Item1

**Review by cdriesler — COMMENTED** [review]
Agreed, moved it over and added an optional flag.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/488#-:-MResKLsEoa8uqa81vFj:bngtrdj)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Polygon.cs, line 1013 at r1](https://reviewable.io/reviews/hypar-io/elements/488#-MRe9nXG410VuJcBaX2K:-MResNZh6S9oLDVn5ueX:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/ef2879af65029cf0fd20fbc96124c5844909950b/Elements/src/Geometry/Polygon.cs#L1013)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I like to use named tuples in a case like this — List<(int indexOnA, int indexOnB)> — then whoever receives the result can get result.indexOnA instead of Item1
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/488)* status: all files reviewed, 1 unresolved discussion (waiting on @cdriesler)

___
*[Elements/test/PolylineTests.cs, line 56 at r3](https://reviewable.io/reviews/hypar-io/elements/488#-MRtWN1m4WYing8rXvPg:-MRtWN1m4WYing8rXvPh:b-1s5xm3) ([raw file](https://github.com/hypar-io/elements/blob/991b78341fff80a89319f066cc1d9464a8b29fc3/Elements/test/PolylineTests.cs#L56)):*
> ```Smalltalk
> 
>         [Fact]
>         public void SharedSegments_OpenMirroredSquares_OneResult()
> ```

should be "NoResults" not "OneResult," correct?

**Review by cdriesler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/488)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

___
*[Elements/test/PolylineTests.cs, line 56 at r3](https://reviewable.io/reviews/hypar-io/elements/488#-MRtWN1m4WYing8rXvPg:-MRtzx4n8qTSE40cg-aG:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/991b78341fff80a89319f066cc1d9464a8b29fc3/Elements/test/PolylineTests.cs#L56)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

should be "NoResults" not "OneResult," correct? 
</blockquote></details>

Done.

**Pull request merged**
