### PR TITLE
first pass dxf

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- We want to make DXFs from Hypar models.

DESCRIPTION:
- Add a project dedicated to the creation of DXF files from elements.
- It allows for us to continue adding Converters for each type of element in a model.

TESTING:
- The test results in a dxf that looks like this.  A super impressive rectangle.
image

FUTURE WORK:
- We need to accommodate more types by adding converters.
- We should make use of the DrawingRange element during render.
- Make methods that will let users add their own converters.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/596)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Code looks good! I think it would be good to add XML comments to this before submitting — I've made the mistake of thinking "I'll do it later" and then it becomes a huge task. We should get it started now while it's still manageable. 

> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/596#-:-MbBoj9C-BnbazCV5cRN:b-6oun46)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements.DXF/src/DxfConverter.cs, line 11 at r1](https://reviewable.io/reviews/hypar-io/elements/596#-MbBp2Tr6RlmypkerYfh:-MbBp2Tr6RlmypkerYfi:b-dllaq) ([raw file](https://github.com/hypar-io/elements/blob/fdcec4b55dad8180a16cc21f199c78065667596c/Elements.DXF/src/DxfConverter.cs#L11)):*
> ```Smalltalk
>         public Vector3 Direction;
>         public Vector3 Origin;
>         public double Depth;
> ```

Maybe consider Transform + Depth to capture this?

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/596)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

**Review by wynged — COMMENTED** [review]
done, good idea.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/596#-:-MbH8cPW1fc2H3YJEVna:bdcmr5b)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements.DXF/src/DxfConverter.cs, line 11 at r1](https://reviewable.io/reviews/hypar-io/elements/596#-MbBp2Tr6RlmypkerYfh:-MbH8f2n37iTaZpPsWgA:b-ie073y) ([raw file](https://github.com/hypar-io/elements/blob/fdcec4b55dad8180a16cc21f199c78065667596c/Elements.DXF/src/DxfConverter.cs#L11)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Maybe consider Transform + Depth to capture this? 
</blockquote></details>

done, yup makes sense.

**Review by andrewheumann — CHANGES_REQUESTED** [review]
One last Q and we’re good!

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/596#-:-MbHA27U2s2FtSlGVGgU:b8f1sf3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[Elements.DXF/src/ModelToDxf.cs, line 5 at r2](https://reviewable.io/reviews/hypar-io/elements/596#-MbH9vBlCxyFKmVcorIi:-MbH9vBm-jbaR-17lmP1:blyvot4) ([raw file](https://github.com/hypar-io/elements/blob/cac97b8a463bbf4062de1dfb453bc80c5b786367/Elements.DXF/src/ModelToDxf.cs#L5)):*
> ```Smalltalk
> using System.IO;
> using Elements;
> using Microsoft.Win32.SafeHandles;
> ```

Is this import used?

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/596)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[Elements.DXF/src/ModelToDxf.cs, line 5 at r2](https://reviewable.io/reviews/hypar-io/elements/596#-MbH9vBlCxyFKmVcorIi:-MbIJB0_E86kQytykdU5:bbp53re) ([raw file](https://github.com/hypar-io/elements/blob/cac97b8a463bbf4062de1dfb453bc80c5b786367/Elements.DXF/src/ModelToDxf.cs#L5)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Is this import used?
</blockquote></details>

Done. ugh no.

**Review by andrewheumann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/596)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/596)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by andrewheumann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/596)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
