### PR TITLE
Fix network region recognition.

### PR DESCRIPTION
**Pull request by ikeough**
BACKGROUND:
While creating networks of walls in Hypar, I attempted to recognize closed areas as rooms by using `Newtork.FindAllClosedRegions`. I found for the shape pictured that the red cell would not be found. This was because the traversal algorithm was previously visiting all the nodes in such a way as to ignore 4 and 5 as having been previously traversed, resulting in an unclosed region.
 
image

DESCRIPTION:
This PR adds a new traversal method, `Network.TraverseLeftWithoutLeaves`, and uses this traversal method in the `Network.FindAllClosedRegions` method. This new traversal method ignores leaf nodes, both external to the graph, and internal to a cell, resulting in less traversals of unclosed paths. It reliably "turns left" resulting in proper closed regions.

TESTING:
- See the `NetworkTests.FourQuadrantsWithPointerFindsCorrectNumberOfClosedRegions` test.
  
FUTURE WORK:
- Network region recognition still does not work on rooms with a concave shape.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/925)

### CODE REVIEW

**Comment by ikeough** [comment]
This may also fix #900.

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Works great except for a couple cases, which can be left for future work. 

You've already identified that Concave shapes are an issue — this could be just another manifestation of the same problem, but this will fail to find both regions: 

```csharp
var lines = new List<Line> {
    new Line((10.00, 0.00), (10.00, 10.00)),
    new Line((10.00, 10.00), (-0.00, 10.00)),
    new Line((-0.00, 10.00), (0.00, 0.00)),
    new Line((0.00, 0.00), (10.00, 0.00)),
    new Line((-2.00, 6.00), (12.00, 6.00)),
    new Line((5.00, -2.00), (4.00, 1.00)),
    new Line((4.00, 1.00), (6.00, 2.00)),
    new Line((6.00, 2.00), (5.00, 4.00)),
};
```

This one misses a region, returning 4 instead of 5, even though they should all be convex:

```csharp
var lines = new List<Line> {
    new Line((10.00, 0.00), (10.00, 10.00)),
    new Line((10.00, 10.00), (-0.00, 10.00)),
    new Line((-0.00, 10.00), (0.00, 0.00)),
    new Line((0.00, 0.00), (10.00, 0.00)),
    new Line((-2.00, 6.00), (12.00, 6.00)),
    new Line((-2.96, -0.16), (2.13, 2.51)),
    new Line((2.13, 2.51), (7.81, 2.51)),
    new Line((7.81, 2.51), (13.11, 0.28)),
    new Line((7.81, 2.51), (11.60, 4.88)),
    new Line((2.13, 2.51), (-1.46, 4.62)),
};
```

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/925#-:-NII6YTJ9fGbvwAPPK-4:bif977o)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @katehryhorenko)

___
*[`Elements/src/Search/Network.cs` line 555 at r2](https://reviewable.io/reviews/hypar-io/elements/925#-NIHxTmX6DodC--01oeR:-NIHxTmX6DodC--01oeS:b-3l68rd) ([raw file](https://github.com/hypar-io/elements/blob/67d4f99df1ae148c81721e1e27ea99f4c58a5dd1/Elements/src/Search/Network.cs#L555)):*
> ```Smalltalk
>         /// <summary>
>         /// Traverse a network following the left-most candidate edge relative to the current edge.
>         /// leaf nodes.
> ```

this comment was maybe unfinished?
___
*[`Elements/src/Search/Network.cs` line 559 at r2](https://reviewable.io/reviews/hypar-io/elements/925#-NII-T3O43oza_3C5kp_:-NII-T3O43oza_3C5kpa:b5r7kp5) ([raw file](https://github.com/hypar-io/elements/blob/67d4f99df1ae148c81721e1e27ea99f4c58a5dd1/Elements/src/Search/Network.cs#L559)):*
> ```Smalltalk
>         /// <param name="traversalData">Data about the current step of the traversal.</param>
>         /// <param name="allNodeLocations">A collection of all node locations in the network.</param>
>         /// <param name="visitedEdges">A collection of previously visited edge.</param>
> ```

previously visited edges
___
*[`Elements/src/Search/Network.cs` line 593 at r2](https://reviewable.io/reviews/hypar-io/elements/925#-NIIQXm9-mQbHdA3XhTh:-NIIQXmAAwAKzyOaYZIG:b-if0tox) ([raw file](https://github.com/hypar-io/elements/blob/67d4f99df1ae148c81721e1e27ea99f4c58a5dd1/Elements/src/Search/Network.cs#L593)):*
> ```Smalltalk
> 
>                 var localEdge = (allNodeLocations[e] - allNodeLocations[traversalData.currentIndex]).Unitized();
>                 var angle = 180 - baseEdge.PlaneAngleTo(localEdge);
> ```

Could be future work, but this embeds an assumption that the network is 2D and in the XY plane. Can we at least leave a comment w/ a TODO to accept a normal or otherwise support non-planar networks?

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/925)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @katehryhorenko)

___
*[`Elements/src/Search/Network.cs` line 498 at r2](https://reviewable.io/reviews/hypar-io/elements/925#-NIJ7W-y26cW50u0PLXT:-NIJ7W-y26cW50u0PLXU:b-3i5tc) ([raw file](https://github.com/hypar-io/elements/blob/67d4f99df1ae148c81721e1e27ea99f4c58a5dd1/Elements/src/Search/Network.cs#L498)):*
> ```Smalltalk
>         /// Traverse a network following the smallest plane angle between the current
>         /// edge and the next candidate edge.
>         /// leaf nodes.
> ```

unfinished comment?

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/925)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann and @katehryhorenko)

___
*[`Elements/src/Search/Network.cs` line 498 at r2](https://reviewable.io/reviews/hypar-io/elements/925#-NIJ7W-y26cW50u0PLXT:-NIKAogB-1oDHke0M2OD:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/67d4f99df1ae148c81721e1e27ea99f4c58a5dd1/Elements/src/Search/Network.cs#L498)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

unfinished comment?
</blockquote></details>

Done.
___
*[`Elements/src/Search/Network.cs` line 555 at r2](https://reviewable.io/reviews/hypar-io/elements/925#-NIHxTmX6DodC--01oeR:-NIKAp_m0Cf_qHPmZKJ1:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/67d4f99df1ae148c81721e1e27ea99f4c58a5dd1/Elements/src/Search/Network.cs#L555)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

this comment was maybe unfinished?
</blockquote></details>

Done.
___
*[`Elements/src/Search/Network.cs` line 559 at r2](https://reviewable.io/reviews/hypar-io/elements/925#-NII-T3O43oza_3C5kp_:-NIKAu6B4ad5yQwARV4v:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/67d4f99df1ae148c81721e1e27ea99f4c58a5dd1/Elements/src/Search/Network.cs#L559)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

previously visited edges
</blockquote></details>

Done.
___
*[`Elements/src/Search/Network.cs` line 593 at r2](https://reviewable.io/reviews/hypar-io/elements/925#-NIIQXm9-mQbHdA3XhTh:-NIKMbzm8djZhg1BI1A8:b-7gbqdj) ([raw file](https://github.com/hypar-io/elements/blob/67d4f99df1ae148c81721e1e27ea99f4c58a5dd1/Elements/src/Search/Network.cs#L593)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Could be future work, but this embeds an assumption that the network is 2D and in the XY plane. Can we at least leave a comment w/ a TODO to accept a normal or otherwise support non-planar networks? 
</blockquote></details>

I've added a clarification to the `Network.FromSegmentableItems` method's docs. That's where the assumption is embedded first as the algorithm uses a line sweep on planar line segments to construct the network.

**Comment by ikeough** [comment]
@andrewheumann 
image
image
image

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/925)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
