### PR TITLE
RepresentationInstances and GLB serialization

### PR DESCRIPTION
**Pull request by katehryhorenko**
BACKGROUND:
Multiple representations!

DESCRIPTION:

- `ElementRepresentation` is a base class for all representations
- `GeometricElement.RepresentationInstances` - collection of representation instances, where each instance contains Representation, Material and the set of representation types
- RepresentationTypes and if this representation is default is kept inside glb extensions
- `GeometricElement.RepresentationInstances` is ignored during serialization to json

TESTING:
https://hypar.io/workflows/665b2d73-b927-461e-bed8-7e4786ca7c44
  
FUTURE WORK:
- Serialization to IFC
- Include Representation Instances to GeometricElement.Intersection method

REQUIRED:
- [ ] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- I'll be glad to discuss any of these changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1028)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1028)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/Model.cs` line 40 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NeKG1i7-S_qojTd2UrM:-NeKG1i7-S_qojTd2UrN:b-es0cg9) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Model.cs#L40)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Collection of subelements frpm shared objects.
> ```

frpm => from
___
*[`Elements/src/Model.cs` line 42 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NeNz_rf4DtmgIiOj9WJ:-NeNz_rf4DtmgIiOj9WK:breupt0) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Model.cs#L42)):*
> ```Smalltalk
>         /// Collection of subelements frpm shared objects.
>         /// 
>         /// We do not serialize shared objects to json, but we do serialize them to other formats 
> ```

"but we do include them in other formats like gltf"
___
*[`Elements/src/Model.cs` line 45 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NeSjRXL-i_V1wegmPC8:-NeSjRXL-i_V1wegmPC9:b16xg88) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Model.cs#L45)):*
> ```Smalltalk
>         /// </summary>
>         [JsonIgnore]
>         public System.Collections.Generic.IDictionary<Guid, Element> SubElementsFromSharedObjects { get; set; } = new System.Collections.Generic.Dictionary<Guid, Element>();
> ```

Can we update the comment here to explain a bit more about what this is for? It's not actually storing the SharedObjects, it's storing the elements that SharedObjects may point to (which may also be in `Elements`, if an element also points to them) — is that correct? just want to make sure I understand! 
___
*[`Elements/src/CoreModels/RepresentationInstance.cs` line 62 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePOMxJDK05fnLpF-Dt:-NePOMxJDK05fnLpF-Du:b-ww81go) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/CoreModels/RepresentationInstance.cs#L62)):*
> ```Smalltalk
>         /// <summary>
>         /// Indicates if this element representation isntance is displayed by default. 
>         /// Element can have several default represemtations.
> ```

represemtations => representations
isntance => instance
___
*[`Elements/src/CoreModels/RepresentationInstance.cs` line 67 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePOWo60uPsX63YH-xS:-NePOWo60uPsX63YH-xT:b-pnnfxi) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/CoreModels/RepresentationInstance.cs#L67)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Calculates representation istance hash code including material and element opening information.
> ```

instance



_Code quote:_
```Smalltalk
istance
```
___
*[`Elements/src/CoreModels/SharedObject.cs` line 7 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePOszbDUAgOqxLMnOc:-NePOszbDUAgOqxLMnOd:bxi2mnl) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/CoreModels/SharedObject.cs#L7)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// An object which is identified with a unique identifier.
> ```

An object with a unique identifier which is shared by one or more elements, and excluded from element serialization.
___
*[`Elements/src/Representations/CurveRepresentation.cs` line 8 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePP7p2DJzw-CVSTwVf:-NePP7p2DJzw-CVSTwVg:bmk67nc) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Representations/CurveRepresentation.cs#L8)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// The element representation that represented like a curve.
> ```

An element representation displayed as an open or closed continuous curve. 
___
*[`Elements/src/Representations/CurveRepresentation.cs` line 45 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePPGd6-PcUJ4vt1AM9:-NePPGd6-PcUJ4vt1AMA:bfayuqp) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Representations/CurveRepresentation.cs#L45)):*
> ```Smalltalk
>         /// <returns>
>         /// True if there is graphicsbuffers data applicable to add, false otherwise.
>         /// Out variables should be ignored if the return value is false.
> ```

if this is inherited from ElementRepresentation, I think we can use `<inheritdoc/>`

**Review by andrewheumann — COMMENTED** [review]
Generally looks good! Just a few minor comments, mostly about documentation! 

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1028#-:-NeSr9ZZ2mqFTk5ON9i5:b-65py1g)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

**Review by katehryhorenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1028)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[`Elements/src/Model.cs` line 40 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NeKG1i7-S_qojTd2UrM:-NecTwPG3pc8m5cGwpui:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Model.cs#L40)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

frpm => from
</blockquote></details>

Done.
___
*[`Elements/src/Model.cs` line 42 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NeNz_rf4DtmgIiOj9WJ:-NecU7vHC0plkERo5GZC:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Model.cs#L42)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

"but we do include them in other formats like gltf"
</blockquote></details>

Done.
___
*[`Elements/src/Model.cs` line 45 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NeSjRXL-i_V1wegmPC8:-NecVlUqBx44OY8hnThB:b-862gvd) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Model.cs#L45)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

Can we update the comment here to explain a bit more about what this is for? It's not actually storing the SharedObjects, it's storing the elements that SharedObjects may point to (which may also be in `Elements`, if an element also points to them) — is that correct? just want to make sure I understand!
</blockquote></details>

Yes, you are right. It contains all Materials collected from the RepresentatioInstances, profiles from the SolidRepresentations. Everything that is used by Representations and what we potentially will need to  create gltf
___
*[`Elements/src/CoreModels/RepresentationInstance.cs` line 62 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePOMxJDK05fnLpF-Dt:-NecXpAq73hnGKcE6dsW:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/CoreModels/RepresentationInstance.cs#L62)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

represemtations => representations
isntance => instance
</blockquote></details>

Done.
___
*[`Elements/src/CoreModels/RepresentationInstance.cs` line 67 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePOWo60uPsX63YH-xS:-NecXphk-rtrh0YFLPbm:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/CoreModels/RepresentationInstance.cs#L67)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

instance
</blockquote></details>

Done.
___
*[`Elements/src/CoreModels/SharedObject.cs` line 7 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePOszbDUAgOqxLMnOc:-NecXya67xS_UnTmrO8T:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/CoreModels/SharedObject.cs#L7)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

An object with a unique identifier which is shared by one or more elements, and excluded from element serialization.
</blockquote></details>

Done.
___
*[`Elements/src/Representations/CurveRepresentation.cs` line 8 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePP7p2DJzw-CVSTwVf:-NecY4QG8QFigVMJUj0C:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Representations/CurveRepresentation.cs#L8)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

An element representation displayed as an open or closed continuous curve.
</blockquote></details>

Done.
___
*[`Elements/src/Representations/CurveRepresentation.cs` line 45 at r1](https://reviewable.io/reviews/hypar-io/Elements/1028#-NePPGd6-PcUJ4vt1AM9:-NecZxY434qdV8Mge54c:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/35c02a02253e34eab7f26a99e64eacd787f8784d/Elements/src/Representations/CurveRepresentation.cs#L45)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

if this is inherited from ElementRepresentation, I think we can use `<inheritdoc/>`
</blockquote></details>

Done.

**Review by katehryhorenko — COMMENTED** [review]
Thanks! I would never find this errors :heart: 

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1028#-:-Nec_JOACwUOWo27S3mp:b-mq345z)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

**Review by andrewheumann — APPROVED** [review]
One more little comment adjustment but :shipit: !! 

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1028#-:-Negt-CS9COSWlkmaZpy:bhe6y5o)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/Model.cs` line 43 at r2](https://reviewable.io/reviews/hypar-io/Elements/1028#-NegsGdrCgmlx6RXRO4S:-NegsGdrCgmlx6RXRO4T:b-cnne76) ([raw file](https://github.com/hypar-io/Elements/blob/63cd7e04a2d0ce9bdeaec9c8436ca208962c69e9/Elements/src/Model.cs#L43)):*
>This collection contains all elements referenced directly by RepresentationInstances, such as Materials and Profiles. These objects affect representation appearance and may be used at glTF creation time.

**Review by katehryhorenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1028)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @andrewheumann)

___
*[`Elements/src/Model.cs` line 43 at r2](https://reviewable.io/reviews/hypar-io/Elements/1028#-NegsGdrCgmlx6RXRO4S:-NehRuKs55iPwGBVRMvn:b-896fix) ([raw file](https://github.com/hypar-io/Elements/blob/63cd7e04a2d0ce9bdeaec9c8436ca208962c69e9/Elements/src/Model.cs#L43)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

>This collection contains all elements referenced directly by RepresentationInstances, such as Materials and Profiles. These objects affect representation appearance and may be used at glTF creation time.
</blockquote></details>

Done.

**Pull request merged**
