### PR TITLE
Serialize Vector, UV, and Color to Arrays

### PR DESCRIPTION
**Pull request by ikeough**
BACKGROUND:
This is the second PR in support of #454. 

For the completion of the `Representation` work, we will add a `MeshRepresentation` which will serialize its mesh. Serializing meshes to JSON should be done as economically as possible given that each vertex has a position, color, normal, and index. Additionally, meshes do not currently serialize AT ALL, due to reference loops created between `Triangle` and `Vertex` types.

DESCRIPTION:
This PR adds JSON converters to serialize `Vector3`, `UV`, and `Color` types as arrays instead of objects, reducing the character count in the JSON which, while small, makes a big difference for mesh serialization. It also adds converters for `Mesh` and `Vertex` which enable serialization of meshes without looping references by serializing vertex references on triangles by their index instead of by reference. The vector, uv, and color converters handle deserialization from the old serialization format as well. The mesh, and vertex converters do not as we did not previously serialize those types.

An example of the newly formed JSON (indented for clarity):
```json
{
    "Transform": {
        "Matrix": {
            "Components": [
                1.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1.0,
                0.0
            ]
        }
    },
    "Elements": {
        "57af66cb-f72a-45c6-b654-719e79234185": {
            "discriminator": "Elements.Geometry.Profiles.WideFlangeProfile",
            "d": 0.28193999999999997,
            "tw": 0.017272,
            "bf": 0.26162,
            "tf": 0.028448,
            "Perimeter": {
                "discriminator": "Elements.Geometry.Polygon",
                "Vertices": [
                    [
                        -0.13081,
                        0.14096999999999998,
                        0.0
                    ],
                    [
                        -0.13081,
                        0.11252199999999998,
                        0.0
                    ],
                    [
                        -0.008636,
                        0.11252199999999998,
                        0.0
                    ],
                    [
                        -0.008636,
                        -0.11252199999999998,
                        0.0
                    ],
                    [
                        -0.13081,
                        -0.11252199999999998,
                        0.0
                    ],
                    [
                        -0.13081,
                        -0.14096999999999998,
                        0.0
                    ],
                    [
                        0.13081,
                        -0.14096999999999998,
                        0.0
                    ],
                    [
                        0.13081,
                        -0.11252199999999998,
                        0.0
                    ],
                    [
                        0.008636,
                        -0.11252199999999998,
                        0.0
                    ],
                    [
                        0.008636,
                        0.11252199999999998,
                        0.0
                    ],
                    [
                        0.13081,
                        0.11252199999999998,
                        0.0
                    ],
                    [
                        0.13081,
                        0.14096999999999998,
                        0.0
                    ]
                ]
            },
            "Voids": [],
            "Id": "57af66cb-f72a-45c6-b654-719e79234185",
            "Name": "W10x100"
        },
        "13bef3c8-64c5-4283-a471-2571239cc14d": {
            "discriminator": "Elements.Material",
            "Color": [
                0.6,
                0.5,
                0.5,
                1.0
            ],
            "SpecularFactor": 0.0,
            "GlossinessFactor": 0.0,
            "Unlit": false,
            "DoubleSided": false,
            "Id": "13bef3c8-64c5-4283-a471-2571239cc14d",
            "Name": "steel"
        },
        "42640550-8436-468f-a699-2519e9cc70ee": {
            "discriminator": "Elements.Column",
            "Location": [
                0.0,
                0.0,
                0.0
            ],
            "Height": 3.0,
            "Curve": {
                "discriminator": "Elements.Geometry.Line",
                "Start": [
                    0.0,
                    0.0,
                    3.0
                ],
                "End": [
                    0.0,
                    0.0,
                    0.0
                ]
            },
            "StartSetback": 0.0,
            "EndSetback": 0.0,
            "Profile": "57af66cb-f72a-45c6-b654-719e79234185",
            "Rotation": 0.0,
            "Transform": {
                "Matrix": {
                    "Components": [
                        1.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        1.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        1.0,
                        0.0
                    ]
                }
            },
            "Material": "13bef3c8-64c5-4283-a471-2571239cc14d",
            "Representation": {
                "SolidOperations": [
                    {
                        "discriminator": "Elements.Geometry.Solids.Sweep",
                        "Profile": "974b0afa-27c3-43c8-8124-03610073eeaa",
                        "Curve": {
                            "discriminator": "Elements.Geometry.Line",
                            "Start": [
                                0.0,
                                0.0,
                                3.0
                            ],
                            "End": [
                                0.0,
                                0.0,
                                0.0
                            ]
                        },
                        "StartSetback": 0.0,
                        "EndSetback": 0.0,
                        "IsVoid": false,
                        "LocalTransform": null
                    }
                ]
            },
            "IsElementDefinition": false,
            "Id": "42640550-8436-468f-a699-2519e9cc70ee",
            "Name": null
        }
    }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/472)

### CODE REVIEW

**Comment by andrewheumann** [comment]
Will it be possible to still deserialize from the old formats? This will be important to maintain compatibility with old functions since the front end also needs to serialize these values for inputs.

**Comment by ikeough** [comment]
>The vector, uv, and color converters handle deserialization from the old serialization format as well.

**Comment by andrewheumann** [comment]
Yay! Sorry I missed that in my first skim :)

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/472)* status: all files reviewed, 4 unresolved discussions (waiting on @ikeough)

___
*[Elements/src/Serialization/JSON/ColorConverter.cs, line 22 at r2](https://reviewable.io/reviews/hypar-io/elements/472#-MPnh4bW3KuNBLzriHV6:-MPnh4bXDbzsXZnDeTV9:brqll5d) ([raw file](https://github.com/hypar-io/elements/blob/2b28b563cc1e5cc989c56cb9974a3923d84a7f57/Elements/src/Serialization/JSON/ColorConverter.cs#L22)):*
> ```Smalltalk
>         public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
>         {
>             try
> ```

Is there a way to inspect the reader contents and disambiguate without this try/catch — maybe w/ `JToken.Parse(content)`? I would consider encountering "old format" part of normal execution, and C# best practices suggest not using try/catch in conditions that occur frequently or in the course of normal execution. 
___
*[Elements/src/Serialization/JSON/UVConverter.cs, line 23 at r2](https://reviewable.io/reviews/hypar-io/elements/472#-MPni6Cc1JXPon75HjEY:-MPni6CdAE4SubWtTAbD:bdvk0ys) ([raw file](https://github.com/hypar-io/elements/blob/2b28b563cc1e5cc989c56cb9974a3923d84a7f57/Elements/src/Serialization/JSON/UVConverter.cs#L23)):*
> ```Smalltalk
>         {
> 
>             try
> ```

see note on color converter about try/ catch
___
*[Elements/src/Serialization/JSON/Vector3Converter.cs, line 24 at r2](https://reviewable.io/reviews/hypar-io/elements/472#-MPniE75DpMvRm4WYCdu:-MPniE75DpMvRm4WYCdv:bl5ghp4) ([raw file](https://github.com/hypar-io/elements/blob/2b28b563cc1e5cc989c56cb9974a3923d84a7f57/Elements/src/Serialization/JSON/Vector3Converter.cs#L24)):*
> ```Smalltalk
>         public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
>         {
>             try
> ```

see note in color converter about try/catch
___
*[Elements/src/Serialization/JSON/VertexConverter.cs, line 23 at r2](https://reviewable.io/reviews/hypar-io/elements/472#-MPnjbQV70iNhv386gv1:-MPnjbQV70iNhv386gv2:bzgfjef) ([raw file](https://github.com/hypar-io/elements/blob/2b28b563cc1e5cc989c56cb9974a3923d84a7f57/Elements/src/Serialization/JSON/VertexConverter.cs#L23)):*
> ```Smalltalk
>         public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
>         {
>             throw new NotSupportedException();
> ```

maybe just a comment here to explain why this is not supported — it took me a second to understand that this deserialization is expected to be handled by the MeshConverter.

**Review by ikeough — COMMENTED** [review]
After discussion we decided to minimize the impact of this change by making compact JSON serialization affect ONLY meshes. Upon further review it was decided that we could additionally compact the representation by converting it to a true buffer representation. The previous set of type converters for Color, Vector3, Vertex and UV have been removed, and the Mesh converter has been updated to serialize a buffered representation. In addition, the MeshElement now serializes/deserialized its mesh to/from JSON.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/472#-:-MQJxa9hDabCak03PPlA:b-fozyyl)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @andrewheumann and @ikeough)

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/472)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @andrewheumann and @ikeough)

___
*[Elements/src/Model.cs, line 178 at r3](https://reviewable.io/reviews/hypar-io/elements/472#-MQRidBE-sT0wpdGNJ2b:-MQRidBE-sT0wpdGNJ2c:b19oh6p) ([raw file](https://github.com/hypar-io/elements/blob/c11f675387caed08948569c2d1e9d11029170a3a/Elements/src/Model.cs#L178)):*
> ```Smalltalk
>             return Newtonsoft.Json.JsonConvert.SerializeObject(this,
>                                                                indent ? Formatting.Indented : Formatting.None,
>                                                                new JsonConverter[] { new MeshConverter() });
> ```

Check me if I'm wrong here, but I think the converters don't need to be supplied explicitly if you use the `[JsonConverter(typeof(MeshConverter))]` attribute over the Mesh class — which is helpful so that if any other place tries to serialize a mesh it gets the converter automatically.
___
*[Elements/src/Model.cs, line 200 at r3](https://reviewable.io/reviews/hypar-io/elements/472#-MQRhFc8BnPGpNCziBFu:-MQRhFc8BnPGpNCziBFv:bbiikw1) ([raw file](https://github.com/hypar-io/elements/blob/c11f675387caed08948569c2d1e9d11029170a3a/Elements/src/Model.cs#L200)):*
> ```Smalltalk
>                     args.ErrorContext.Handled = true;
>                 },
>                 Converters = new JsonConverter[] { new MeshConverter() }
> ```

See note above

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/472)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @andrewheumann)

___
*[Elements/src/Model.cs, line 178 at r3](https://reviewable.io/reviews/hypar-io/elements/472#-MQRidBE-sT0wpdGNJ2b:-MQSSX0o7xEPQdAjXWQH:b-7jsj4e) ([raw file](https://github.com/hypar-io/elements/blob/c11f675387caed08948569c2d1e9d11029170a3a/Elements/src/Model.cs#L178)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Check me if I'm wrong here, but I think the converters don't need to be supplied explicitly if you use the `[JsonConverter(typeof(MeshConverter))]` attribute over the Mesh class — which is helpful so that if any other place tries to serialize a mesh it gets the converter automatically.
</blockquote></details>

It's a good point, and I've updated the code here to put the attribute directly on the class. 
___
*[Elements/src/Model.cs, line 200 at r3](https://reviewable.io/reviews/hypar-io/elements/472#-MQRhFc8BnPGpNCziBFu:-MQSSWHx5VgN0niXJqQX:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/c11f675387caed08948569c2d1e9d11029170a3a/Elements/src/Model.cs#L200)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

See note above
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/472)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @andrewheumann)

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/472)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ikeough)

**Pull request merged**
