### PR TITLE
Intersect a model with a plane.

### PR DESCRIPTION
**Pull request by ikeough**
BACKGROUND:
For the purpose of creating 2D sections through a model, we need a method that allows the caller to provide a `Plane` and a `Model` and creates the 2D section through the model at that plane.

DESCRIPTION:
- Adds the `Model.Intersect(...)` method which returns a collection of polygons representing the section through the model.
- Add the `BBox3.Intersects(...)` method which returns whether a bounding box is above, below, or intersecting a plane.
- Adds the `Elements.Serialization.SVG` project with wrapper methods to generate plan sections.

TESTING:
- See the `SolidTests.ModelIntersects` method and the `BBox3Tests` for new tests. Two additional tests are added as part of #822 
  
FUTURE WORK:
- This is based on CSGs. I'd prefer to have it based on solid booleans, but solid booleans aren't ready to handle this problem (I tried). When solid booleans are ready we will update `UpdateBoundsAndComputeSolid` to create a cached solid instead of a CSG. 

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

image

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)

### CODE REVIEW

**Review by ikeough — COMMENTED** [review]
The intent is to ensure that whenever a representation is updated, the bounds and the csg are updated as well. By embedding calls to `UpdateBoundsAndComputeSolid` in `UpdateRepresentation` we achieve that _and_ we retain one API that needs to be called by the user to ensure the geometry of their element is up to date, instead of two. There is no impact to the _user_ and a small impact to the _type author_ which is no larger than if we required them to call `base.UpdateBoundsAndComputeSolid` which was only impossible because some types have multiple levels of inheritance.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823#-:-N6ABs8L8YqWP7iXKiHr:blo7w4u)* status: 1 change requests, 0 of 1 approvals obtained

**Review by ikeough — COMMENTED** [review]
After our discussion the calls to update bounds and computed solids have been removed from implementations of `UpdateRepresentations`. There is now one method on the model, `Model.UpdateBoundsAndComputedSolids()` that enables a one time updating of all bounds and computed solids. 

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823#-:-N80qhmT6BUeq1mzuvbQ:by3p543)* status: 1 change requests, 0 of 1 approvals obtained

**Review by wynged — CHANGES_REQUESTED** [review]
This looks super super cool!  Some notes, and tests appear to be failing, but I totally dig this work.

> Reviewed 3 of 25 files at r1, 9 of 12 files at r4, 20 of 21 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823#-:-N85FI5Q17nc96w968mz:b-8mpzr)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`CHANGELOG.md` line 14 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85F17qAuZbXOIAnySu:-N85F17qAuZbXOIAnySv:b3aneeq) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/CHANGELOG.md#L14)):*
> ```Markdown
> - `BBox3.Intersects(Plane plane, out RelationToPlane relationToPlane)`
> - `BBox3.Extend(Vector3 point)`
> - `BBox3.Extend(params Vector3[] points)`
> ```

I think we should add the svg plan `create` methods (or w/e they get called) here.
___
*[`Elements/src/Model.cs` line 274 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N856uhU0k32902T9_Cd:-N856uhU0k32902T9_Ce:b5mgik6) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Model.cs#L274)):*
> ```Smalltalk
>                               out Dictionary<Guid, List<Geometry.Line>> lines)
>         {
>             intersectionPolygons = new Dictionary<Guid, List<Geometry.Polygon>>();
> ```

should we call UpdateBoundsAndComputeSolids at top of this method?  wouldn't want a user to have to do that manually.
___
*[`Elements/src/Model.cs` line 278 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N8575LK6kkDjfz8AK34:-N8575LK6kkDjfz8AK35:bjrnn0v) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Model.cs#L278)):*
> ```Smalltalk
>             lines = new Dictionary<Guid, List<Geometry.Line>>();
> 
>             // var backPlane = new Plane(plane.Origin - plane.Normal * depth, plane.Normal);
> ```

delete commented code.
___
*[`Elements/src/Model.cs` line 289 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N857UMmCltyisuL99pr:-N857UMmCltyisuL99ps:bczx8jy) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Model.cs#L289)):*
> ```Smalltalk
>             allIntersectingElements.AddRange(intersectingElements);
> 
>             IntersectElementsWithPlane(plane, allIntersectingElements, intersectionPolygons, beyondPolygons, lines);
> ```

I think we should have the intersectionPolygons, beyondPolygons and lines dictionaries all return as `out` variables from this method.  They can be created inside there rather than up above and then there's no risk of them getting manipulated in this method.
___
*[`Elements/src/Model.cs` line 308 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N856pQ421UFFBxFu8LW:-N856pQ421UFFBxFu8LX:brvz3od) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Model.cs#L308)):*
> ```Smalltalk
>         public void UpdateBoundsAndComputedSolids()
>         {
>             foreach (GeometricElement geo in Elements.Values.Where(e => e is GeometricElement).Cast<GeometricElement>())
> ```

I think this can just be `var geo` don't need explicit class
___
*[`Elements/src/Geometry/CsgExtensions.cs` line 217 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N859XGj-k0io8_Xmwd1:-N859XGj-k0io8_Xmwd2:bkywru5) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Geometry/CsgExtensions.cs#L217)):*
> ```Smalltalk
>         {
>             var p = (csgPlane.Normal * csgPlane.W).ToVector3();
>             return p.DistanceTo(plane) < 0;
> ```

I think maybe you might want Plane.SignedDistanceTo() for this?  
___
*[`Elements/src/Geometry/Line.cs` line 1270 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85ABNc7erCMSMlKj7f:-N85ABNc7erCMSMlKj7g:b-r9oyq7) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Geometry/Line.cs#L1270)):*
> ```Smalltalk
>     {
>         /// <summary>
>         /// Does this edge intersect the provided plane?
> ```

are these line extensions or edge extensions?  maybe an implicit operator from (Vector3, Vector3) to Line would be cleaner and more generically useful?  
___
*[`Elements/src/Serialization/glTF/GltfExtensions.cs` line 1448 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85BdQb3NhvMtvl6UTz:-N85BdQb3NhvMtvl6UU-:bqzp5kt) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Serialization/glTF/GltfExtensions.cs#L1448)):*
> ```Smalltalk
>             else
>             {
>                 buffers = geometricElement._csg.Tessellate(mergeVertices, geometricElement.ModifyVertexAttributes);
> ```

I think that we can't rely on _csg being set unless we call the new `model.UpdateBoundsAndComputeSolids()` method when we start making the gltf.
___
*[`Elements/test/SolidTests.cs` line 13 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85ByLF54VSuGjP3h6l:-N85ByLF54VSuGjP3h6m:bskt8w8) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/test/SolidTests.cs#L13)):*
> ```Smalltalk
> using Elements.Serialization.JSON;
> using System.Linq;
> using Elements.Spatial;
> ```

not needed usings
___
*[`Elements.Serialization.SVG/src/SvgPlan.cs` line 41 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85DYou-E1zJRjci3Ku:-N85DYou-E1zJRjci3Kv:b-ep45ay) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/src/SvgPlan.cs#L41)):*
> ```Smalltalk
>             var rotation = GetRotationValueForPlan(models, planRotation, planRotationDegrees);
> 
>             var doc = new SvgDocument
> ```

could we put this `doc` declaration inside the Draw method and have Draw return the doc?  passing it in from the outside feels a little inverted
___
*[`Elements.Serialization.SVG/src/SvgPlan.cs` line 72 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85ENAF3UsCNGaWuh0d:-N85ENAF3UsCNGaWuh0e:bhsythh) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/src/SvgPlan.cs#L72)):*
> ```Smalltalk
>         /// <param name="path">The location on disk to write the SVG file.</param>
>         /// <param name="showGrid">If gridlines exist, should they be shown in the plan?</param>
>         public static SvgDocument CreatePlanFromModels(IList<Model> models,
> ```

I think these two methods shouldnt' have the same name given their different return signatures.  Suggest `GetSvgPlanFromModels` for this method, and then `SaveSvgPlanOfModels` up above.  Also lots of duplication, maybe the one that saves the doc could simply call this on and then save the returned document.  
___
*[`Elements.Serialization.SVG/src/SvgPlan.cs` line 133 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85EqLKA0xqSMDS-Od7:-N85EqLKA0xqSMDS-Od8:b-rs8y5f) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/src/SvgPlan.cs#L133)):*
> ```Smalltalk
>         }
> 
>         private static void Draw(IList<Model> models,
> ```

suggest returning doc here as mentioned above.
___
*[`Elements.Serialization.SVG/test/SvgTests.cs` line 35 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85CxqhAjbQPXh4obUz:-N85CxqhAjbQPXh4obV-:byg4beu) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/test/SvgTests.cs#L35)):*
> ```Smalltalk
>                                             _frontContext,
>                                             _backContext,
>                                             "ModelPlan.svg", planRotation: PlanRotation.LongestGridHorizontal);
> ```

can we elevate this path outside of the bin folder, it's a pain to go digging around in there.

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @wynged)

___
*[`CHANGELOG.md` line 14 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85F17qAuZbXOIAnySu:-N8B9W_V2kVYxfqnwfg5:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/CHANGELOG.md#L14)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think we should add the svg plan `create` methods (or w/e they get called) here.
</blockquote></details>

Done.
___
*[`Elements/src/Model.cs` line 278 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N8575LK6kkDjfz8AK34:-N8B9vpPEMxxJTu7SjsS:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Model.cs#L278)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

delete commented code.
</blockquote></details>

Done.
___
*[`Elements/src/Model.cs` line 289 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N857UMmCltyisuL99pr:-N8BEIGH3c_8JVvDewIW:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Model.cs#L289)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think we should have the intersectionPolygons, beyondPolygons and lines dictionaries all return as `out` variables from this method.  They can be created inside there rather than up above and then there's no risk of them getting manipulated in this method.
</blockquote></details>

Done.
___
*[`Elements/src/Model.cs` line 308 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N856pQ421UFFBxFu8LW:-N8BANkJ9BInHoQG23vg:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Model.cs#L308)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think this can just be `var geo` don't need explicit class
</blockquote></details>

Done.
___
*[`Elements/src/Geometry/CsgExtensions.cs` line 217 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N859XGj-k0io8_Xmwd1:-N8BAlhg9D6R0BWeAMPU:b-896fjx) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Geometry/CsgExtensions.cs#L217)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think maybe you might want Plane.SignedDistanceTo() for this?  
</blockquote></details>

Done
___
*[`Elements/src/Geometry/Line.cs` line 1270 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85ABNc7erCMSMlKj7f:-N8BBOuv0Z0zFVx3UcHk:b-jodxwl) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Geometry/Line.cs#L1270)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

are these line extensions or edge extensions?  maybe an implicit operator from (Vector3, Vector3) to Line would be cleaner and more generically useful?  
</blockquote></details>

I've changed this to an instance method on `Plane`. We don't want an implicit operator because it'll allocate a line. We're moving to edges (tuples of Vectors) to avoid allocating lines (see the numerous locations in `Polygon` and `Polyline` where we do this).
___
*[`Elements/src/Serialization/glTF/GltfExtensions.cs` line 1448 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85BdQb3NhvMtvl6UTz:-N8BMuJQEkMN-6QT80H8:bqvrnze) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Serialization/glTF/GltfExtensions.cs#L1448)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think that we can't rely on _csg being set unless we call the new `model.UpdateBoundsAndComputeSolids()` method when we start making the gltf.
</blockquote></details>

We now call `UpdateBoundsAndComputedSolid()` further up the call chain where we call `UpdateRepresentations` to avoid this.
___
*[`Elements.Serialization.SVG/test/SvgTests.cs` line 35 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85CxqhAjbQPXh4obUz:-N8BC1de3FEQx4xQrZmq:be3yynt) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/test/SvgTests.cs#L35)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can we elevate this path outside of the bin folder, it's a pain to go digging around in there.
</blockquote></details>

But the bin folder gets cleaned up, which is what we want.
___
*[`Elements/test/SolidTests.cs` line 13 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85ByLF54VSuGjP3h6l:-N8BBxEz9dK5XezRmNAF:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/test/SolidTests.cs#L13)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

not needed usings
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgPlan.cs` line 41 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85DYou-E1zJRjci3Ku:-N8BM1UmAz-g__K1-iff:b-73k400) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/src/SvgPlan.cs#L41)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

could we put this `doc` declaration inside the Draw method and have Draw return the doc?  passing it in from the outside feels a little inverted
</blockquote></details>

I've called one from the other to clean this up, but we still want two methods. One is just to write the document straightaway. The other is if we want to write the document but then add other things to it, which will be required for custom drawing stuff (like drywall stocking plans)

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 1 of 25 files at r1, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements/src/Geometry/Line.cs` line 1270 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85ABNc7erCMSMlKj7f:-N8OL91y1l76MSE74Ozj:b-6tk9nb) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Geometry/Line.cs#L1270)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I've changed this to an instance method on `Plane`. We don't want an implicit operator because it'll allocate a line. We're moving to edges (tuples of Vectors) to avoid allocating lines (see the numerous locations in `Polygon` and `Polyline` where we do this).
</blockquote></details>

ok, gotcha.
___
*[`Elements.Serialization.SVG/test/SvgTests.cs` line 35 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85CxqhAjbQPXh4obUz:-N8OKtsB2T0mzvBQTo84:b-8785l5) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/test/SvgTests.cs#L35)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

But the bin folder gets cleaned up, which is what we want.
</blockquote></details>

ok if you have a strong preference for test results being inside the compile/bin directory it can stay.
___
*[`Elements.Serialization.SVG/src/SvgPlan.cs` line 41 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85DYou-E1zJRjci3Ku:-N8OKYyP9ap0o-Vsi2sl:biv2dv6) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/src/SvgPlan.cs#L41)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I've called one from the other to clean this up, but we still want two methods. One is just to write the document straightaway. The other is if we want to write the document but then add other things to it, which will be required for custom drawing stuff (like drywall stocking plans)
</blockquote></details>

two methods makes sense, I just think they should have different names since they have such different results.  One returns a Doc, the other returns void because it saved a model.  Maybe "SavePlanFromModel" for the method that takes a path would be more clear.
___
*[`Elements.Serialization.SVG/src/SvgPlan.cs` line 133 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85EqLKA0xqSMDS-Od7:-N8OLlhL6V5MBHVvx8mO:b-3pb8w7) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/src/SvgPlan.cs#L133)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

suggest returning doc here as mentioned above.
</blockquote></details>

ok, this is cleaner now that we call one method from the other, although I still might prefer a structure that doesn't pass the Doc in from the outside of this method I can get over it :)

**Review by wynged — COMMENTED** [review]
> Reviewed 10 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements/src/Model.cs` line 274 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N856uhU0k32902T9_Cd:-N9aZ-mD5ATrk9K2wk3V:bb7f2mf) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements/src/Model.cs#L274)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

should we call UpdateBoundsAndComputeSolids at top of this method?  wouldn't want a user to have to do that manually.
</blockquote></details>

done

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements.Serialization.SVG/src/SvgPlan.cs` line 41 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85DYou-E1zJRjci3Ku:-NA5xOmJDa9HJIbCwDcC:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/src/SvgPlan.cs#L41)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

two methods makes sense, I just think they should have different names since they have such different results.  One returns a Doc, the other returns void because it saved a model.  Maybe "SavePlanFromModel" for the method that takes a path would be more clear.
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgPlan.cs` line 72 at r7](https://reviewable.io/reviews/hypar-io/elements/823#-N85ENAF3UsCNGaWuh0d:-NA5xRA40jZjbzmn6kQS:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/4bb1a7afff5607e0bd6b0c59081ceffcbed08ff1/Elements.Serialization.SVG/src/SvgPlan.cs#L72)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think these two methods shouldnt' have the same name given their different return signatures.  Suggest `GetSvgPlanFromModels` for this method, and then `SaveSvgPlanOfModels` up above.  Also lots of duplication, maybe the one that saves the doc could simply call this on and then save the returned document.  
</blockquote></details>

Done.

**Review by wynged — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements/src/Model.cs` line 104 at r11](https://reviewable.io/reviews/hypar-io/elements/823#-NA6CUNc3H56aQqRvGxO:-NA6CUNc3H56aQqRvGxP:b15zwi8) ([raw file](https://github.com/hypar-io/elements/blob/33b8c924855de0110d6788e1642b7dacc6929e57/Elements/src/Model.cs#L104)):*
> ```Smalltalk
>             {
>                 geo.UpdateRepresentations();
>                 geo.UpdateBoundsAndComputeSolid();
> ```

@andrewheumann  makes a good argument that this shouldn't be done here.  We're already noting that we don't want to do UpdateRepresentation, but we have to because we create elements.  `UpdateBoundsAndComputeSolid()` doesn't have the same justification.

**Review by wynged — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements/src/Model.cs` line 104 at r11](https://reviewable.io/reviews/hypar-io/elements/823#-NA6CUNc3H56aQqRvGxO:-NA6CxB30cqXCNlO7a4p:bf2zlo3) ([raw file](https://github.com/hypar-io/elements/blob/33b8c924855de0110d6788e1642b7dacc6929e57/Elements/src/Model.cs#L104)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

@andrewheumann  makes a good argument that this shouldn't be done here.  We're already noting that we don't want to do UpdateRepresentation, but we have to because we create elements.  `UpdateBoundsAndComputeSolid()` doesn't have the same justification.
</blockquote></details>

We also now call this method in the geometric operations below that require the Solid geometry to exist, so this call isn't necessary.

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 27 at r12](https://reviewable.io/reviews/hypar-io/elements/823#-NA6KII_E6tUa8o_Zjn5:-NA6KII_E6tUa8o_Zjn6:b-odb0kv) ([raw file](https://github.com/hypar-io/elements/blob/59aedc7a34a95713908e83b732f73a93f03bacbf/Elements.Serialization.SVG/src/SvgSection.cs#L27)):*
> ```Smalltalk
>         /// <param name="models">A collection of models to include in the plan.</param>
>         /// <param name="elevation">The elevation at which the plan will be cut.</param>
>         /// <param name="frontContext"></param>
> ```

all the other arguments have descriptions filled in, we should probably do that here.

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 27 at r12](https://reviewable.io/reviews/hypar-io/elements/823#-NA6KII_E6tUa8o_Zjn5:-NA6LLpt7ENJyki0Qsv6:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/59aedc7a34a95713908e83b732f73a93f03bacbf/Elements.Serialization.SVG/src/SvgSection.cs#L27)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

all the other arguments have descriptions filled in, we should probably do that here.
</blockquote></details>

Done.

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/823)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
