### PR TITLE
Add a redirect for docs.

### PR DESCRIPTION
**Pull request by ikeough**
To ensure that github isn't listed in the search results for docs sites, like Getting Started, we should redirect docs here to point to `docs.hypar.io`

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/627)

### CODE REVIEW

**Review by mattc — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/627)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by mattc — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/627)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[docs/index.html, line 179 at r1](https://reviewable.io/reviews/hypar-io/elements/627#-MezjHrIE4FSeHS8fvVH:-MezjHrJ3NDc5S2kTzes:becv60e) ([raw file](https://github.com/hypar-io/elements/blob/0b7a2565acab90f2ce08b6e3d14a35e76728e409/docs/index.html#L179)):*
> ```HTML
>     <script type="text/javascript" src="styles/main.js"></script>
>   </body>
> </html>
> ```

Looks like the closing tags were lost

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/627)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mattc)

___
*[docs/index.html, line 179 at r1](https://reviewable.io/reviews/hypar-io/elements/627#-MezjHrIE4FSeHS8fvVH:-MezkuffCINkoEnT-NXK:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/0b7a2565acab90f2ce08b6e3d14a35e76728e409/docs/index.html#L179)):*
<details><summary><i>Previously, mattc (Matt Campbell) wrote…</i></summary><blockquote>

Looks like the closing tags were lost
</blockquote></details>

Done.

**Review by mattc — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/627)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
