### PR TITLE
Cache glb streams

### PR DESCRIPTION
**Pull request by wynged**
BACKGROUND:
- Adding content elements to the GLTF was slow, partly because we repeatedly fetch the glb from the url.

DESCRIPTION:
- Create a cache for memory streams that will be used anytime a url is recognized.

TESTING:
- there's a test that asserts the speed difference.
  
FUTURE WORK:
- Is there any future work needed or anticipated?  Does this PR create any obvious technical debt?

REQUIRED:
- [ x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Any other notes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/539)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/539)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @wynged)

___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 1108 at r1](https://reviewable.io/reviews/hypar-io/elements/539#-MUoRgc0BXrTheqqs22U:-MUoRgc2EyayTunOwVOI:b-7kop24) ([raw file](https://github.com/hypar-io/elements/blob/5c3d6ebb06143170932a53ae75e46e246e8d932d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1108)):*
> ```Smalltalk
>             if (gltfCache.TryGetValue(gltfLocation, out var foundStream))
>             {
>                 Console.WriteLine("cache hit: " + gltfLocation);
> ```

let's get rid of this for production

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/539)* status: all files reviewed, 1 unresolved discussion (waiting on @wynged)

**Review by wynged — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/539)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

___
*[Elements/src/Serialization/glTF/GltfExtensions.cs, line 1108 at r1](https://reviewable.io/reviews/hypar-io/elements/539#-MUoRgc0BXrTheqqs22U:-MUpOFnp7sBAgIsPeFYj:b-xvdmcy) ([raw file](https://github.com/hypar-io/elements/blob/5c3d6ebb06143170932a53ae75e46e246e8d932d/Elements/src/Serialization/glTF/GltfExtensions.cs#L1108)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

let's get rid of this for production
</blockquote></details>

done.  woops!

**Review by andrewheumann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/539)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @andrewheumann)

**Pull request merged**
