### PR TITLE
Fix #313.

### LINKED ISSUE #313: Beam Profiles reverse at some points when used on a Polygon
**Describe the bug**
Beam Profiles reverse at some points when used on a Polygon, usually for corners that bend inside.

**To Reproduce**
```
var beam = new Beam(poly, Polygon.Rectangle(input.BridgeWidth, input.BridgeHeight), brdigeMaterial);
```

**Expected behavior**
expected a sweep with profile orientation maintained

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
vscode, hypar cli 0.7.1

### PR DESCRIPTION
**Pull request by ikeough**
Fix #313.

This also unveiled a flaw in our logic to get mitered planes along a segmented curve. We were introducing shear into the cross sections of our sweeps because we were transforming to miter transforms instead of _projecting_ to miter planes.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/424)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/424)* status: all files reviewed, 1 unresolved discussion (waiting on @ikeough)

___
*[Elements/src/Geometry/Polyline.cs, line 130 at r1](https://reviewable.io/reviews/hypar-io/elements/424#-ML7w8LrC7FfDECDz2HM:-ML7w8Ls-hE9wOyBPfHp:bhvwly0) ([raw file](https://github.com/hypar-io/elements/blob/aaddb464edf9b99630b752e3d2c08673a070a4cf/Elements/src/Geometry/Polyline.cs#L130)):*
> ```Smalltalk
>                 else
>                 {
>                     // Create the average of the 
> ```

finish comment?

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/424)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Polyline.cs, line 130 at r1](https://reviewable.io/reviews/hypar-io/elements/424#-ML7w8LrC7FfDECDz2HM:-ML9bE4v0Si_ygL_MOO8:b-wjin11) ([raw file](https://github.com/hypar-io/elements/blob/aaddb464edf9b99630b752e3d2c08673a070a4cf/Elements/src/Geometry/Polyline.cs#L130)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

finish comment? 
</blockquote></details>

Comment was removed.

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/424)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @andrewheumann)

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/424)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
