### PR TITLE
Pdf creation + small fixes inside SvgSection

### PR DESCRIPTION
**Pull request by katehryhorenko**
BACKGROUND:
We need to convert svg to pdf

DESCRIPTION:
1. Svg-net library is replaced with Skia. Skia supports PDF creation
2. SvgSection is not static anymore. Now it's possible to create SvgSection class instance. It has all required properties by default to generate stocking plan. 
3.  New extensions like ToSvgLine and ToSvgPolygon that can use SvgSection to get scene bounds
4. OnElementDrawing event that allows to customize elements drawing
5. Draw method was changed a little bit. Just small fixes:
    - document rotation should be around the middle point, otherwise the image is not at the view box. You still can see it if you open svg file, but during conversion to pdf or any other format,  image will be lost. Also, ViewBox should be moved a little bit to fit the image size/location  
                   doc.ViewBox = new SvgViewBox((wOld - ViewBoxWidth) / 2.0f, (ViewBoxHeight - hOld) / 2.0f, ViewBoxWidth, ViewBoxHeight);
                doc.CustomAttributes.Add("transform", $"rotate({rotation} {ViewBoxWidth / 2.0} {ViewBoxHeight / 2.0})");
     - in some reason BaseLineOffset is lost during conversion to pdf, so I replaced it with translate(0, 0.2)

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/916)

### CODE REVIEW

**Review by ikeough — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/916)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj` line 21 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT1sJgDwCVuQz0w-eF:-NGT1sJgDwCVuQz0w-eG:bsbxmtq) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj#L21)):*
> ```XML
>     <PackageReference Include="Svg.Skia" Version="0.6.0-preview2"/>
>     <PackageReference Include="SkiaSharp" Version="2.88.3"/>
>     <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.3"/>
> ```

Is this required when you're not running on the lambda? I know that packages can do cool stuff like pull down platform dependencies depending on how they're built. Just wondering if need to always include this.
___
*[`Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj` line 29 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT2VYW6VkvdFBeWjwS:-NGT2VYW6VkvdFBeWjwT:b-xjtz8w) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj#L29)):*
> ```XML
> 
>     <ItemGroup>
>     <None Include="libSkiaSharp.so" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
> ```

I've never had to do this for a nuget package that targets Linux. Is this required?

I'm getting up to date here: https://github.com/mono/SkiaSharp/issues/312#issuecomment-427607910. But I'm still not 100% sure that this is required.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 38 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT3kwHDgSGjueCK_PX:-NGT3kwHDgSGjueCK_PY:bsoxrhd) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L38)):*
> ```Smalltalk
> 
>     /// <summary>
>     ///
> ```

Empty docs make me sad. May I suggest. `A section of a model serialized to SVG.`
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 45 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT3zsg-zu7KBuA8SD6:-NGT3zsg-zu7KBuA8SD7:b-impef5) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L45)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// This event occurs before element is added to the svg scene.
> ```

"...before _an_ element is added..."
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 57 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT48of82T-xHRNkMAQ:-NGT48of82T-xHRNkMAR:bu239v9) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L57)):*
> ```Smalltalk
>         /// Initializes a new instance of SvgDrawingPlan class
>         /// </summary>
>         /// <param name="models">A collection of models to include in the plan</param>
> ```

"A collection of models to include in the plan." (note the period) All of these doc comments can end in a period.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 88 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT4XBp2NaQDnOqwirK:-NGT4XBp2NaQDnOqwirL:b-618vit) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L88)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Gets or sets an svg context which defines settings for grid elements
> ```

I usually don't say "Gets or sets" because one day we'll decide we don't want to "set" anymore and we'll forget to update the docs. I recommend "The svg context which defines settings for the grid elements." The developer tooling does a pretty good job of telling the user if you can get and set.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 302 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT5Ia-5RgtJ_t1gbkB:-NGT5Ia-5RgtJ_t1gbkC:bdzzdcy) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L302)):*
> ```Smalltalk
>                     }
> ```

Whitespace
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 401 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT5VJR5d3eK3MkjUal:-NGT5VJR5d3eK3MkjUam:b-lvt7t6) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L401)):*
> ```Smalltalk
>         private static BBox3 ComputeSceneBounds(IList<Model> models)
>         {
>             var max = new Vector3(double.MinValue, double.MinValue);
> ```

I've written this exact same code numerous times. Can we add convenience constructors `Vector3.Max` and `Vector3.Min`?
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 413 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT6VZIANpAxncTgV94:-NGT6VZJ9R9BEPpA_Wdq:b-9su47d) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L413)):*
> ```Smalltalk
>                         geo.UpdateBoundsAndComputeSolid();
> 
>                         if (geo._bounds.Max.X > max.X)
> ```

Can we replace this block with `geo._bounds.Extend(new[]{max,min})`?
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 444 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT5QId1q8eSI26b_75:-NGT5QId1q8eSI26b_76:bkkx9cu) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L444)):*
> ```Smalltalk
>             foreach (var model in models)
>             {
>                 var modelWithoutCusromElements = model;
> ```

`modelWithoutCustomElements`
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 600 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT6vIxDv4c5nfHXPc5:-NGT6vIxDv4c5nfHXPc6:bpbkteq) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L600)):*
> ```Smalltalk
>         #region Private fields
> 
>         private readonly List<Model> models = new List<Model>();
> ```

Our general practice is to put private fields at the top of the class and to use C# coding guidelines with camel-cased, prefixed members: https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case

**Review by katehryhorenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/916)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @katehryhorenko)

___
*[`Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj` line 21 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT1sJgDwCVuQz0w-eF:-NGTBeAs4nk01FwO2tvv:b-nso7jj) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj#L21)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Is this required when you're not running on the lambda? I know that packages can do cool stuff like pull down platform dependencies depending on how they're built. Just wondering if need to always include this.
</blockquote></details>

Yes, it's for lambda
___
*[`Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj` line 29 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT2VYW6VkvdFBeWjwS:-NGTBqwC0BBrEue_GklA:b-8ctelg) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj#L29)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I've never had to do this for a nuget package that targets Linux. Is this required?

I'm getting up to date here: https://github.com/mono/SkiaSharp/issues/312#issuecomment-427607910. But I'm still not 100% sure that this is required.
</blockquote></details>

Yes, it didn't work without this file
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 38 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT3kwHDgSGjueCK_PX:-NGTCfst57-7AmSYXHaI:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L38)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Empty docs make me sad. May I suggest. `A section of a model serialized to SVG.`
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 45 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT3zsg-zu7KBuA8SD6:-NGTCjfB9g2GaG-P7kfh:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L45)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

"...before _an_ element is added..."
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 88 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT4XBp2NaQDnOqwirK:-NGTDjka2Bo8I3IzX8-0:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L88)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I usually don't say "Gets or sets" because one day we'll decide we don't want to "set" anymore and we'll forget to update the docs. I recommend "The svg context which defines settings for the grid elements." The developer tooling does a pretty good job of telling the user if you can get and set.
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 302 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT5Ia-5RgtJ_t1gbkB:-NGTDk258ptNqNIuT-xn:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L302)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Whitespace
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 401 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT5VJR5d3eK3MkjUal:-NGTG2T3A5oj6szKVBhG:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L401)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I've written this exact same code numerous times. Can we add convenience constructors `Vector3.Max` and `Vector3.Min`?
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 413 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT6VZIANpAxncTgV94:-NGTHFZW9nlqhBTFVl8n:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L413)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Can we replace this block with `geo._bounds.Extend(new[]{max,min})`?
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 444 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT5QId1q8eSI26b_75:-NGTHKo42TM99GKTPrDh:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L444)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

`modelWithoutCustomElements`
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 600 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT6vIxDv4c5nfHXPc5:-NGTI-8V8GGMHDcsTp0u:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L600)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Our general practice is to put private fields at the top of the class and to use C# coding guidelines with camel-cased, prefixed members: https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case
</blockquote></details>

Done.

**Review by ikeough — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/916)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/Geometry/Vector3.cs` line 79 at r2](https://reviewable.io/reviews/hypar-io/elements/916#-NGcAfWw2LEx-CNPvfo4:-NGcAfWw2LEx-CNPvfo5:b8i4d19) ([raw file](https://github.com/hypar-io/elements/blob/a93aeea593d2ae8e516fd8a699c918c5cf809cd1/Elements/src/Geometry/Vector3.cs#L79)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The smallest possible value of a Elements.Vector
> ```

Recommend "The smallest possible value of _a_ Vector3."
___
*[`Elements/src/Geometry/Vector3.cs` line 87 at r2](https://reviewable.io/reviews/hypar-io/elements/916#-NGcAt-F2Zf1XbAbnBFr:-NGcAt-F2Zf1XbAbnBFs:bv5gkq2) ([raw file](https://github.com/hypar-io/elements/blob/a93aeea593d2ae8e516fd8a699c918c5cf809cd1/Elements/src/Geometry/Vector3.cs#L87)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// The largest possible value of a Elements.Vector
> ```

Recommend "The largest possible value of _a_ Vector3."
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 112 at r2](https://reviewable.io/reviews/hypar-io/elements/916#-NGcA3d03aDvYnzPOYMX:-NGcA3d03aDvYnzPOYMY:b7r8n8j) ([raw file](https://github.com/hypar-io/elements/blob/a93aeea593d2ae8e516fd8a699c918c5cf809cd1/Elements.Serialization.SVG/src/SvgSection.cs#L112)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Gets or sets if gridlines exist, should they be shown in the plan.
> ```

Missed one! Recommend "Should grid lines be shown in the section?"

**Review by katehryhorenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/916)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements/src/Geometry/Vector3.cs` line 79 at r2](https://reviewable.io/reviews/hypar-io/elements/916#-NGcAfWw2LEx-CNPvfo4:-NHUhFvh7ZuAJD6VMrvA:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/a93aeea593d2ae8e516fd8a699c918c5cf809cd1/Elements/src/Geometry/Vector3.cs#L79)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Recommend "The smallest possible value of _a_ Vector3."
</blockquote></details>

Done.
___
*[`Elements/src/Geometry/Vector3.cs` line 87 at r2](https://reviewable.io/reviews/hypar-io/elements/916#-NGcAt-F2Zf1XbAbnBFr:-NHUhFhx5wvsJAfzKeuX:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/a93aeea593d2ae8e516fd8a699c918c5cf809cd1/Elements/src/Geometry/Vector3.cs#L87)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Recommend "The largest possible value of _a_ Vector3."
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 57 at r1](https://reviewable.io/reviews/hypar-io/elements/916#-NGT48of82T-xHRNkMAQ:-NHUhFC26Ann_yHQqFfS:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/f55a84f7c04211e70e27c578995e3db281dd09f5/Elements.Serialization.SVG/src/SvgSection.cs#L57)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

"A collection of models to include in the plan." (note the period) All of these doc comments can end in a period.
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgSection.cs` line 112 at r2](https://reviewable.io/reviews/hypar-io/elements/916#-NGcA3d03aDvYnzPOYMX:-NHUkfs84PsrDiCPft3X:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/a93aeea593d2ae8e516fd8a699c918c5cf809cd1/Elements.Serialization.SVG/src/SvgSection.cs#L112)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Missed one! Recommend "Should grid lines be shown in the section?"
</blockquote></details>

Done.

**Pull request merged**
