### PR TITLE
Csg

### PR DESCRIPTION
**Pull request by ikeough**
BACKGROUND:
For any case where we want to create an opening in an element, we have thus far had to employ tricks to cut those openings, like clipping opening perimeter polygons out of the perimeter of the opening's target (floors, walls, etc.). This required having this clipping code in an element's `UpdateRepresentation` method, which made the element's instance a container for state about a clipping operation.

DESCRIPTION:
This PR implements csg solids using [Frank Krueger's port of OpenJsCad's csg.js](https://github.com/praeclarum/Csg). A csg is created for every solid operation and used during the creation of meshes for visualization. By moving to csg, we remove any clipping code from the elements themselves and apply csg operations when we are creating the visualization. We follow this work by updating openings to apply their subtraction operation after other solid operations are completed. This enables a more general application of openings to any geometric element. With csgs we can also now support IFC boolean operations. Finally, because operations to create openings are dependent on the geometry and transform of the host, we introduce new APIs to `IHasOpenings` to provide a simpler interface for creating openings in walls and floors.

FUTURE WORK:
- Csgs should probably be hidden behind the `Opening` APIs for users who just want to poke holes in things.
- Creating a solid, then a csg, then a mesh for visualization involves copying a lot of data. It isn't fast. It is possible that we could skip creating solids altogether and work with csgs as the primary representation of a solid.

Csg holes added to beams.
image

Csg operation on a topography mesh preserving the texture coordinates of the mesh.
image

Additive and subtractive operations.
image

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/406)

### CODE REVIEW

**Comment by ikeough** [comment]
@mattc Asking for your review so we can start a conversation about how this may or may not work with the csg work you're doing in Hypar's front end.

**Comment by ikeough** [comment]
Relates to #401.

**Review by mattc — COMMENTED** [review]
I was doing BRep stuff in the front end, not CSG.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/406#-:-MJUuMdI-76PEwdDtZkW:bibkf3b)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @mattc)

**Review by mattc — CHANGES_REQUESTED** [review]
> Reviewed 19 of 26 files at r1, 6 of 9 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/406)* status: all files reviewed, 2 unresolved discussions (waiting on @ikeough)

___
*[Elements/src/Interfaces/IHasOpenings.cs, line 4 at r3](https://reviewable.io/reviews/hypar-io/elements/406#-MJlfIji5BMSNR0U3PQN:-MJlfIji5BMSNR0U3PQO:b-1273y3) ([raw file](https://github.com/hypar-io/elements/blob/80d36acde9b02e64eac15bfd40cb45e8152a9227/Elements/src/Interfaces/IHasOpenings.cs#L4)):*
> ```Smalltalk
> 
> using System.Collections.Generic;
> using Elements.Geometry;
> ```

Did this need to be added?
___
*[Elements/test/CsgTests.cs, line 65 at r3](https://reviewable.io/reviews/hypar-io/elements/406#-MJlfbVYE9AwH755Grsz:-MJlfbVZ5yIqY06ZYtzv:b-93qath) ([raw file](https://github.com/hypar-io/elements/blob/80d36acde9b02e64eac15bfd40cb45e8152a9227/Elements/test/CsgTests.cs#L65)):*
> ```Smalltalk
>         //     }
>         //     // </example>
>         // }
> ```

So that this doesn't gradually become broken code, can you add an issue to finish it? (maybe leave the code in the issue)

**Review by ikeough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/406)* status: 27 of 32 files reviewed, 2 unresolved discussions (waiting on @mattc)

___
*[Elements/src/Interfaces/IHasOpenings.cs, line 4 at r3](https://reviewable.io/reviews/hypar-io/elements/406#-MJlfIji5BMSNR0U3PQN:-MK5vWgE8xYM9_qSb-1Z:bj070ae) ([raw file](https://github.com/hypar-io/elements/blob/80d36acde9b02e64eac15bfd40cb45e8152a9227/Elements/src/Interfaces/IHasOpenings.cs#L4)):*
<details><summary><i>Previously, mattc (Matt Campbell) wrote…</i></summary><blockquote>

Did this need to be added?
</blockquote></details>

Previously yes, but later no.
___
*[Elements/test/CsgTests.cs, line 65 at r3](https://reviewable.io/reviews/hypar-io/elements/406#-MJlfbVYE9AwH755Grsz:-MK5vAYA-kew-yDWbhWU:b-jeym8v) ([raw file](https://github.com/hypar-io/elements/blob/80d36acde9b02e64eac15bfd40cb45e8152a9227/Elements/test/CsgTests.cs#L65)):*
<details><summary><i>Previously, mattc (Matt Campbell) wrote…</i></summary><blockquote>

So that this doesn't gradually become broken code, can you add an issue to finish it? (maybe leave the code in the issue)
</blockquote></details>

This has been moved over to benchmarks.

**Review by mattc — APPROVED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/406)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
